# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XTry do
  try do
    defmacro src_defmacro_x_try_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  rescue
    _ -> nil
  end

  def local_site(a, b), do: src_defmacro_x_try_snoc(a, b) # @local
end
