# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XDefaultsHead do
  defp src_defp_x_defaults_head_snoc(a \\ nil, b \\ nil)
  defp src_defp_x_defaults_head_snoc(a, b) when is_nil(a), do: {a, b}
  defp src_defp_x_defaults_head_snoc(a, b), do: {a, b}

  def local_site(a, b), do: src_defp_x_defaults_head_snoc(a, b) # @local

  def uses(a, b), do: {src_defp_x_defaults_head_snoc(), src_defp_x_defaults_head_snoc(a), a, b}
end
