# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XConditional do
  if Code.ensure_loaded?(Kernel) do
    def src_def_x_conditional_snoc(q, x), do: {q, x}
  end

  def local_site(a, b), do: src_def_x_conditional_snoc(a, b) # @local
end
