# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XDefaultsHead do
  @spec src_defdelegate_unresolvable_x_defaults_head_snoc() :: term() # @spec_0
  @spec src_defdelegate_unresolvable_x_defaults_head_snoc(term()) :: term() # @spec_1
  @spec src_defdelegate_unresolvable_x_defaults_head_snoc(term(), term()) :: term() # @spec_2
  defdelegate src_defdelegate_unresolvable_x_defaults_head_snoc(a \\ nil, b \\ nil), to: Src.DefdelegateUnresolvable.XDefaultsHead.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_x_defaults_head_snoc(a, b) # @local
end
