# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XNfc do
  def src_def_x_nfc_snoć(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_nfc_snoć(a, b) # @local
end
