# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XArity do
  defmacro src_defmacro_x_arity_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_arity_snoc(q, x, y), do: quote(do: {unquote(q), unquote(x), unquote(y)})

  def local_site(a, b), do: src_defmacro_x_arity_snoc(a, b) # @local
end
