# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.W4 do
  defdelegate src_defdelegate_unresolvable_w4_snoc(q, x), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoc(q), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoc(q, x, y), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_xsnoc(q, x), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoc_x(q, x), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoc?(q, x), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoc!(q, x), to: Src.DefdelegateUnresolvable.W4.Missing
  defdelegate src_defdelegate_unresolvable_w4_snoć(q, x), to: Src.DefdelegateUnresolvable.W4.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_w4_snoc(a, b) # @local
end
