# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XTry do
  try do
    defdelegate src_defdelegate_compiled_x_try_snoc(q, x), to: Src.DefdelegateCompiled.XTry.Target
  rescue
    _ -> nil
  end

  def local_site(a, b), do: src_defdelegate_compiled_x_try_snoc(a, b) # @local
end
