# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAs.W2.Target do
  def delegated_src_defdelegate_as_w2_snoc(q, x), do: {q, x}
  def delegated_src_defdelegate_as_w2_snoc(q), do: {q}
  def delegated_src_defdelegate_as_w2_snoc(q, x, y), do: {q, x, y}

  def target_marker, do: :ok
end
