# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XLookalikeAbsent do
  defp src_defp_x_lookalike_absent_snoc(q, x), do: {q, x}
  defp src_defp_x_lookalike_absent_xsnoc(q, x), do: {q, x}
  defp src_defp_x_lookalike_absent_snoc_x(q, x), do: {q, x}
  defp src_defp_x_lookalike_absent_snoc?(q, x), do: {q, x}
  defp src_defp_x_lookalike_absent_snoc!(q, x), do: {q, x}
  defp src_defp_x_lookalike_absent_snoć(q, x), do: {q, x}

  def local_site(a, b), do: src_defp_x_lookalike_absent_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_lookalike_absent_xsnoc(a, b), # @uses_0
      src_defp_x_lookalike_absent_snoc_x(a, b), # @uses_1
      src_defp_x_lookalike_absent_snoc?(a, b), # @uses_2
      src_defp_x_lookalike_absent_snoc!(a, b), # @uses_3
      src_defp_x_lookalike_absent_snoć(a, b), # @uses_4
      a,
      b
    }
  end
end
