# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XDefaultsHead do
  @spec src_defp_x_defaults_head_snoc() :: term() # @spec_0
  @spec src_defp_x_defaults_head_snoc(term()) :: term() # @spec_1
  @spec src_defp_x_defaults_head_snoc(term(), term()) :: term() # @spec_2
  defp src_defp_x_defaults_head_snoc(a \\ nil, b \\ nil)
  defp src_defp_x_defaults_head_snoc(a, b) when is_nil(a), do: {a, b}
  defp src_defp_x_defaults_head_snoc(a, b), do: {a, b}

  def local_site(a, b), do: src_defp_x_defaults_head_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_x_defaults_head_snoc(), # @uses_0
      src_defp_x_defaults_head_snoc(a), # @uses_1
      a,
      b
    }
  end
end
