# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAs.XDefaults do
  defdelegate src_defdelegate_as_x_defaults_snoc(q, x \\ nil), to: Src.DefdelegateAs.XDefaults.Target, as: :delegated_src_defdelegate_as_x_defaults_snoc

  def local_site(a, b), do: src_defdelegate_as_x_defaults_snoc(a, b) # @local
end
