# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XAritySeparate do
  defdelegate src_defdelegate_unresolvable_x_arity_separate_snoc(), to: Src.DefdelegateUnresolvable.XAritySeparate.Missing
  defdelegate src_defdelegate_unresolvable_x_arity_separate_snoc(a), to: Src.DefdelegateUnresolvable.XAritySeparate.Missing
  defdelegate src_defdelegate_unresolvable_x_arity_separate_snoc(a, b), to: Src.DefdelegateUnresolvable.XAritySeparate.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @local
end
