# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XArity do
  defmacrop src_defmacrop_x_arity_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_x_arity_snoc(q, x, y), do: quote(do: {unquote(q), unquote(x), unquote(y)})

  def local_site(a, b), do: src_defmacrop_x_arity_snoc(a, b) # @local

  def uses(a, b), do: {src_defmacrop_x_arity_snoc(a, b, a), a, b}
end
