# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XArity do
  defdelegate src_defdelegate_unresolvable_x_arity_snoc(q, x), to: Src.DefdelegateUnresolvable.XArity.Missing
  defdelegate src_defdelegate_unresolvable_x_arity_snoc(q, x, y), to: Src.DefdelegateUnresolvable.XArity.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_x_arity_snoc(a, b) # @local
end
