# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XAritySeparate do
  defdelegate src_defdelegate_x_arity_separate_snoc(), to: Src.Defdelegate.XAritySeparate.Target
  defdelegate src_defdelegate_x_arity_separate_snoc(a), to: Src.Defdelegate.XAritySeparate.Target
  defdelegate src_defdelegate_x_arity_separate_snoc(a, b), to: Src.Defdelegate.XAritySeparate.Target

  def local_site(a, b), do: src_defdelegate_x_arity_separate_snoc(a, b) # @local
end
