# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFrom.XArityAbsent do
  require EEx

  EEx.function_from_string(:def, :src_eex_function_from_x_arity_absent_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: src_eex_function_from_x_arity_absent_snoc(a, b) # @local
end
