# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XUnquoteName do
  def unquote(:src_def_x_unquote_name_snoc)(q, x), do: {q, x}

  def local_site(a, b), do: src_def_x_unquote_name_snoc(a, b) # @local
end
