# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XConditional do
  if Code.ensure_loaded?(Kernel) do
    defdelegate src_defdelegate_unresolvable_x_conditional_snoc(q, x), to: Src.DefdelegateUnresolvable.XConditional.Missing
  end

  def local_site(a, b), do: src_defdelegate_unresolvable_x_conditional_snoc(a, b) # @local
end
