# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defguardp.XLookalikeAbsent do
  defguardp src_defguardp_x_lookalike_absent_snoc(q, x) when is_list(q) or is_list(x)
  defguardp src_defguardp_x_lookalike_absent_xsnoc(q, x) when is_list(q) or is_list(x)
  defguardp src_defguardp_x_lookalike_absent_snoc_x(q, x) when is_list(q) or is_list(x)
  defguardp src_defguardp_x_lookalike_absent_snoc?(q, x) when is_list(q) or is_list(x)
  defguardp src_defguardp_x_lookalike_absent_snoc!(q, x) when is_list(q) or is_list(x)
  defguardp src_defguardp_x_lookalike_absent_snoć(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: src_defguardp_x_lookalike_absent_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defguardp_x_lookalike_absent_xsnoc(a, b), # @uses_0
      src_defguardp_x_lookalike_absent_snoc_x(a, b), # @uses_1
      src_defguardp_x_lookalike_absent_snoc?(a, b), # @uses_2
      src_defguardp_x_lookalike_absent_snoc!(a, b), # @uses_3
      src_defguardp_x_lookalike_absent_snoć(a, b), # @uses_4
      a,
      b
    }
  end
end
