# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XUnless do
  unless Code.ensure_loaded?(Matrix.Absent) do
    defdelegate src_defdelegate_x_unless_snoc(q, x), to: Src.Defdelegate.XUnless.Target
  end

  def local_site(a, b), do: src_defdelegate_x_unless_snoc(a, b) # @local
end
