# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.W3 do
  defp src_defp_w3_snoc(q, x), do: {q, x}
  defp src_defp_w3_xsnoc(q, x), do: {q, x}
  defp src_defp_w3_snoc_x(q, x), do: {q, x}
  defp src_defp_w3_snoc?(q, x), do: {q, x}
  defp src_defp_w3_snoc!(q, x), do: {q, x}
  defp src_defp_w3_snoć(q, x), do: {q, x}

  def local_site(a, b), do: src_defp_w3_snoc(a, b) # @local

  def uses(a, b), do: {src_defp_w3_xsnoc(a, b), src_defp_w3_snoc_x(a, b), src_defp_w3_snoc?(a, b), src_defp_w3_snoc!(a, b), src_defp_w3_snoć(a, b), a, b}
end
