# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XDefaults do
  defmacro src_defmacro_x_defaults_snoc(q, x \\ nil), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: src_defmacro_x_defaults_snoc(a, b) # @local
end
