# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAs.W1 do
  def local_forward(a, b), do: src_defdelegate_as_w1_snoc(a, b) # @local_forward

  @spec src_defdelegate_as_w1_snoc(term(), term()) :: term() # @spec_2
  defdelegate src_defdelegate_as_w1_snoc(q, x), to: Src.DefdelegateAs.W1.Target, as: :delegated_src_defdelegate_as_w1_snoc

  def local_site(a, b), do: src_defdelegate_as_w1_snoc(a, b) # @local
end
