# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.W2 do
  defdelegate src_defdelegate_compiled_w2_snoc(q, x), to: Src.DefdelegateCompiled.W2.Target
  defdelegate src_defdelegate_compiled_w2_snoc(q), to: Src.DefdelegateCompiled.W2.Target
  defdelegate src_defdelegate_compiled_w2_snoc(q, x, y), to: Src.DefdelegateCompiled.W2.Target

  def local_site(a, b), do: src_defdelegate_compiled_w2_snoc(a, b) # @local
end
