# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XConditional do
  if Code.ensure_loaded?(Kernel) do
    defmacrop src_defmacrop_x_conditional_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  end

  def local_site(a, b), do: src_defmacrop_x_conditional_snoc(a, b) # @local

  def uses(a, b), do: {a, b}
end
