# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XArityZero do
  defdelegate src_defdelegate_compiled_x_arity_zero_snoc(), to: Src.DefdelegateCompiled.XArityZero.Target
  defdelegate src_defdelegate_compiled_x_arity_zero_snoc(q, x), to: Src.DefdelegateCompiled.XArityZero.Target

  def local_site(a, b), do: src_defdelegate_compiled_x_arity_zero_snoc(a, b) # @local
end
