# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Def.XDefaults do
  def src_def_x_defaults_snoc(q, x \\ nil), do: {q, x}

  def local_site(a, b), do: src_def_x_defaults_snoc(a, b) # @local
end
