# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XOtherModule.Other do
  defdelegate src_defdelegate_x_other_module_snoc(q, x), to: Src.Defdelegate.XOtherModule.Other.Target
end
