# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.W4 do
  defp src_defp_w4_snoc(q, x) when is_list(q), do: {q, x}
  defp src_defp_w4_snoc(queue, item), do: {queue, item}
  defp src_defp_w4_snoc(q), do: {q}
  defp src_defp_w4_snoc(q, x, y), do: {q, x, y}
  defp src_defp_w4_xsnoc(q, x), do: {q, x}
  defp src_defp_w4_snoc_x(q, x), do: {q, x}
  defp src_defp_w4_snoc?(q, x), do: {q, x}
  defp src_defp_w4_snoc!(q, x), do: {q, x}
  defp src_defp_w4_snoć(q, x), do: {q, x}

  def local_site(a, b), do: src_defp_w4_snoc(a, b) # @local

  def uses(a, b), do: {src_defp_w4_snoc(a), src_defp_w4_snoc(a, b, a), src_defp_w4_xsnoc(a, b), src_defp_w4_snoc_x(a, b), src_defp_w4_snoc?(a, b), src_defp_w4_snoc!(a, b), src_defp_w4_snoć(a, b), a, b}
end
