# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.EexFunctionFrom.W1 do
  require EEx

  def local_forward(a, b), do: src_eex_function_from_w1_snoc(a, b) # @local_forward

  @spec src_eex_function_from_w1_snoc(term(), term()) :: term() # @spec_2
  EEx.function_from_string(:def, :src_eex_function_from_w1_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: src_eex_function_from_w1_snoc(a, b) # @local
end
