# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XFor do
  for _ <- [:once] do
    defdelegate src_defdelegate_x_for_snoc(q, x), to: Src.Defdelegate.XFor.Target
  end

  def local_site(a, b), do: src_defdelegate_x_for_snoc(a, b) # @local
end
