# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.W3.Target do
  def src_defdelegate_w3_snoc(q, x), do: {q, x}
  def src_defdelegate_w3_xsnoc(q, x), do: {q, x}
  def src_defdelegate_w3_snoc_x(q, x), do: {q, x}
  def src_defdelegate_w3_snoc?(q, x), do: {q, x}
  def src_defdelegate_w3_snoc!(q, x), do: {q, x}
  def src_defdelegate_w3_snoć(q, x), do: {q, x}

  def target_marker, do: :ok
end
