# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.W3 do
  defmacro src_defmacro_w3_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w3_xsnoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w3_snoc_x(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w3_snoc?(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w3_snoc!(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w3_snoć(q, x), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: src_defmacro_w3_snoc(a, b) # @local
end
