# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.XAritySeparate do
  defmacrop src_defmacrop_x_arity_separate_snoc(), do: quote(do: {})
  defmacrop src_defmacrop_x_arity_separate_snoc(a), do: quote(do: {unquote(a)})
  defmacrop src_defmacrop_x_arity_separate_snoc(a, b), do: quote(do: {unquote(a), unquote(b)})

  def local_site(a, b), do: src_defmacrop_x_arity_separate_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defmacrop_x_arity_separate_snoc(), # @uses_0
      src_defmacrop_x_arity_separate_snoc(a), # @uses_1
      a,
      b
    }
  end
end
