# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.W4 do
  defmacro src_defmacro_w4_snoc(q, x) when is_list(q), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w4_snoc(queue, item), do: quote(do: {unquote(queue), unquote(item)})
  defmacro src_defmacro_w4_snoc(q), do: quote(do: {unquote(q)})
  defmacro src_defmacro_w4_snoc(q, x, y), do: quote(do: {unquote(q), unquote(x), unquote(y)})
  defmacro src_defmacro_w4_xsnoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w4_snoc_x(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w4_snoc?(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w4_snoc!(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_w4_snoć(q, x), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: src_defmacro_w4_snoc(a, b) # @local
end
