# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.W4 do
  defp src_defp_w4_snoc(q, x) when is_list(q), do: {q, x}
  defp src_defp_w4_snoc(queue, item), do: {queue, item}
  defp src_defp_w4_snoc(q), do: {q}
  defp src_defp_w4_snoc(q, x, y), do: {q, x, y}
  defp src_defp_w4_xsnoc(q, x), do: {q, x}
  defp src_defp_w4_snoc_x(q, x), do: {q, x}
  defp src_defp_w4_snoc?(q, x), do: {q, x}
  defp src_defp_w4_snoc!(q, x), do: {q, x}
  defp src_defp_w4_snoć(q, x), do: {q, x}

  def local_site(a, b), do: src_defp_w4_snoc(a, b) # @local

  def uses(a, b) do
    {
      src_defp_w4_snoc(a), # @uses_0
      src_defp_w4_snoc(a, b, a), # @uses_1
      src_defp_w4_xsnoc(a, b), # @uses_2
      src_defp_w4_snoc_x(a, b), # @uses_3
      src_defp_w4_snoc?(a, b), # @uses_4
      src_defp_w4_snoc!(a, b), # @uses_5
      src_defp_w4_snoć(a, b), # @uses_6
      a,
      b
    }
  end
end
