# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XNotACall do
  defdelegate src_defdelegate_x_not_a_call_snoc(q, x), to: Src.Defdelegate.XNotACall.Target

  def local_site(a, b), do: src_defdelegate_x_not_a_call_snoc(a, b) # @local
end
