# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XArity do
  @spec src_defp_x_arity_snoc(term(), term()) :: term() # @spec_2
  defp src_defp_x_arity_snoc(q, x), do: {q, x}
  @spec src_defp_x_arity_snoc(term(), term(), term()) :: term() # @spec_3
  defp src_defp_x_arity_snoc(q, x, y), do: {q, x, y}

  def local_site(a, b), do: src_defp_x_arity_snoc(a, b) # @local

  def uses(a, b), do: {src_defp_x_arity_snoc(a, b, a), a, b}
end
