# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.W1 do
  defp src_defp_w1_snoc(q, x), do: {q, x}

  def local_site(a, b), do: src_defp_w1_snoc(a, b) # @local

  def uses(a, b), do: {a, b}
end
