# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XArity.Target do
  def src_defdelegate_x_arity_snoc(q, x), do: {q, x}
  def src_defdelegate_x_arity_snoc(q, x, y), do: {q, x, y}

  def target_marker, do: :ok
end
