# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XAritySeparate do
  defp src_defp_x_arity_separate_snoc(), do: {}
  defp src_defp_x_arity_separate_snoc(a), do: {a}
  defp src_defp_x_arity_separate_snoc(a, b), do: {a, b}

  def local_site(a, b), do: src_defp_x_arity_separate_snoc(a, b) # @local

  def uses(a, b), do: {src_defp_x_arity_separate_snoc(), src_defp_x_arity_separate_snoc(a), a, b}
end
