# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.W2 do
  defdelegate src_defdelegate_unresolvable_w2_snoc(q, x), to: Src.DefdelegateUnresolvable.W2.Missing
  defdelegate src_defdelegate_unresolvable_w2_snoc(q), to: Src.DefdelegateUnresolvable.W2.Missing
  defdelegate src_defdelegate_unresolvable_w2_snoc(q, x, y), to: Src.DefdelegateUnresolvable.W2.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_w2_snoc(a, b) # @local
end
