# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateImports.W1 do
  defdelegate src_defdelegate_imports_w1_snoc(q, x), to: Src.DefdelegateImports.W1.Target

  def local_site(a, b), do: src_defdelegate_imports_w1_snoc(a, b) # @local
end
