# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XCond.Target do
  cond do
    Code.ensure_loaded?(Kernel) ->
    def src_defdelegate_x_cond_snoc(q, x), do: {q, x}
  end

  def target_marker, do: :ok
end
