# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateUnresolvable.XDefaults do
  defdelegate src_defdelegate_unresolvable_x_defaults_snoc(q, x \\ nil), to: Src.DefdelegateUnresolvable.XDefaults.Missing

  def local_site(a, b), do: src_defdelegate_unresolvable_x_defaults_snoc(a, b) # @local
end
