# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacrop.W3 do
  defmacrop src_defmacrop_w3_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_w3_xsnoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_w3_snoc_x(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_w3_snoc?(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_w3_snoc!(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacrop src_defmacrop_w3_snoć(q, x), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: src_defmacrop_w3_snoc(a, b) # @local

  def uses(a, b), do: {src_defmacrop_w3_xsnoc(a, b), src_defmacrop_w3_snoc_x(a, b), src_defmacrop_w3_snoc?(a, b), src_defmacrop_w3_snoc!(a, b), src_defmacrop_w3_snoć(a, b), a, b}
end
