# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defp.XCond do
  cond do
    Code.ensure_loaded?(Kernel) ->
    defp src_defp_x_cond_snoc(q, x), do: {q, x}
  end

  def local_site(a, b), do: src_defp_x_cond_snoc(a, b) # @local

  def uses(a, b), do: {a, b}
end
