# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAsAttribute.W1.Target do
  def delegated_src_defdelegate_as_attribute_w1_snoc(q, x), do: {q, x}

  def target_marker, do: :ok
end
