# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defmacro.XLookalikeAbsent do
  defmacro src_defmacro_x_lookalike_absent_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_lookalike_absent_xsnoc(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_lookalike_absent_snoc_x(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_lookalike_absent_snoc?(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_lookalike_absent_snoc!(q, x), do: quote(do: {unquote(q), unquote(x)})
  defmacro src_defmacro_x_lookalike_absent_snoć(q, x), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: src_defmacro_x_lookalike_absent_snoc(a, b) # @local
end
