# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateAsAttribute.W1 do
  @target :delegated_src_defdelegate_as_attribute_w1_snoc
  defdelegate src_defdelegate_as_attribute_w1_snoc(q, x), to: Src.DefdelegateAsAttribute.W1.Target, as: @target

  def local_site(a, b), do: src_defdelegate_as_attribute_w1_snoc(a, b) # @local
end
