# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.Defdelegate.XCond do
  cond do
    Code.ensure_loaded?(Kernel) ->
    defdelegate src_defdelegate_x_cond_snoc(q, x), to: Src.Defdelegate.XCond.Target
  end

  def local_site(a, b), do: src_defdelegate_x_cond_snoc(a, b) # @local
end
