# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Def.XAritySeparateUndefined do
  alias ExDbgi.Def.XAritySeparate
  alias ExDbgi.Def.XAritySeparate, as: Aliased
  import ExDbgi.Def.XAritySeparate

  def at_unqualified_arity_3(a, b), do: ex_dbgi_def_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
