# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Def.XNfcBroken do
  alias ExDbgi.Def.XNfc
  alias ExDbgi.Def.XNfc, as: Aliased
  import ExDbgi.Def.XNfc

  def at_arity_1(a, _b), do: ExDbgi.Def.XNfc.ex_dbgi_def_x_nfc_snoć(a) # @arity_1
end
