package org.elixir_lang.code_insight

import com.intellij.ide.impl.HeadlessDataManager
import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiCompiledFile
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiManager
import com.intellij.psi.PsiPolyVariantReference
import com.intellij.psi.ResolveState
import com.intellij.psi.util.PsiTreeUtil
import com.intellij.testFramework.EdtTestUtil
import com.intellij.testFramework.LightPlatformTestCase
import com.intellij.testFramework.fixtures.CodeInsightTestFixture
import com.intellij.testFramework.fixtures.IdeaTestFixtureFactory
import com.intellij.testFramework.fixtures.impl.LightTempDirTestFixtureImpl
import com.intellij.openapi.diagnostic.ControlFlowException
import com.intellij.testFramework.utils.parameterInfo.MockCreateParameterInfoContext
import com.intellij.testFramework.utils.parameterInfo.MockParameterInfoUIContext
import org.elixir_lang.psi.Arguments
import com.intellij.ide.structureView.StructureViewBuilder
import com.intellij.ide.structureView.TreeBasedStructureViewBuilder
import com.intellij.ide.util.treeView.smartTree.TreeElement
import com.intellij.openapi.util.Disposer
import org.elixir_lang.ElixirSyntaxHighlighter
import com.intellij.openapi.editor.colors.EditorColorsManager
import com.intellij.openapi.editor.colors.TextAttributesKey
import com.intellij.openapi.editor.markup.TextAttributes
import java.awt.Color
import java.io.File
import com.intellij.codeInsight.lookup.LookupManager
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.psi.PsiDocumentManager
import junit.framework.TestCase.assertEquals
import junit.framework.TestCase.assertFalse
import junit.framework.TestCase.assertNotNull
import junit.framework.TestCase.assertTrue
import kotlinx.coroutines.CancellationException
import com.intellij.testFramework.junit5.TestApplication
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.DynamicContainer
import org.junit.jupiter.api.DynamicContainer.dynamicContainer
import org.junit.jupiter.api.DynamicTest.dynamicTest
import org.junit.jupiter.api.TestFactory
import org.elixir_lang.code_insight.matrix.Scenario
import org.elixir_lang.code_insight.matrix.Applicability
import org.elixir_lang.code_insight.matrix.Backing
import org.elixir_lang.code_insight.matrix.Binding
import org.elixir_lang.code_insight.matrix.Cell
import org.elixir_lang.code_insight.matrix.Complaint
import org.elixir_lang.code_insight.matrix.complaintOf
import org.elixir_lang.code_insight.matrix.namedArities
import org.elixir_lang.code_insight.matrix.suggestionsOf
import org.elixir_lang.inspection.References
import org.elixir_lang.inspection.UnresolvableModuleQualifier
import org.elixir_lang.code_insight.matrix.Crossing
import org.elixir_lang.code_insight.matrix.DeclaringModule
import org.elixir_lang.code_insight.matrix.Definition
import org.elixir_lang.code_insight.matrix.Expected
import org.elixir_lang.code_insight.matrix.Feature
import org.elixir_lang.code_insight.matrix.Fixtures
import org.elixir_lang.code_insight.matrix.Head
import org.elixir_lang.code_insight.matrix.LOCAL
import org.elixir_lang.code_insight.matrix.MACRO_FORMS
import org.elixir_lang.code_insight.matrix.MatrixProjectDescriptor
import org.elixir_lang.code_insight.matrix.Place
import org.elixir_lang.code_insight.matrix.Site
import org.elixir_lang.code_insight.matrix.UNAVAILABLE_PHRASE
import org.elixir_lang.code_insight.matrix.nfc
import org.elixir_lang.code_insight.matrix.sees
import org.elixir_lang.code_insight.matrix.privateUse
import org.elixir_lang.code_insight.matrix.specName
import org.elixir_lang.documentation.quickDocumentationAtCaret
import org.elixir_lang.psi.CallDefinitionClause
import org.elixir_lang.psi.call.Call

/**
 * One test per cell: a [Feature] asked at one [Place] of one scenario, where a scenario is a backing, a declaration
 * form and a world of definitions and calls generated by `generate.exs`. The expected answers come from real Elixir:
 * the compiler says which definition each call binds to, and quoting the scenario's source says what that
 * definition's heads are.
 *
 * Every cell of a scenario shares one fixture, opened by the first of them to run and closed after the last, because
 * the fixture's set-up and tear-down cost more than the features themselves. Each cell still passes or fails on its
 * own outcome.
 *
 * `testData/.../code_intelligence_matrix/gap-map.tsv` records which cells were red when this suite was written, one
 * sorted row each, so a refactor of the code underneath can be diffed cell by cell. It is **data, not an oracle**:
 * nothing reads it, and a cell going green is an improvement to re-record rather than a row to defend.
 */
@TestApplication
class CodeIntelligenceMatrixTest {
    @TestFactory
    fun cells(): List<DynamicContainer> =
        Fixtures.oracle.scenarios
            .filterNot { Backing.of(it).guardOnly }
            .map { it to Group.cellsOf(it) }
            // An empty container is reported as a passing test named after the scenario.
            .filter { (_, cells) -> cells.isNotEmpty() }
            .map { (scenario, cells) ->
                dynamicContainer(
                    "${scenario.backing},${scenario.form},${scenario.world}",
                    cells.map { (place, feature) ->
                        dynamicTest(Cell(scenario, feature, place).testName) { Group.check(scenario, place, feature) }
                    }
                )
            }

    companion object {
        /**
         * Closes whichever scenario a filtered or aborted run left open, then the light project every scenario
         * shared: JUnit 5's leak check at the end of the run reports it otherwise, where JUnit 3 closed it itself.
         */
        @AfterAll
        @JvmStatic
        fun close() {
            Group.closeOpen()
            EdtTestUtil.runInEdtAndWait<Throwable> { LightPlatformTestCase.closeAndDeleteProject() }
        }
    }
}

/**
 * Every applicable feature asked at every place of [scenario], in one light fixture.
 *
 * The fixture is per scenario rather than per place because its set-up and tear-down cost more than the features
 * themselves, and a scenario's places all ask about the same files. It is not shared any more widely than that: a
 * feature that edits has to be the only thing in the project defining what it edits, so scenarios cannot overlap.
 */
private class Group(val scenario: Scenario) {
    private lateinit var myFixture: CodeInsightTestFixture

    /** The place being asked; every applicable feature is asked there before the next place is opened. */
    private lateinit var place: Place
    private val project get() = myFixture.project
    private val backing get() = Backing.of(scenario)

    /** What `generate.exs` prefixes every function name with, so one project can hold every scenario at once. */
    private val scope get() = "${scenario.backing}_${scenario.form}_${scenario.world}_"
    /** Every caller the scenario has, by its fixture path: the ordinary one, and the broken ones where it has them. */
    private val callerFiles = linkedMapOf<String, VirtualFile>()
    private val sourceFiles = mutableMapOf<DeclaringModule, VirtualFile>()
    private val originals = linkedMapOf<VirtualFile, String>()
    private var opened = false

    private var unchecked = cellsOf(scenario).size
    private var closed = false

    /** Set once the scenario cannot go on - its fixture would not open, or a place would not bind - and failing every later cell. */
    private var broken: Throwable? = null
    private var binding: Binding? = null

    /**
     * Asks [feature] at [atPlace], opening the fixture for this scenario's first cell and closing it after its last.
     *
     * A failure to open the fixture or to bind a place fails that cell and every later one of the scenario, as it
     * would leave them asking an unknown project.
     */
    fun check(atPlace: Place, feature: Feature) {
        try {
            broken?.let { throw it }
            EdtTestUtil.runInEdtAndWait<Throwable> {
                if (!this::myFixture.isInitialized) breakOnFailure { timed("setUp") { setUp() } }
                if (!this::place.isInitialized || place != atPlace) {
                    place = atPlace
                    opened = false
                    binding = breakOnFailure { timed("binding", place = atPlace) { binding() } }
                }
                timed("check", feature, atPlace) {
                    try {
                        check(feature, binding)
                    } catch (e: Throwable) {
                        if (e is ControlFlowException || e is CancellationException) breakOnFailure { throw e }
                        throw e
                    } finally {
                        if (feature.edits && broken == null) restore()
                    }
                }
            }
        } finally {
            if (--unchecked == 0) closeOpen()
        }
    }

    private inline fun <T> breakOnFailure(block: () -> T): T =
        try {
            block()
        } catch (e: Throwable) {
            if (e !is VirtualMachineError) broken = e
            close()
            throw e
        }

    fun close() {
        if (closed) return
        closed = true
        // `myFixture` is only unset when the factory itself threw, and then there is nothing to tear down; calling it
        // anyway would replace the real failure with an uninitialized-property one.
        if (this::myFixture.isInitialized) timed("tearDown") { myFixture.tearDown() }
    }

    /**
     * [block]'s result, with its wall time appended to [TIMING] when that is set.
     *
     * The XML charges a scenario's set-up to its first cell and a place's binding to that place's first; this says
     * which phase the time goes to. A feature's time includes the [restore] after it.
     */
    private inline fun <T> timed(phase: String, feature: Feature? = null, place: Place? = null, block: () -> T): T {
        val timing = TIMING ?: return block()
        val start = System.nanoTime()
        try {
            return block()
        } finally {
            val nanos = System.nanoTime() - start
            timing.appendText(
                listOf(scenario.backing, scenario.form, scenario.world, phase, feature?.testName ?: "", place?.id ?: "", nanos)
                    .joinToString("\t", postfix = "\n")
            )
        }
    }

    private fun setUp() {
        val factory = IdeaTestFixtureFactory.getFixtureFactory()
        val fixture = factory.createLightFixtureBuilder(MatrixProjectDescriptor, "matrix").fixture
        myFixture = factory.createCodeInsightFixture(fixture, LightTempDirTestFixtureImpl(true))
        myFixture.testDataPath = Fixtures.DIRECTORY
        myFixture.setUp()
        HeadlessDataManager.fallbackToProductionDataManager(myFixture.testRootDisposable)
        // What the editor says is a question only an enabled inspection answers, and `References` ships off by
        // default. Both are enabled for every group rather than only the diagnostic cells, so that a complaint one
        // of them makes about a place the other is being asked about is visible instead of suppressed.
        myFixture.enableInspections(References(), UnresolvableModuleQualifier())

        scenario.callers.forEach { callerFiles[it] = myFixture.copyFileToProject(it) }
        scenario.modules.filterNot { it.compiled }.forEach { sourceFiles[it] = myFixture.copyFileToProject(it.source) }
        (callerFiles.values + sourceFiles.values).forEach { originals[it] = text(it) }
    }

    /** Puts every copied file back as it was copied, so the next feature starts from the same project. */
    private fun restore() {
        LookupManager.hideActiveLookup(project)
        WriteCommandAction.runWriteCommandAction(project) {
            for ((file, text) in originals) {
                val document = FileDocumentManager.getInstance().getDocument(file)!!
                // Only what the feature changed: resetting an untouched document to its own text still reparses it.
                if (document.text != text) document.setText(text)
            }
        }
        PsiDocumentManager.getInstance(project).commitAllDocuments()
        // Unsaved, the next group's copy of the same file would meet a document that differs from the disk.
        FileDocumentManager.getInstance().saveAllDocuments()
        opened = false
    }

    private fun check(feature: Feature, binding: Binding?) {
        when (feature) {
            Feature.GO_TO_DECLARATION -> checkGoToDeclaration(binding)
            Feature.FIND_USAGES -> checkFindUsages(binding)
            Feature.LABEL -> checkLabel(binding)
            Feature.QUICK_DOCUMENTATION -> checkQuickDocumentation(binding)
            Feature.UNAVAILABLE_NOTICE -> checkUnavailableNotice(binding)
            Feature.PARAMETER_INFO -> checkParameterInfo(binding)
            Feature.CTRL_CLICK -> checkCtrlClick(binding!!)
            Feature.HIGHLIGHTING -> checkHighlighting(binding)
            Feature.DIAGNOSTIC -> checkDiagnostic(binding)
            Feature.STRUCTURE_VIEW -> checkStructureView(binding!!)
            Feature.BREADCRUMBS -> checkBreadcrumbs(binding!!)
            Feature.COMPLETION_OFFERED -> checkCompletionOffered()
            Feature.COMPLETION_INSERTED -> checkCompletionInserted()
            Feature.RENAME -> checkRename(binding)
            Feature.INCOMPLETE_RESOLUTION -> checkIncompleteResolution()
        }
    }

    /**
     * One signature for each arity of the called name in the called module, taken from that arity's first clause.
     *
     * Every arity of the name is shown, whichever one the call passes - and at a call whose arity none of them
     * covers, that is still the answer, because the arity is what the developer could not remember.
     */
    private fun checkParameterInfo(binding: Binding?) {
        openAt(place)
        moveIntoArguments()

        val site = siteOrNull()!!
        val module = binding?.let { definition(it).first } ?: scenario.main
        val expected = module.definitions
            .filter { nfc(it.name) == nfc(site.name) && site.sees(it) }
            .map { definition -> Expected.heads(module, definition.name, definition.maxArity).first().parameters.joinToString(", ") }
            .map(::nfc)
            .sorted()

        assertEquals("Parameter Info at ${place.id} showed the wrong signatures", expected, parameterInfoSignaturesAtCaret().map(::nfc).sorted())
    }

    /** Ctrl+Click on a declaration shows its usages, offering only the clause the caret is on. */
    private fun checkCtrlClick(binding: Binding) {
        openAt(place)
        val navigation = myFixture.gtduNavigationAtCaret()

        // Without its identity hash, which differs from run to run and would make every such cell's message "change".
        val described = navigation.toString().replace(IDENTITY_HASH, "")
        assertTrue("Ctrl+Click on ${place.id} should show its usages, but resolved to $described", navigation is GtduNavigation.ShowUsages)
        assertEquals(
            "Show Usages at ${place.id} offered the wrong targets",
            listOf(nfc(presentedHead(binding).label)),
            (navigation as GtduNavigation.ShowUsages).variants.map(::nfc)
        )
    }

    /**
     * The annotator's key on the name: a declaration's for a head, and a call's for a use, by whether the definition
     * is a function or a macro. A variable, atom or keyword that shares the name gets neither call key.
     */
    private fun checkHighlighting(binding: Binding?) {
        openAt(place)
        val nameStart = myFixture.editor.caretModel.offset - 1
        val keys = highlightKeysAt(nameStart)
        val macro = scenario.form in MACRO_FORMS
        // A guard is a macro Elixir allows in a guard, and it has keys of its own; they fall back to the function
        // keys, so an unconfigured scheme shows it as a function, but the key says what it is.
        val guard = scenario.form in GUARD_FORMS

        if (binding == null) {
            val callKeys = listOf(ElixirSyntaxHighlighter.FUNCTION_CALL, ElixirSyntaxHighlighter.MACRO_CALL, GUARD_CALL).map { it.externalName }
            assertEquals("${place.id} is highlighted as a call", emptyList<String>(), keys.filter { it in callKeys })
        } else {
            val expected = when {
                place is Place.Head && guard -> GUARD_DECLARATION
                place is Place.Head && macro -> ElixirSyntaxHighlighter.MACRO_DECLARATION
                place is Place.Head -> ElixirSyntaxHighlighter.FUNCTION_DECLARATION
                guard -> GUARD_CALL
                macro -> ElixirSyntaxHighlighter.MACRO_CALL
                else -> ElixirSyntaxHighlighter.FUNCTION_CALL
            }.externalName
            assertTrue("${place.id} should be highlighted `$expected`, but has $keys", expected in keys)
        }
    }

    /**
     * The keys whose attributes the annotator applied at [offset]. It applies merged attributes rather than keys, and
     * the test scheme gives several keys the same attributes, so each key gets a foreground of its own while this runs.
     *
     * The five keys are put back in a `finally`, with one caveat worth stating rather than hiding: a key the global
     * scheme only inherits is read as its inherited value and written back as an explicit one. The value is identical,
     * so no cell can see the difference, but the scheme is left marginally more explicit than it was found for the
     * rest of the test JVM.
     */
    private fun highlightKeysAt(offset: Int): List<String> =
        highlights().filter { it.startOffset == offset }.mapNotNull { it.key }.sorted()

    /** One highlight of the open file: where, how severe, what it says, and which of [highlightKeysAt]'s keys it is. */
    private class Highlight(val startOffset: Int, val endOffset: Int, val severity: HighlightSeverity, val description: String?, val key: String?)

    /**
     * The open file's highlights, with each of [highlightKeysAt]'s keys given a foreground of its own while they are
     * computed, so an applied attribute can be read back as the key that applied it.
     *
     * The highlights depend on the project's text, not on the caret, so one pass answers every place in the file and
     * both [checkHighlighting] and [checkDiagnostic]. Without this every place re-highlighted the whole file twice,
     * a fifth of the suite. A pass is only reused while [pristine], and [restore] puts the project back to exactly
     * that text.
     */
    private fun highlights(): List<Highlight> {
        val file = myFixture.file.virtualFile
        val pristine = pristine()
        highlightsByFile[file]?.takeIf { pristine }?.let { return it }

        val scheme = EditorColorsManager.getInstance().globalScheme
        val previous = HIGHLIGHT_KEYS.associateWith { scheme.getAttributes(it) }
        val distinct = HIGHLIGHT_KEYS.withIndex().associate { (index, key) -> key to TextAttributes(Color(1, 2, 3 + index), null, null, null, 0) }

        return try {
            distinct.forEach { (key, attributes) -> scheme.setAttributes(key, attributes) }
            myFixture.doHighlighting().map { info ->
                Highlight(
                    info.startOffset,
                    info.endOffset,
                    info.severity,
                    info.description,
                    distinct.entries.firstOrNull { it.value == info.forcedTextAttributes }?.key?.externalName
                )
            }
        } finally {
            previous.forEach { (key, attributes) -> scheme.setAttributes(key, attributes) }
        }.also { if (pristine) highlightsByFile[file] = it }
    }

    private val highlightsByFile = mutableMapOf<VirtualFile, List<Highlight>>()

    /**
     * What the editor says about the caret's position: [inspectionDescriptionsAtCaret], read from [highlights]
     * rather than from a highlighting pass of its own.
     */
    private fun inspectionDescriptionsAtCaret(): List<String> {
        val document = myFixture.editor.document
        val caret = myFixture.caretOffset
        val line = document.getLineNumber(caret)
        val start = document.getLineStartOffset(line)
        val end = document.getLineEndOffset(line)

        if (DUMP_HIGHLIGHTS) {
            println("highlights on line ${line + 1}, caret at $caret (`${document.charsSequence.subSequence(caret, minOf(caret + 30, end))}`):")
            highlights().filter { it.startOffset >= start && it.endOffset <= end }.forEach {
                println("  ${it.startOffset}..${it.endOffset} `${document.charsSequence.subSequence(it.startOffset, it.endOffset)}` ${it.severity} ${it.description}")
            }
        }

        return highlights()
            .filter { it.severity >= HighlightSeverity.WARNING }
            .filter { it.startOffset >= start && it.endOffset <= end && caret in it.startOffset..it.endOffset }
            .mapNotNull { it.description }
            .distinct()
            .sorted()
    }

    /** Whether every copied file's document has the text it was copied with, and nothing is waiting to be committed. */
    private fun pristine(): Boolean =
        !PsiDocumentManager.getInstance(project).hasUncommitedDocuments() &&
            originals.all { (file, text) -> FileDocumentManager.getInstance().getDocument(file)!!.text == text }

    /**
     * What the editor says about the call, which is the only feature here that asks what the developer is *told*
     * rather than where they are taken. Everything else can see that resolution failed; none of them can see
     * whether the reason was explained, or explained wrongly.
     *
     * Three answers, and the middle one is the point. A correct call is not complained about. A call at an arity
     * nothing covers is complained about as an arity, because the editor knows the arities and the developer has
     * just demonstrated that they do not - this is what the compiler itself does, answering *"undefined or
     * private. Did you mean: * snoc/2"*. A call to a name nothing declares gets the complaint that says so, and
     * exists here mainly so the middle answer has something to be distinguished from: a plugin that says "does
     * not resolve to anything" to both is wrong about one of them and looks right about the other.
     *
     * A category, never a sentence - [complaintOf] is the one place the current wordings appear, so improving one
     * reddens nothing. The arity complaint is held to one thing more: it has to *name the arities*. That is
     * content rather than wording, the same way [UNAVAILABLE_PHRASE] is, and without it the category is a
     * distinction the plugin makes only to itself - "only resolves to invalid results" tells a developer who
     * cannot remember whether it was two arguments or three exactly nothing, where the compiler's own
     * *"Did you mean: * snoc/2"* answers them outright.
     */
    private fun checkDiagnostic(binding: Binding?) {
        openAt(place)
        val site = siteOrNull()!!
        val candidates = candidates(site)
        val expected = when {
            site.diagnostic == null -> emptyList()
            candidates.isNotEmpty() -> listOf(Complaint.ARITY_MISMATCH.name)
            else -> listOf(Complaint.UNRESOLVED.name)
        }
        val said = inspectionDescriptionsAtCaret()

        assertEquals(
            "The editor says the wrong thing about ${place.id}, which the compiler called: ${site.diagnostic?.message?.trim() ?: "correct"}",
            expected,
            said.map(::complaintOf).distinct().sorted()
        )

        val suggested = site.diagnostic?.message?.let(::suggestionsOf).orEmpty()

        if (suggested.isNotEmpty()) {
            // The compiler already tells the developer what they may have meant, and an editor naming less than that,
            // or something else, is less help than the build. Its list is fuzzy on the name, not only the arity: a
            // call of a name nothing declares is pointed at the name that is declared.
            assertEquals(
                "The editor's complaint about ${place.id} does not name what the compiler suggests: $said",
                suggested,
                said.flatMap(::namedArities).distinct().sorted()
            )
        } else if (expected == listOf(Complaint.UNRESOLVED.name)) {
            // The compiler names nothing - "undefined or private" of a private function says no more - so naming an arity
            // tells the developer of a function they cannot call.
            assertEquals(
                "The editor's complaint about ${place.id} names what the compiler does not: $said",
                emptyList<String>(),
                said.flatMap(::namedArities).distinct().sorted()
            )
        } else if (expected == listOf(Complaint.ARITY_MISMATCH.name)) {
            // Every arity a candidate covers, defaults included, less any an `import only:`/`except:` hides from
            // this site: naming the one arity the developer can call here is the answer, not the definition's widest.
            val visible = site.visible?.map(::nfc)
            val arities = candidates
                .map { definition(it).second }
                .flatMap { definition -> (definition.minArity..definition.maxArity).map { "${definition.name}/$it" } }
                .filter { visible == null || nfc(it) in visible }

            assertTrue(
                "The editor complains about ${place.id} without saying which arities there are, so it leaves the developer where it found them: $said does not name any of $arities",
                said.any { description -> arities.any(description::contains) }
            )
        }
    }

    /** The declaring file's structure view has the definition as `name/arity`, with one child per clause it keeps. */
    private fun checkStructureView(binding: Binding) {
        openAt(place)
        val (module, definition) = definition(binding)
        val file = myFixture.file.virtualFile
        val builder = StructureViewBuilder.getProvider().getStructureViewBuilder(file.fileType, file, project)
            as? TreeBasedStructureViewBuilder
            ?: throw AssertionError("${file.name} has no tree-based structure view")
        val model = builder.createStructureViewModel(myFixture.editor)

        try {
            val entries = mutableListOf<Pair<String, Int>>()
            fun walk(element: TreeElement) {
                entries += nfc(element.presentation.presentableText.orEmpty()) to element.children.size
                element.children.forEach(::walk)
            }
            walk(model.root)

            val name = "${nfc(definition.name)}/${definition.maxArity}"
            // Every head the declaration writes, which for a defaults world is one more than `Definition.clauses`:
            // the bodiless head is not a clause, but the structure view still shows it under the definition.
            // A `@spec` of the definition is shown under it too, as the other thing written about it. One of a lower arity a
            // default covers is shown under that arity's own entry, which is how the view lists a definition with defaults.
            val specs = scenario.sites.count { specName(it.id) && it.file == module.source && nfc(it.name) == nfc(definition.name) && it.arity == definition.maxArity }
            val heads = Expected.heads(module, definition.name, definition.maxArity).size + specs
            assertTrue(
                "Structure view has no `$name` with $heads head(s) and spec(s); it has ${entries.filter { it.first.contains('/') }}",
                entries.any { it.first == name && it.second == heads }
            )
        } finally {
            Disposer.dispose(model)
        }
    }

    /** With the caret in a head, the breadcrumbs end with the module and the definition's `name/arity`. */
    private fun checkBreadcrumbs(binding: Binding) {
        openAt(place)
        val (_, definition) = definition(binding)
        val provider = org.elixir_lang.breadcrumbs.Provider()
        val crumbs = generateSequence(myFixture.file.findElementAt(myFixture.editor.caretModel.offset)) { it.parent }
            .filter { provider.acceptElement(it) }
            .map { nfc(provider.getElementInfo(it)) }
            .toList()
            .reversed()
        val arity = if (definition.minArity == definition.maxArity) "${definition.maxArity}" else "${definition.minArity}..${definition.maxArity}"

        assertEquals(
            "Breadcrumbs at ${place.id} are wrong",
            listOf(scenario.main.module, "${nfc(definition.name)}/$arity"),
            crumbs.takeLast(2)
        )
    }

    private fun parameterInfoSignaturesAtCaret(): List<String> {
        val handler = ParameterInfo()
        val context = MockCreateParameterInfoContext(myFixture.editor, myFixture.file)
        val arguments = handler.findElementForParameterInfo(context) ?: return emptyList()
        handler.showParameterInfo(arguments, context)

        return context.itemsToShow.orEmpty().map { item ->
            val uiContext = MockParameterInfoUIContext<Arguments>(arguments)
            uiContext.currentParameterIndex = 0
            handler.updateUI(item as Signature, uiContext)
            uiContext.text
        }
    }

    /** Every definition visible at the call whose name starts with what is typed; a look-alike's prefix is its own. */
    private fun checkCompletionOffered() {
        val (name, prefix) = typeCallPrefix()
        val offered = myFixture.completionCandidatesAtCaret().map(::nfc).filter { it.startsWith(prefix) }.distinct().sorted()

        assertEquals("Typing `$prefix` at ${place.id} offered the wrong names (typing toward `$name`)", visibleNames(prefix), offered)
    }

    /**
     * Completing a name writes a real signature - `snoc(q, x)`, with the parameters there to be typed over - not
     * an empty argument list. `snoc()` is what puts the developer at a call no arity covers in the first place,
     * and it is the IDE that put them there.
     *
     * Any of the name's arities is accepted, because the gesture takes the first candidate offered under the name
     * and the popup collapses the arities into one lookup string, so which one was picked is not the caller's to
     * choose. Where a zero-arity definition genuinely exists, `snoc()` is one of those signatures and is right.
     *
     * The signature is the one a caller could type - [org.elixir_lang.code_insight.matrix.Head.callSignature], without the `\\` that declares a
     * default - since inserting a default marker at a call site would insert a syntax error.
     */
    private fun checkCompletionInserted() {
        val (name, prefix) = typeCallPrefix()
        val line = typedLine()
        val text = myFixture.completeCandidateOrSoleMatchAtCaret(name, '\n') { nfc(it) == name }
        val inserted = nfc(text.split('\n')[line.index])
        val site = siteOrNull()!!
        val module = scenario.module(site.binding?.module ?: scenario.main.module)
        val signatures = module.definitions
            .filter { nfc(it.name) == nfc(name) && site.sees(it) }
            .sortedBy { it.maxArity }
            .map { nfc(line.before + Expected.heads(module, it.name, it.maxArity).first().callSignature) }

        assertTrue(
            "Completing `$prefix` to `$name` at ${place.id} inserted `$inserted`, not one of $signatures",
            inserted in signatures
        )
    }

    /**
     * Source: every head of the definition and every call the compiler bound to it are renamed, and nothing else
     * changes. Compiled: the rename is refused, because the definition is in a read-only `.beam`. A call nothing
     * covers: the rename is refused, because renaming would edit a function the call does not make. Refused is
     * either nothing offered to rename, or the rename dialog refusing with a reason saying it cannot be renamed and
     * editing nothing.
     */
    private fun checkRename(binding: Binding?) {
        openAt(place)

        if (binding == null) {
            assertRenameRefused("no definition covers that call", "nothing")
            return
        }

        if (definition(binding).first.compiled) {
            assertRenameRefused("the definition is compiled", definition(binding).second.name)
            return
        }

        val (module, definition) = definition(binding)
        val newName = renamed(definition.name)
        val positions = scenario.sites
            .filter { site -> site.binding?.let { it.module == module.module && definition.covers(it) } == true }
            .map { it.file to (it.line to it.column) }
        // A declaration spells the name as its form does: an embed's atom is the name without the suffix the embed adds.
        val declarationName = EMBED_SUFFIXES.firstOrNull { scenario.form == GENERATOR_EMBED && newName.endsWith(it) }
            ?.let(newName::removeSuffix) ?: newName
        val declarationPositions = module.declarations
            .filter { nfc(it.name) == nfc(definition.name) && it.arity == definition.maxArity }
            .map { module.source to (it.line to it.column) }

        myFixture.renameTargetAtCaret(newName)

        val wrong = originals.keys.mapNotNull { file ->
            val path = callerFiles.entries.firstOrNull { it.value == file }?.key
                ?: scenario.modules.single { sourceFiles[it] == file }.source
            val heads = declarationPositions.filter { it.first == path }.map { it.second }
            val declared = replaceNames(keepDelegationTarget(module, originals.getValue(file), heads), heads, declarationName)
            val expected = replaceNames(declared, positions.filter { it.first == path }.map { it.second }, newName)
            val actual = FileDocumentManager.getInstance().getDocument(file)!!.text

            if (actual == expected) null else "${file.name}: ${firstDifference(expected, actual)}"
        }

        assertEquals("Renaming ${definition.name} to $newName from ${place.id} changed the wrong text", emptyList<String>(), wrong)
    }

    /**
     * Resolved as code still being typed - how completion and parameter info resolve it - a call the compiler rejected for
     * its name has no valid result either: a name that only starts like a declared one, or one the call cannot see, is
     * not made right by typing more of the arguments. Candidates it is offered stay invalid.
     */
    private fun checkIncompleteResolution() {
        openAt(place)
        val reference = myFixture.file.findReferenceAt(myFixture.caretOffset) as? PsiPolyVariantReference
        val valid = reference?.multiResolve(true).orEmpty()
            .filter { it.isValidResult }
            .map { result -> result.element?.let { "${it.containingFile?.name}: ${it.text.lineSequence().first().take(80)}" } ?: "an element-less result" }

        assertEquals("Resolving ${place.id} as code being typed found valid results", emptyList<String>(), valid)
    }

    // -- Typing a call ----------------------------------------------------------------------

    private class TypedLine(val index: Int, val before: String)

    /** The line the call at [place] is on, and its text up to the call's name. */
    private fun typedLine(): TypedLine {
        val site = scenario.sites.single { it.id == place.id }
        val file = fileOf(site)
        val lines = originals.getValue(file).split('\n')
        val line = lines[site.line - 1]
        return TypedLine(site.line - 1, line.substring(0, site.column - 1))
    }

    /** Cuts the call at [place] back to the first three letters of its name, with the caret after them. */
    private fun typeCallPrefix(): Pair<String, String> {
        val site = scenario.sites.single { it.id == place.id }
        // The site's own name, not the binding's: a call at an arity nothing defines still names what it meant.
        val name = nfc(site.name)
        // Every name starts with its scenario, so three letters of the name itself are the three after that.
        val prefix = name.take(scope.length + 3)
        val file = fileOf(site)
        val line = typedLine()
        // Opening rewrites the file on disk, which conflicts with an unsaved edit, so it comes first.
        myFixture.configureFromExistingVirtualFile(file)
        val document = myFixture.editor.document
        val lineStart = document.getLineStartOffset(line.index)
        val lineEnd = document.getLineEndOffset(line.index)

        WriteCommandAction.runWriteCommandAction(project) {
            document.replaceString(lineStart, lineEnd, line.before + prefix)
        }
        PsiDocumentManager.getInstance(project).commitDocument(document)
        myFixture.editor.caretModel.moveToOffset(lineStart + line.before.length + prefix.length)
        opened = false

        return name to prefix
    }

    /**
     * The names a call at [place] can reach that start with [prefix]: its module's, and for an import, nothing
     * else. A call at an arity nothing defines reaches the same module - what the developer is typing toward is
     * unaffected by their having got the arity wrong.
     *
     * The module's own `local_site/2` is not among them at any place, including [LOCAL]: [prefix] always opens with
     * the scenario's `<backing>_<form>_<world>_` scope, which an unprefixed helper cannot start with.
     */
    private fun visibleNames(prefix: String): List<String> {
        val site = siteOrNull()!!
        val module = scenario.module(site.binding?.module ?: scenario.main.module)

        return module.definitions.filter(site::sees).map { nfc(it.name) }.filter { it.startsWith(prefix) }.distinct().sorted()
    }

    private fun fileOf(site: Site): VirtualFile =
        callerFiles[site.file] ?: sourceFiles.getValue(scenario.modules.single { it.source == site.file })

    // -- Renaming ---------------------------------------------------------------------------

    /**
     * `snoc` becomes `renamed`; a trailing `?` or `!` is kept, as renaming it away would change what the name means.
     * The new name keeps the scenario prefix, or two scenarios sharing the project would rename to the same name.
     */
    private fun renamed(name: String): String =
        scope + "renamed" + name.takeLast(1).takeIf { it == "?" || it == "!" }.orEmpty() +
            // An embed's function is its atom plus a suffix, so a name without the suffix is one no embed can declare.
            EMBED_SUFFIXES.firstOrNull { scenario.form == GENERATOR_EMBED && name.endsWith(it) }.orEmpty()

    /**
     * Rename at the caret is refused because [why]: nothing is offered, or whichever of the offered targets the user
     * picks is refused by the rename dialog's validator - which the test engine reports as an exception carrying the
     * validator's reason - and nothing is edited. Any other failure is not a refusal the user could read.
     */
    private fun assertRenameRefused(why: String, name: String) {
        val targets = myFixture.renameTargetsAtCaret()

        for (target in targets) {
            val failure = runCatching { myFixture.renameTarget(target, renamed(name)) }.exceptionOrNull()
            val reason = generateSequence(failure) { it.cause }.mapNotNull { it.message }.firstOrNull { "cannot be renamed" in it }
            assertNotNull(
                "Rename at ${place.id} should be refused, as $why, but offered $targets and $target " +
                    (failure?.let { "failed with $it" } ?: "renamed it"),
                reason
            )
            val changed = originals.filter { (file, text) -> FileDocumentManager.getInstance().getDocument(file)!!.text != text }.keys.map { it.name }
            assertEquals("Rename at ${place.id} of $target was refused ($reason) but still changed", emptyList<String>(), changed)
        }
    }

    /**
     * Renaming a `defdelegate` renames the delegation, not what it calls: the target keeps its name, so a delegation
     * without `as:` gains `as: :<its old name>` to go on calling it. One that already has `as:` keeps it unchanged.
     */
    private fun keepDelegationTarget(module: DeclaringModule, text: String, heads: List<Pair<Int, Int>>): String {
        if (module.delegateTo == null || module.delegateAs != null) return text
        val lines = text.split('\n').toMutableList()

        for ((line, column) in heads) {
            val current = lines[line - 1]
            val name = IDENTIFIER.find(current, column - 1)?.value ?: throw AssertionError("No identifier at $line:$column of `$current`")
            val to = DELEGATE_TO.find(current) ?: throw AssertionError("No `to:` in the delegation `$current`")
            lines[line - 1] = current.substring(0, to.range.last + 1) + ", as: :$name" + current.substring(to.range.last + 1)
        }

        return lines.joinToString("\n")
    }

    /** [text] with the identifier at each 1-based (line, column) replaced by [newName]. */
    private fun replaceNames(text: String, positions: List<Pair<Int, Int>>, newName: String): String {
        val lines = text.split('\n').toMutableList()

        for ((line, column) in positions.sortedWith(compareBy({ it.first }, { -it.second }))) {
            val current = lines[line - 1]
            val start = column - 1
            val length = IDENTIFIER.find(current, start)?.takeIf { it.range.first == start }?.value?.length
                ?: throw AssertionError("No identifier at $line:$column of `$current`")
            lines[line - 1] = current.substring(0, start) + newName + current.substring(start + length)
        }

        return lines.joinToString("\n")
    }

    private fun firstDifference(expected: String, actual: String): String {
        val expectedLines = expected.split('\n')
        val actualLines = actual.split('\n')
        val index = (0 until maxOf(expectedLines.size, actualLines.size)).first { expectedLines.getOrNull(it) != actualLines.getOrNull(it) }
        return "line ${index + 1}: expected `${expectedLines.getOrNull(index)?.trim()}`, got `${actualLines.getOrNull(index)?.trim()}`"
    }

    private fun text(file: VirtualFile): String = String(file.contentsToByteArray(), file.charset)

    /**
     * A correct call navigates to its definition's heads. A call at an arity nothing defines navigates to the
     * heads of every arity of the name instead - one target navigates straight there, several open the chooser -
     * because the arity is precisely what the developer could not remember, and refusing to move is the least
     * useful answer available. A place that is not a call at all still navigates nowhere.
     */
    private fun checkGoToDeclaration(binding: Binding?) {
        openAt(place)
        val landed = myFixture.gotoDeclarationTargetsAtCaret().orEmpty().map { target ->
            target.destination?.let(::describeLine) ?: "a target with no destination"
        }.sorted()

        if (atWrongArity(binding)) {
            val candidates = candidates(siteOrNull()!!).flatMap(::headLines).distinct().sorted()
            assertEquals("Go To Declaration from ${place.id} did not offer the declared arities", candidates, landed)
        } else if (binding == null) {
            val functionHeads = headLines(primary())
            assertEquals("Go To Declaration from ${place.id} landed on a function head", emptyList<String>(), landed.filter { it in functionHeads })
        } else {
            // A `@spec` describes the definition it is written over, so from a delegate's spec the user lands on the
            // `defdelegate` itself, not on the function it delegates to.
            val expected = if (specName(place.id)) headLines(binding) else goToDeclarationLines(binding)
            assertEquals("Go To Declaration from ${place.id} landed on the wrong heads", expected, landed)
        }
    }

    private fun checkFindUsages(binding: Binding?) {
        openAt(place)
        val targets = myFixture.searchTargetCountAtCaret()
        // With several targets the IDE asks which; what a user can reach is every target's usages, one after another.
        val found = myFixture.everyTargetPsiUsagesAtCaret(project).filterNot { it.declaration }.map { usage ->
            usageSite(usage.file, usage.range.startOffset)
        }.sorted()

        if (atWrongArity(binding)) {
            // Asked for the uses of a name the caller got the arity of wrong, the answer is the uses of that name -
            // the same candidates Go To Declaration offers, not silence.
            assertEquals(
                "Find Usages from ${place.id} did not find the uses of the declared arities, from $targets search targets at the caret",
                candidates(siteOrNull()!!).flatMap(::boundSites).distinct().sorted(),
                found
            )
        } else if (binding == null) {
            val functionCalls = boundSites(primary())
            assertEquals(
                "Find Usages from ${place.id} found calls of the function from $targets search targets at the caret",
                emptyList<String>(),
                found.filter { it in functionCalls }
            )
        } else {
            assertEquals(
                "Find Usages from ${place.id} found the wrong calls from $targets search targets at the caret",
                boundSites(binding),
                found
            )
        }
    }

    private fun checkLabel(binding: Binding?) {
        openAt(place)
        val labels = myFixture.searchTargetPresentableTextsAtCaret().map(::nfc)

        if (atWrongArity(binding)) {
            // The candidates have to name themselves, or a chooser listing them says nothing a developer who is
            // already unsure of the arity can act on.
            assertEquals(
                "The search targets at ${place.id} do not present the declared arities",
                candidates(siteOrNull()!!).map { nfc(heads(it).first().label) }.sorted(),
                labels.sorted()
            )
        } else if (binding == null) {
            val functionLabels = heads(primary()).map { nfc(it.label) }
            assertEquals("The search target at ${place.id} presents the function", emptyList<String>(), labels.filter { it in functionLabels })
        } else {
            assertEquals("The search target at ${place.id} presents the wrong text", listOf(nfc(presentedHead(binding).label)), labels)
        }
    }

    /**
     * Every definition of the name, in ascending arity order, whichever arity the call passes.
     *
     * Taken from IEx's `h Module.fun`, which given a bare name shows every definition of it, and deliberately not
     * from IEx's other half: given an explicit `Module.fun/0` it says *"No documentation for ... was found"* and
     * stops. In an editor the developer never typed the arity - completion did - so answering "nothing" to the
     * question "what are the arguments?" would be the IDE refusing to answer its own mistake. Every arity is
     * shown, and where there is more than one a header at the top lists their signatures, each linking to its
     * entry, so the developer can see at a glance that a choice exists.
     *
     * Deliberately not asserted: which entry the view opens scrolled to, since that is carried by the
     * `DocumentationResult` and never reaches the HTML; how the matching arity is marked out; and the anchors'
     * naming scheme, which is the implementation's to choose so long as the header's links resolve.
     */
    private fun checkQuickDocumentation(binding: Binding?) {
        openAt(place)
        val html = myFixture.quickDocumentationAtCaret(project)?.let { nfc(it.replace('\n', ' ')) }

        if (binding == null && !atWrongArity(binding)) {
            val signature = nfc(heads(primary()).first().signature)
            assertFalse("Quick Documentation at ${place.id} documents the function: $html", html?.contains(signature) == true)
            return
        }

        val documented = binding ?: candidates(siteOrNull()!!).first()
        val module = definition(documented).first
        val signatures = module.definitions
            .filter { nfc(it.name) == nfc(documented.name) }
            .sortedBy { it.maxArity }
            .map { nfc(Expected.heads(module, it.name, it.maxArity).first().signature) }

        assertNotNull("Quick Documentation at ${place.id} showed nothing", html)
        assertEquals(
            "Quick Documentation at ${place.id} does not show every arity in ascending order: $html",
            signatures,
            signatures.filter { html!!.contains(it) }.sortedBy { html!!.indexOf(it) }
        )
        assertTrue("Quick Documentation does not show `${module.module}`: $html", html!!.contains(module.module))

        if (signatures.size > 1) {
            val entries = signatures.associateWith { html.indexOf(it, html.indexOf(it) + 1) }

            assertEquals(
                "Quick Documentation at ${place.id} shows no header listing every signature: $html",
                emptyList<String>(),
                entries.filterValues { it < 0 }.keys.toList()
            )

            val header = html.take(entries.values.min())

            assertTrue(
                "Quick Documentation at ${place.id} lists the signatures among its entries rather than above them: $html",
                signatures.all { header.contains(it) }
            )
            assertTrue(
                "Quick Documentation's header at ${place.id} does not link each signature to its entry: $html",
                occurrences(header, "href=\"#") >= signatures.size
            )
        }
    }

    /**
     * Where the reader does not have everything the author wrote, the popups the developer asks say so.
     *
     * This is the other half of writing `_` for a parameter the artefact never recorded. `_` stops the IDE
     * claiming a name the author never chose, but on its own it leaves the developer to guess why the IDE has
     * less to say about this module than the last one - and guessing wrong means filing a bug for a gap no fix
     * can close. One sentence turns that into something they can act on: find a build of the dependency that was
     * not stripped. Asserted as a category rather than a sentence, through [UNAVAILABLE_PHRASE], so the wording
     * stays the implementation's.
     *
     * It is a feature of its own rather than a line in [checkQuickDocumentation] because those cells are red for
     * other reasons in exactly the scenarios this asks about, and an assertion that can only run once something
     * else is fixed reports nothing in the meantime.
     */
    private fun checkUnavailableNotice(binding: Binding?) {
        openAt(place)
        // A wrong-arity call is described by the candidates Quick Documentation offers there, so it is owed the
        // same word about them; a variable or an atom is describing nothing and is owed none.
        val described = binding ?: siteOrNull()?.takeIf { it.diagnostic != null }?.let { candidates(it).firstOrNull() }
        val module = described?.let { definition(it).first }
        val wanted = module?.complete == false
        val shown = linkedMapOf<String, Boolean>()

        shown["Quick Documentation"] = myFixture.quickDocumentationAtCaret(project).orEmpty().says(UNAVAILABLE_PHRASE)

        if (Crossing.applicability(scenario, Feature.PARAMETER_INFO, place) is Applicability.Applicable) {
            moveIntoArguments()
            shown["Parameter Info"] = parameterInfoSignaturesAtCaret().any { it.says(UNAVAILABLE_PHRASE) }
        }

        assertEquals(
            if (wanted) {
                "${module!!.beam} was compiled without debug info, so what it cannot say about ${place.id} should be said out loud"
            } else {
                "Nothing is missing at ${place.id}, so nothing should claim it is"
            },
            shown.keys.associateWith { wanted },
            shown
        )
    }

    private fun String.says(phrase: String): Boolean = contains(phrase, ignoreCase = true)

    /**
     * Parameter Info answers from inside the argument list, not from the name the caret opened on.
     *
     * A site with no argument list after the caret is one [Crossing.applicability] should have ruled out; saying so
     * beats moving the caret to offset 0 and answering about whatever happens to be at the top of the file.
     */
    private fun moveIntoArguments() {
        val caret = myFixture.editor.caretModel.offset
        val openingParenthesis = myFixture.editor.document.text.indexOf('(', caret)

        if (openingParenthesis < 0) throw AssertionError("${place.id} has no argument list after the caret to move into")

        myFixture.editor.caretModel.moveToOffset(openingParenthesis + 1)
        opened = false
    }

    private fun occurrences(text: String, of: String): Int =
        generateSequence(text.indexOf(of)) { text.indexOf(of, it + 1) }.takeWhile { it >= 0 }.count()

    // -- What the oracle says ---------------------------------------------------------------

    /** The definition the caret is on or at a call of: a declaration is its own; a call is whatever the compiler bound. */
    private fun binding(): Binding? =
        when (val place = place) {
            is Place.Head -> Binding(scenario.main.module, place.name, place.arity, "declaration")
            is Place.Marked -> scenario.sites.single { it.id == place.id }.binding
        }

    /** The world's first definition, which a variable, atom or keyword site shares its name with. */
    private fun primary(): Binding =
        scenario.main.definitions.first().let { Binding(scenario.main.module, it.name, it.maxArity, "declaration") }

    /** The marked site the caret is at, or null at a declaration. */
    private fun siteOrNull(): Site? = (place as? Place.Marked)?.let { marked -> scenario.sites.single { it.id == marked.id } }

    /**
     * Whether the caret is at a call the compiler rejected for its arity, as opposed to a place that is not a call
     * at all or one naming a function that does not exist. The oracle only carries a diagnostic where the compiler
     * complained, so this is the compiler's own answer rather than the harness guessing from the shape; the
     * candidates are what makes it an *arity* question, since a name nothing declares has none and there is
     * nothing to show a developer instead.
     */
    private fun atWrongArity(binding: Binding?): Boolean =
        binding == null && siteOrNull()?.let { it.diagnostic != null && candidates(it).isNotEmpty() } == true

    /**
     * Every definition of the name a call writes, at any arity - what the developer is choosing between when they
     * could not remember which one they wanted. Ascending arity, because that is the order they are offered in.
     */
    private fun candidates(site: Site): List<Binding> =
        scenario.main.definitions
            .filter { nfc(it.name) == nfc(site.name) && site.sees(it) }
            .sortedBy { it.maxArity }
            .map { Binding(scenario.main.module, it.name, it.maxArity, "candidate") }

    private fun definition(binding: Binding): Pair<DeclaringModule, Definition> {
        val module = scenario.module(binding.module)
        return module to module.definitions.first { it.covers(binding) }
    }

    private fun heads(binding: Binding): List<Head> {
        val (module, definition) = definition(binding)
        return Expected.heads(module, definition.name, binding.arity)
    }

    /**
     * A declaration presents its own clause; a call presents the definition's first.
     *
     * A clause the oracle names and the heads do not have is the fixtures and the expectations disagreeing, so it is
     * raised rather than quietly answered with clause 0 - which would compare the cell against the wrong head and
     * pass.
     */
    private fun presentedHead(binding: Binding): Head {
        val heads = heads(binding)
        val place = place

        return if (place is Place.Head) {
            heads.getOrNull(place.clause)
                ?: throw AssertionError("${place.id} asks for clause ${place.clause} of ${binding.name}/${binding.arity}, which has ${heads.size} head(s)")
        } else {
            heads.first()
        }
    }

    /** The sites the compiler bound to the definition [binding] is in: the mirror of a body-less backing has no local call. */
    private fun boundSites(binding: Binding): List<String> {
        val (module, definition) = definition(binding)

        return scenario.sites
            .filter { site -> site.binding?.let { it.module == module.module && definition.covers(it) } == true }
            .filter { (it.id != LOCAL && !privateUse(it.id)) || Crossing.hasLocalCall(scenario) }
            // A compiled module is searched through its mirror, where only `local`'s call can be told apart.
            .filter { !privateUse(it.id) || !module.compiled }
            .map { it.id }
            .sorted()
    }

    /**
     * Where Go To Declaration from a call of [binding] lands: a delegate's target where its target resolves and the
     * delegate's `.beam`, if any, still records it, and otherwise the definition's own heads.
     */
    private fun goToDeclarationLines(binding: Binding): List<String> {
        val (module, definition) = definition(binding)
        val target = scenario.modules.firstOrNull { it.module == module.delegateTo }

        return if (target != null && !(module.compiled && backing in setOf(Backing.EX_GEN, Backing.ERL_GEN))) {
            // A delegate fills in its own defaults and calls the target with every argument, so a call at any arity
            // the delegate covers lands on the target's one arity. Asking the target for the call's own arity found
            // no definition, and the cell reported the harness's exception rather than anything the plugin did.
            headLines(Binding(target.module, module.delegateAs.orEmpty() + definition.name, definition.maxArity, "delegated"))
        } else {
            headLines(binding)
        }
    }

    /**
     * Where each clause head of the definition [binding] is in, as `file:line `text``. A mirror gives each arity a
     * default argument creates its own head, so there it is the heads covering the arity called.
     */
    private fun headLines(binding: Binding): List<String> {
        val (module, definition) = definition(binding)

        return if (module.compiled) {
            mirrorHeads(mirror(module), definition.name, binding.arity).map { describeLine(it) }
        } else {
            module.declarations
                .filter { it.name == definition.name && it.arity == definition.maxArity }
                .map { describeLine(sourceFiles.getValue(module), it.line) }
        }.sorted()
    }

    // -- Carets -----------------------------------------------------------------------------

    /** Every feature asks at the same place, so the file is opened once per group. */
    private fun openAt(place: Place) {
        if (opened) return
        opened = true
        // `createAndSetEditor` makes a new editor per open and closes none, so a fixture reused across places
        // accumulates one for every open it has ever done.
        FileEditorManager.getInstance(project).let { manager -> manager.openFiles.forEach(manager::closeFile) }

        val offset = when {
            place is Place.Head && scenario.main.compiled -> {
                myFixture.configureFromExistingVirtualFile(beamFile(scenario.main))
                val head = mirrorHeads(mirror(scenario.main), place.name, place.arity).getOrNull(place.clause)
                    ?: throw AssertionError("The decompiled ${scenario.main.module} has no clause ${place.clause} for ${place.name}/${place.arity}")
                CallDefinitionClause.nameIdentifier(head)!!.textOffset
            }

            place is Place.Head -> {
                val file = sourceFiles.getValue(scenario.main)
                myFixture.configureFromExistingVirtualFile(file)
                val declaration = scenario.main.declarations.filter { it.name == place.name && it.arity == place.arity }[place.clause]
                offsetOf(file, declaration.line, declaration.column)
            }

            place.id == LOCAL && scenario.main.compiled -> {
                myFixture.configureFromExistingVirtualFile(beamFile(scenario.main))
                mirrorLocalCall(mirror(scenario.main)).textOffset
            }

            else -> {
                val site = scenario.sites.single { it.id == place.id }
                val file = fileOf(site)
                myFixture.configureFromExistingVirtualFile(file)
                offsetOf(file, site.line, site.column)
            }
        }

        myFixture.editor.caretModel.moveToOffset(offset + 1)
    }

    /** Which site a usage is, or where it is when no site is there. */
    private fun usageSite(file: PsiFile, offset: Int): String {
        val virtualFile = fileOf(file)
        val source = sourceFiles.entries.firstOrNull { it.value == virtualFile }?.key
        val site = when {
            virtualFile in callerFiles.values ->
                scenario.sites.firstOrNull { callerFiles[it.file] == virtualFile && offsetOf(virtualFile!!, it.line, it.column) == offset }?.id
            source != null ->
                scenario.sites.firstOrNull { it.file == source.source && offsetOf(virtualFile!!, it.line, it.column) == offset }?.id
            virtualFile == beamFileOrNull(scenario.main) ->
                LOCAL.takeIf { runCatching { mirrorLocalCall(mirror(scenario.main)).textOffset }.getOrNull() == offset }
            else -> null
        }

        return site ?: "unexpected usage at ${describeLine(file, offset)}"
    }

    // -- The decompiled mirror --------------------------------------------------------------

    private fun beamFileOrNull(module: DeclaringModule): VirtualFile? =
        module.beam?.let { LocalFileSystem.getInstance().refreshAndFindFileByIoFile(Fixtures.file(it).absoluteFile) }

    private fun beamFile(module: DeclaringModule): VirtualFile =
        beamFileOrNull(module) ?: throw AssertionError("${module.beam} is not in the VFS")

    private fun mirror(module: DeclaringModule): PsiFile {
        val file = PsiManager.getInstance(project).findFile(beamFile(module))!!
        return (file as? PsiCompiledFile)?.decompiledPsiFile ?: file
    }

    private fun mirrorHeads(mirror: PsiFile, name: String, arity: Int): List<Call> =
        PsiTreeUtil.findChildrenOfType(mirror, Call::class.java).filter { call ->
            CallDefinitionClause.`is`(call) &&
                CallDefinitionClause.nameArityInterval(call, ResolveState.initial())?.let { nameArityInterval ->
                    val interval = nameArityInterval.arityInterval
                    nfc(nameArityInterval.name) == nfc(name) && interval.minimum <= arity && (interval.maximum ?: arity) >= arity
                } == true
        }

    /** The name of the call in `local_site`'s body. */
    private fun mirrorLocalCall(mirror: PsiFile): PsiElement {
        val localSite = mirrorHeads(mirror, "local_site", 2).singleOrNull()
            ?: throw AssertionError("The decompiled ${scenario.main.module} has no single local_site/2")
        val name = scenario.sites.single { it.id == LOCAL }.binding!!.name
        val call = PsiTreeUtil.findChildrenOfType(localSite, Call::class.java)
            .firstOrNull { it.functionName()?.let(::nfc) == nfc(name) && !CallDefinitionClause.`is`(it) }
            ?: throw AssertionError("The decompiled local_site/2 of ${scenario.main.module} does not call $name: ${localSite.text}")

        return call.functionNameElement() ?: call
    }

    // -- Positions --------------------------------------------------------------------------

    private fun offsetOf(file: VirtualFile, line: Int, column: Int): Int {
        val text = String(file.contentsToByteArray(), file.charset)
        return text.split('\n').take(line - 1).sumOf { it.length + 1 } + column - 1
    }

    private fun fileOf(file: PsiFile): VirtualFile? = file.virtualFile ?: file.originalFile.virtualFile

    private fun describeLine(element: PsiElement): String = describeLine(element.containingFile, element.textOffset)

    private fun describeLine(file: PsiFile, offset: Int): String {
        val text = file.text
        val start = text.lastIndexOf('\n', offset - 1) + 1
        val end = text.indexOf('\n', offset).let { if (it < 0) text.length else it }
        return "${fileOf(file)?.name}:${text.substring(0, start).count { it == '\n' } + 1} `${nfc(text.substring(start, end).trim())}`"
    }

    private fun describeLine(file: VirtualFile, line: Int): String =
        "${file.name}:$line `${nfc(String(file.contentsToByteArray(), file.charset).split('\n')[line - 1].trim())}`"

    companion object {
        private val IDENTIFIER = Regex("[\\p{L}\\p{N}_\\p{Mn}\\p{Mc}]+[?!]?")

        /** The `@1a2b3c` a default `toString()` ends with. */
        private val IDENTITY_HASH = Regex("@[0-9a-f]+$")
        private val DELEGATE_TO = Regex("\\bto: [A-Z][\\w.]*")

        /** The form whose declarations are `Mix.Generator` embeds, and the suffixes an embed adds to its atom. */
        private const val GENERATOR_EMBED = "generator_embed"
        private val EMBED_SUFFIXES = listOf("_template", "_text")

        /**
         * A guard's own keys, looked up by name: a plugin without them still compiles this suite, and its guard cells
         * then say what it is missing rather than failing to build.
         */
        private val GUARD_CALL: TextAttributesKey = TextAttributesKey.find("ELIXIR_GUARD_CALL")
        private val GUARD_DECLARATION: TextAttributesKey = TextAttributesKey.find("ELIXIR_GUARD_DECLARATION")
        private val GUARD_FORMS = setOf("defguard", "defguardp")

        /** The keys [highlightKeysAt] can tell apart. */
        private val HIGHLIGHT_KEYS = listOf(
            ElixirSyntaxHighlighter.FUNCTION_CALL,
            ElixirSyntaxHighlighter.MACRO_CALL,
            ElixirSyntaxHighlighter.FUNCTION_DECLARATION,
            ElixirSyntaxHighlighter.MACRO_DECLARATION,
            ElixirSyntaxHighlighter.PREDEFINED_CALL,
            GUARD_CALL,
            GUARD_DECLARATION,
        )

        /** Where [Group.timed] appends one row per phase: the file `MATRIX_TIMING` names, or nowhere when unset. */
        private val TIMING: File? = System.getenv("MATRIX_TIMING")?.takeIf(String::isNotBlank)?.let(::File)

        /** The cells whose names `MATRIX_ONLY` matches, a regex, when it is set: to ask a handful without the rest. */
        private val ONLY: Regex? = System.getenv("MATRIX_ONLY")?.takeIf(String::isNotBlank)?.let(::Regex)

        /** Whether to print every highlight on the caret's line where a cell reads them, to see what it is judged on. */
        private val DUMP_HIGHLIGHTS: Boolean = !System.getenv("MATRIX_DUMP_HIGHLIGHTS").isNullOrBlank()
        /**
         * The scenario being asked, and the only one holding a fixture: scenarios define the same files, and a closed
         * scenario's group is dropped rather than kept for the rest of the run.
         */
        private var open: Group? = null

        /** Every applicable feature at every place, in the order [check] asks them. */
        fun cellsOf(scenario: Scenario): List<Pair<Place, Feature>> = Crossing.places(scenario).flatMap { place ->
            Feature.entries
                .filter { Crossing.applicability(scenario, it, place) is Applicability.Applicable }
                .filter { feature -> ONLY?.containsMatchIn(Cell(scenario, feature, place).testName) ?: true }
                .map { place to it }
        }

        fun check(scenario: Scenario, place: Place, feature: Feature) {
            val group = open?.takeIf { it.scenario === scenario } ?: Group(scenario).also {
                closeOpen()
                open = it
            }
            group.check(place, feature)
        }

        fun closeOpen() {
            val group = open ?: return
            open = null
            EdtTestUtil.runInEdtAndWait<Throwable> { group.close() }
        }
    }
}
