# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateUnresolvable.XAritySeparateBroken do
  alias Src.DefdelegateUnresolvable.XAritySeparate
  alias Src.DefdelegateUnresolvable.XAritySeparate, as: Aliased
  import Src.DefdelegateUnresolvable.XAritySeparate

  def at_arity_3(a, b), do: Src.DefdelegateUnresolvable.XAritySeparate.src_defdelegate_unresolvable_x_arity_separate_snoc(a, b, a) # @arity_3
end
