# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateUnresolvable.XArityZeroUndefined do
  alias Src.DefdelegateUnresolvable.XArityZero
  alias Src.DefdelegateUnresolvable.XArityZero, as: Aliased
  import Src.DefdelegateUnresolvable.XArityZero

  def at_unqualified_arity_1(a, _b), do: src_defdelegate_unresolvable_x_arity_zero_snoc(a) # @unqualified_arity_1
end
