# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateUnresolvable.XDefaults.ImportTransitive.Middle do
  import Src.DefdelegateUnresolvable.XDefaults
  def middle_marker, do: :ok
end

defmodule Callers.Src.DefdelegateUnresolvable.XDefaults.ImportTransitive do
  import Callers.Src.DefdelegateUnresolvable.XDefaults.ImportTransitive.Middle

  def at_import_transitive(a, b), do: src_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_transitive
end

