# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateUnresolvable.XLookalikeAbsentBroken do
  alias Src.DefdelegateUnresolvable.XLookalikeAbsent
  alias Src.DefdelegateUnresolvable.XLookalikeAbsent, as: Aliased
  import Src.DefdelegateUnresolvable.XLookalikeAbsent

  def at_arity_1(a, _b), do: Src.DefdelegateUnresolvable.XLookalikeAbsent.src_defdelegate_unresolvable_x_lookalike_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: Src.DefdelegateUnresolvable.XLookalikeAbsent.src_defdelegate_unresolvable_x_lookalike_absent_snoc(a, b, a) # @arity_3
  def at_undeclared(a, b), do: Src.DefdelegateUnresolvable.XLookalikeAbsent.src_defdelegate_unresolvable_x_lookalike_absent_undeclared(a, b) # @undeclared
end
