# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.W3 do
  alias ExDocs.Defmacro.W3
  alias ExDocs.Defmacro.W3, as: Aliased
  require ExDocs.Defmacro.W3
  import ExDocs.Defmacro.W3

  def at_qualified(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W3.ex_docs_defmacro_w3_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defmacro_w3_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defmacro_w3_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defmacro_w3_snoc(b) # @pipe
  def at_lookalike_xsnoc(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_xsnoc(a, b) # @lookalike_xsnoc
  def at_lookalike_snoc_x(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_snoc_x(a, b) # @lookalike_snoc_x
  def at_lookalike_snoc_question(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_snoc?(a, b) # @lookalike_snoc_question
  def at_lookalike_snoc_bang(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_snoc!(a, b) # @lookalike_snoc_bang
  def at_lookalike_snoc_combining(a, b), do: ExDocs.Defmacro.W3.ex_docs_defmacro_w3_snoć(a, b) # @lookalike_snoc_combining
end
