# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XAritySeparateBroken do
  alias ExDocs.Defmacro.XAritySeparate
  alias ExDocs.Defmacro.XAritySeparate, as: Aliased
  require ExDocs.Defmacro.XAritySeparate
  import ExDocs.Defmacro.XAritySeparate

  def at_arity_3(a, b), do: ExDocs.Defmacro.XAritySeparate.ex_docs_defmacro_x_arity_separate_snoc(a, b, a) # @arity_3
end
