# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XArityZeroUndefined do
  alias ExDocs.Defmacro.XArityZero
  alias ExDocs.Defmacro.XArityZero, as: Aliased
  require ExDocs.Defmacro.XArityZero
  import ExDocs.Defmacro.XArityZero

  def at_unqualified_arity_1(a, _b), do: ex_docs_defmacro_x_arity_zero_snoc(a) # @unqualified_arity_1
end
