# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XDefaultsHead.RequireOnly do
  require ExDocs.Defmacro.XDefaultsHead

  def at_require_only(a, b), do: ex_docs_defmacro_x_defaults_head_snoc(a, b) # @require_only
end
