# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XDefaultsHeadUndefined do
  alias ExDocs.Defmacro.XDefaultsHead
  alias ExDocs.Defmacro.XDefaultsHead, as: Aliased
  require ExDocs.Defmacro.XDefaultsHead
  import ExDocs.Defmacro.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: ex_docs_defmacro_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
