# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XLookalikeAbsentBroken do
  alias ExDocs.Defmacro.XLookalikeAbsent
  alias ExDocs.Defmacro.XLookalikeAbsent, as: Aliased
  require ExDocs.Defmacro.XLookalikeAbsent
  import ExDocs.Defmacro.XLookalikeAbsent

  def at_arity_1(a, _b), do: ExDocs.Defmacro.XLookalikeAbsent.ex_docs_defmacro_x_lookalike_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: ExDocs.Defmacro.XLookalikeAbsent.ex_docs_defmacro_x_lookalike_absent_snoc(a, b, a) # @arity_3
  def at_undeclared(a, b), do: ExDocs.Defmacro.XLookalikeAbsent.ex_docs_defmacro_x_lookalike_absent_undeclared(a, b) # @undeclared
end
