# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XNfc do
  alias ExDocs.Defmacro.XNfc
  alias ExDocs.Defmacro.XNfc, as: Aliased
  require ExDocs.Defmacro.XNfc
  import ExDocs.Defmacro.XNfc

  def at_qualified(a, b), do: ExDocs.Defmacro.XNfc.ex_docs_defmacro_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_docs_defmacro_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defmacro_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defmacro_x_nfc_snoć(a, b) # @unqualified
end
