# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defmacro.XNfcBroken do
  alias ExDocs.Defmacro.XNfc
  alias ExDocs.Defmacro.XNfc, as: Aliased
  require ExDocs.Defmacro.XNfc
  import ExDocs.Defmacro.XNfc

  def at_arity_1(a, _b), do: ExDocs.Defmacro.XNfc.ex_docs_defmacro_x_nfc_snoć(a) # @arity_1
end
