# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.W2.ImportTransitive.Middle do
  import ExGen.Defmacro.W2
  def middle_marker, do: :ok
end

defmodule Callers.ExGen.Defmacro.W2.ImportTransitive do
  import Callers.ExGen.Defmacro.W2.ImportTransitive.Middle

  def at_import_transitive(a, b), do: ex_gen_defmacro_w2_snoc(a, b) # @import_transitive
end

