# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XArityAbsentUndefined do
  alias ExGen.Defmacro.XArityAbsent
  alias ExGen.Defmacro.XArityAbsent, as: Aliased
  require ExGen.Defmacro.XArityAbsent
  import ExGen.Defmacro.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_defmacro_x_arity_absent_snoc(a) # @unqualified_arity_1
end
