# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XArityZero do
  alias ExGen.Defmacro.XArityZero
  alias ExGen.Defmacro.XArityZero, as: Aliased
  require ExGen.Defmacro.XArityZero
  import ExGen.Defmacro.XArityZero

  def at_qualified(a, b), do: ExGen.Defmacro.XArityZero.ex_gen_defmacro_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.ex_gen_defmacro_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_defmacro_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_defmacro_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_defmacro_x_arity_zero_snoc(b) # @pipe
  def at_no_arguments(_a, _b), do: ExGen.Defmacro.XArityZero.ex_gen_defmacro_x_arity_zero_snoc # @no_arguments
end
