# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XArityZeroUndefined do
  alias ExGen.Defmacro.XArityZero
  alias ExGen.Defmacro.XArityZero, as: Aliased
  require ExGen.Defmacro.XArityZero
  import ExGen.Defmacro.XArityZero

  def at_unqualified_arity_1(a, _b), do: ex_gen_defmacro_x_arity_zero_snoc(a) # @unqualified_arity_1
end
