# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XArityAbsent do
  alias ExGen.Defmacro.XArityAbsent
  alias ExGen.Defmacro.XArityAbsent, as: Aliased
  require ExGen.Defmacro.XArityAbsent
  import ExGen.Defmacro.XArityAbsent

  def at_qualified(a, b), do: ExGen.Defmacro.XArityAbsent.ex_gen_defmacro_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.ex_gen_defmacro_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_defmacro_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_defmacro_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_defmacro_x_arity_absent_snoc(b) # @pipe
end
