# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XAritySeparate.ImportFunctions do
  import ExGen.Defmacro.XAritySeparate, only: :functions

  def at_import_functions(a, b), do: ex_gen_defmacro_x_arity_separate_snoc(a, b) # @import_functions
end
