# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XAritySeparateBroken do
  alias ExGen.Defmacro.XAritySeparate
  alias ExGen.Defmacro.XAritySeparate, as: Aliased
  require ExGen.Defmacro.XAritySeparate
  import ExGen.Defmacro.XAritySeparate

  def at_arity_3(a, b), do: ExGen.Defmacro.XAritySeparate.ex_gen_defmacro_x_arity_separate_snoc(a, b, a) # @arity_3
end
