# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XDefaults.ImportOnly do
  import ExGen.Defmacro.XDefaults, only: [ex_gen_defmacro_x_defaults_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_gen_defmacro_x_defaults_snoc(a) # @import_only_1
end

defmodule Callers.ExGen.Defmacro.XDefaults.ImportExcept do
  import ExGen.Defmacro.XDefaults, except: [ex_gen_defmacro_x_defaults_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_gen_defmacro_x_defaults_snoc(a, b) # @import_except_2
end
