# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XDefaultsHead do
  alias ExGen.Defmacro.XDefaultsHead
  alias ExGen.Defmacro.XDefaultsHead, as: Aliased
  require ExGen.Defmacro.XDefaultsHead
  import ExGen.Defmacro.XDefaultsHead

  def at_qualified(a, b), do: ExGen.Defmacro.XDefaultsHead.ex_gen_defmacro_x_defaults_head_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XDefaultsHead.ex_gen_defmacro_x_defaults_head_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_defmacro_x_defaults_head_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_defmacro_x_defaults_head_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_defmacro_x_defaults_head_snoc(b) # @pipe
  def at_no_arguments(_a, _b), do: ExGen.Defmacro.XDefaultsHead.ex_gen_defmacro_x_defaults_head_snoc # @no_arguments
  def at_arity_1(a, _b), do: ExGen.Defmacro.XDefaultsHead.ex_gen_defmacro_x_defaults_head_snoc(a) # @arity_1
end
