# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defmacro.XNfcBroken do
  alias ExGen.Defmacro.XNfc
  alias ExGen.Defmacro.XNfc, as: Aliased
  require ExGen.Defmacro.XNfc
  import ExGen.Defmacro.XNfc

  def at_arity_1(a, _b), do: ExGen.Defmacro.XNfc.ex_gen_defmacro_x_nfc_snoć(a) # @arity_1
end
