# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.W1 do
  alias Src.Defmacro.W1
  alias Src.Defmacro.W1, as: Aliased
  require Src.Defmacro.W1
  import Src.Defmacro.W1

  def at_qualified(a, b), do: Src.Defmacro.W1.src_defmacro_w1_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W1.src_defmacro_w1_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_w1_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_w1_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_w1_snoc(b) # @pipe
end
