# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XArityZeroBroken do
  alias Src.Defmacro.XArityZero
  alias Src.Defmacro.XArityZero, as: Aliased
  require Src.Defmacro.XArityZero
  import Src.Defmacro.XArityZero

  def at_arity_1(a, _b), do: Src.Defmacro.XArityZero.src_defmacro_x_arity_zero_snoc(a) # @arity_1
end
