# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XAritySeparate.ImportOnly do
  import Src.Defmacro.XAritySeparate, only: [src_defmacro_x_arity_separate_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: src_defmacro_x_arity_separate_snoc(a) # @import_only_1
end

defmodule Callers.Src.Defmacro.XAritySeparate.ImportExcept do
  import Src.Defmacro.XAritySeparate, except: [src_defmacro_x_arity_separate_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: src_defmacro_x_arity_separate_snoc(a, b) # @import_except_2
end
