# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XAritySeparate.ImportTransitive.Middle do
  import Src.Defmacro.XAritySeparate
  def middle_marker, do: :ok
end

defmodule Callers.Src.Defmacro.XAritySeparate.ImportTransitive do
  import Callers.Src.Defmacro.XAritySeparate.ImportTransitive.Middle

  def at_import_transitive(a, b), do: src_defmacro_x_arity_separate_snoc(a, b) # @import_transitive
end

