# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XArityZero do
  alias Src.Defmacro.XArityZero
  alias Src.Defmacro.XArityZero, as: Aliased
  require Src.Defmacro.XArityZero
  import Src.Defmacro.XArityZero

  def at_qualified(a, b), do: Src.Defmacro.XArityZero.src_defmacro_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.src_defmacro_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_arity_zero_snoc(b) # @pipe
  def at_no_arguments(_a, _b), do: Src.Defmacro.XArityZero.src_defmacro_x_arity_zero_snoc # @no_arguments
end
