# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XAritySeparate.RequireOnly do
  require Src.Defmacro.XAritySeparate

  def at_require_only(a, b), do: src_defmacro_x_arity_separate_snoc(a, b) # @require_only
end
