# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XArityAbsentBroken do
  alias Src.Defmacro.XArityAbsent
  alias Src.Defmacro.XArityAbsent, as: Aliased
  require Src.Defmacro.XArityAbsent
  import Src.Defmacro.XArityAbsent

  def at_no_arguments(_a, _b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_snoc # @no_arguments
  def at_arity_1(a, _b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_snoc(a, b, a) # @arity_3
  def at_aliased_arity_1(a, _b), do: XArityAbsent.src_defmacro_x_arity_absent_snoc(a) # @aliased_arity_1
  def at_undeclared(a, b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_undeclared(a, b) # @undeclared
  def at_lookalike_prefix(a, b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_sno(a, b) # @lookalike_prefix
  def at_undeclared_no_arguments(_a, _b), do: Src.Defmacro.XArityAbsent.src_defmacro_x_arity_absent_undeclared # @undeclared_no_arguments
  def at_kernel_name(a, _b), do: Src.Defmacro.XArityAbsent.is_nil(a) # @kernel_name
end
