# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XAritySeparate do
  alias Src.Defmacro.XAritySeparate
  alias Src.Defmacro.XAritySeparate, as: Aliased
  require Src.Defmacro.XAritySeparate
  import Src.Defmacro.XAritySeparate

  def at_qualified(a, b), do: Src.Defmacro.XAritySeparate.src_defmacro_x_arity_separate_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XAritySeparate.src_defmacro_x_arity_separate_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_arity_separate_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_arity_separate_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_arity_separate_snoc(b) # @pipe
  def at_no_arguments(_a, _b), do: Src.Defmacro.XAritySeparate.src_defmacro_x_arity_separate_snoc # @no_arguments
  def at_arity_1(a, _b), do: Src.Defmacro.XAritySeparate.src_defmacro_x_arity_separate_snoc(a) # @arity_1
end
