# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XCond do
  alias Src.Defmacro.XCond
  alias Src.Defmacro.XCond, as: Aliased
  require Src.Defmacro.XCond
  import Src.Defmacro.XCond

  def at_qualified(a, b), do: Src.Defmacro.XCond.src_defmacro_x_cond_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XCond.src_defmacro_x_cond_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_cond_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_cond_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_cond_snoc(b) # @pipe
end
