# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XDefaultsHead.ImportExcept1 do
  import Src.Defmacro.XDefaultsHead, except: [src_defmacro_x_defaults_head_snoc: 1] # @import_except_1_key

  def at_import_except_1(a, _b), do: src_defmacro_x_defaults_head_snoc(a) # @import_except_1
end
