# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XDefaults do
  alias Src.Defmacro.XDefaults
  alias Src.Defmacro.XDefaults, as: Aliased
  require Src.Defmacro.XDefaults
  import Src.Defmacro.XDefaults

  def at_qualified(a, b), do: Src.Defmacro.XDefaults.src_defmacro_x_defaults_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XDefaults.src_defmacro_x_defaults_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_defaults_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_defaults_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_defaults_snoc(b) # @pipe
  def at_default_arity(a, _b), do: Src.Defmacro.XDefaults.src_defmacro_x_defaults_snoc(a) # @default_arity
end
