# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XDefaultsHeadBroken do
  alias Src.Defmacro.XDefaultsHead
  alias Src.Defmacro.XDefaultsHead, as: Aliased
  require Src.Defmacro.XDefaultsHead
  import Src.Defmacro.XDefaultsHead

  def at_arity_3(a, b), do: Src.Defmacro.XDefaultsHead.src_defmacro_x_defaults_head_snoc(a, b, a) # @arity_3
end
