# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XLookalikeAbsentUndefined do
  alias Src.Defmacro.XLookalikeAbsent
  alias Src.Defmacro.XLookalikeAbsent, as: Aliased
  require Src.Defmacro.XLookalikeAbsent
  import Src.Defmacro.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: src_defmacro_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
