# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XNfc do
  alias Src.Defmacro.XNfc
  alias Src.Defmacro.XNfc, as: Aliased
  require Src.Defmacro.XNfc
  import Src.Defmacro.XNfc

  def at_qualified(a, b), do: Src.Defmacro.XNfc.src_defmacro_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.src_defmacro_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_nfc_snoć(a, b) # @unqualified
end
