# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XNfcBroken do
  alias Src.Defmacro.XNfc
  alias Src.Defmacro.XNfc, as: Aliased
  require Src.Defmacro.XNfc
  import Src.Defmacro.XNfc

  def at_arity_1(a, _b), do: Src.Defmacro.XNfc.src_defmacro_x_nfc_snoć(a) # @arity_1
end
