# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacro.XTry do
  alias Src.Defmacro.XTry
  alias Src.Defmacro.XTry, as: Aliased
  require Src.Defmacro.XTry
  import Src.Defmacro.XTry

  def at_qualified(a, b), do: Src.Defmacro.XTry.src_defmacro_x_try_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XTry.src_defmacro_x_try_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defmacro_x_try_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defmacro_x_try_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defmacro_x_try_snoc(b) # @pipe
end
