# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFrom.XArityZeroBroken do
  alias ExDbgi.EexFunctionFrom.XArityZero
  alias ExDbgi.EexFunctionFrom.XArityZero, as: Aliased
  import ExDbgi.EexFunctionFrom.XArityZero

  def at_arity_1(a, _b), do: ExDbgi.EexFunctionFrom.XArityZero.ex_dbgi_eex_function_from_x_arity_zero_snoc(a) # @arity_1
end
