# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.EexFunctionFrom.XArityZero do
  alias ExDbgi.EexFunctionFrom.XArityZero
  alias ExDbgi.EexFunctionFrom.XArityZero, as: Aliased
  import ExDbgi.EexFunctionFrom.XArityZero

  def at_qualified(a, b), do: ExDbgi.EexFunctionFrom.XArityZero.ex_dbgi_eex_function_from_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.ex_dbgi_eex_function_from_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_eex_function_from_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_eex_function_from_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_eex_function_from_x_arity_zero_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.EexFunctionFrom.XArityZero.ex_dbgi_eex_function_from_x_arity_zero_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDbgi.EexFunctionFrom.XArityZero, :ex_dbgi_eex_function_from_x_arity_zero_snoc, [a, b]) # @apply
  def at_no_arguments(_a, _b), do: ExDbgi.EexFunctionFrom.XArityZero.ex_dbgi_eex_function_from_x_arity_zero_snoc # @no_arguments
end
