# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.W3 do
  alias Src.Defguard.W3
  alias Src.Defguard.W3, as: Aliased
  require Src.Defguard.W3
  import Src.Defguard.W3

  def at_qualified(a, b), do: Src.Defguard.W3.src_defguard_w3_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W3.src_defguard_w3_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_w3_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_w3_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_w3_snoc(b) # @pipe
  def at_lookalike_xsnoc(a, b), do: Src.Defguard.W3.src_defguard_w3_xsnoc(a, b) # @lookalike_xsnoc
  def at_lookalike_snoc_x(a, b), do: Src.Defguard.W3.src_defguard_w3_snoc_x(a, b) # @lookalike_snoc_x
  def at_lookalike_snoc_question(a, b), do: Src.Defguard.W3.src_defguard_w3_snoc?(a, b) # @lookalike_snoc_question
  def at_lookalike_snoc_bang(a, b), do: Src.Defguard.W3.src_defguard_w3_snoc!(a, b) # @lookalike_snoc_bang
  def at_lookalike_snoc_combining(a, b), do: Src.Defguard.W3.src_defguard_w3_snoć(a, b) # @lookalike_snoc_combining
end
