# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XArityAbsent do
  alias Src.Defguard.XArityAbsent
  alias Src.Defguard.XArityAbsent, as: Aliased
  require Src.Defguard.XArityAbsent
  import Src.Defguard.XArityAbsent

  def at_qualified(a, b), do: Src.Defguard.XArityAbsent.src_defguard_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.src_defguard_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_arity_absent_snoc(b) # @pipe
end
