# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XCase do
  alias Src.Defguard.XCase
  alias Src.Defguard.XCase, as: Aliased
  require Src.Defguard.XCase
  import Src.Defguard.XCase

  def at_qualified(a, b), do: Src.Defguard.XCase.src_defguard_x_case_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XCase.src_defguard_x_case_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_case_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_case_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_case_snoc(b) # @pipe
end
