# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XConditional do
  alias Src.Defguard.XConditional
  alias Src.Defguard.XConditional, as: Aliased
  require Src.Defguard.XConditional
  import Src.Defguard.XConditional

  def at_qualified(a, b), do: Src.Defguard.XConditional.src_defguard_x_conditional_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XConditional.src_defguard_x_conditional_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_conditional_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_conditional_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_conditional_snoc(b) # @pipe
end
