# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XFor do
  alias Src.Defguard.XFor
  alias Src.Defguard.XFor, as: Aliased
  require Src.Defguard.XFor
  import Src.Defguard.XFor

  def at_qualified(a, b), do: Src.Defguard.XFor.src_defguard_x_for_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XFor.src_defguard_x_for_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_for_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_for_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_for_snoc(b) # @pipe
end
