# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XLookalikeAbsentBroken do
  alias Src.Defguard.XLookalikeAbsent
  alias Src.Defguard.XLookalikeAbsent, as: Aliased
  require Src.Defguard.XLookalikeAbsent
  import Src.Defguard.XLookalikeAbsent

  def at_arity_1(a, _b), do: Src.Defguard.XLookalikeAbsent.src_defguard_x_lookalike_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: Src.Defguard.XLookalikeAbsent.src_defguard_x_lookalike_absent_snoc(a, b, a) # @arity_3
  def at_undeclared(a, b), do: Src.Defguard.XLookalikeAbsent.src_defguard_x_lookalike_absent_undeclared(a, b) # @undeclared
end
