# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XNfc do
  alias Src.Defguard.XNfc
  alias Src.Defguard.XNfc, as: Aliased
  require Src.Defguard.XNfc
  import Src.Defguard.XNfc

  def at_qualified(a, b), do: Src.Defguard.XNfc.src_defguard_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.src_defguard_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_nfc_snoć(a, b) # @unqualified
end
