# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguard.XNotACall do
  alias Src.Defguard.XNotACall
  alias Src.Defguard.XNotACall, as: Aliased
  require Src.Defguard.XNotACall
  import Src.Defguard.XNotACall

  def at_qualified(a, b), do: Src.Defguard.XNotACall.src_defguard_x_not_a_call_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XNotACall.src_defguard_x_not_a_call_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defguard_x_not_a_call_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defguard_x_not_a_call_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defguard_x_not_a_call_snoc(b) # @pipe
  def at_variable(a, b), do: (fn src_defguard_x_not_a_call_snoc -> src_defguard_x_not_a_call_snoc end).({a, b}) # @variable
  def at_atom(a, b), do: {:src_defguard_x_not_a_call_snoc, a, b} # @atom
  def at_keyword(a, b), do: [src_defguard_x_not_a_call_snoc: a, b: b] # @keyword
end
