# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.W1 do
  alias ExDocs.DefdelegateUnresolvable.W1
  alias ExDocs.DefdelegateUnresolvable.W1, as: Aliased
  import ExDocs.DefdelegateUnresolvable.W1

  def at_qualified(a, b), do: ExDocs.DefdelegateUnresolvable.W1.ex_docs_defdelegate_unresolvable_w1_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W1.ex_docs_defdelegate_unresolvable_w1_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defdelegate_unresolvable_w1_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defdelegate_unresolvable_w1_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defdelegate_unresolvable_w1_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.DefdelegateUnresolvable.W1.ex_docs_defdelegate_unresolvable_w1_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDocs.DefdelegateUnresolvable.W1, :ex_docs_defdelegate_unresolvable_w1_snoc, [a, b]) # @apply
end
