# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.XArityZeroUndefined do
  alias ExDocs.DefdelegateUnresolvable.XArityZero
  alias ExDocs.DefdelegateUnresolvable.XArityZero, as: Aliased
  import ExDocs.DefdelegateUnresolvable.XArityZero

  def at_unqualified_arity_1(a, _b), do: ex_docs_defdelegate_unresolvable_x_arity_zero_snoc(a) # @unqualified_arity_1
end
