# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateUnresolvable.XNfc do
  alias ExDocs.DefdelegateUnresolvable.XNfc
  alias ExDocs.DefdelegateUnresolvable.XNfc, as: Aliased
  import ExDocs.DefdelegateUnresolvable.XNfc

  def at_qualified(a, b), do: ExDocs.DefdelegateUnresolvable.XNfc.ex_docs_defdelegate_unresolvable_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_docs_defdelegate_unresolvable_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defdelegate_unresolvable_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defdelegate_unresolvable_x_nfc_snoć(a, b) # @unqualified
end
