# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XArityAbsentBroken do
  alias ExDbgi.Defdelegate.XArityAbsent
  alias ExDbgi.Defdelegate.XArityAbsent, as: Aliased
  import ExDbgi.Defdelegate.XArityAbsent

  def at_no_arguments(_a, _b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc # @no_arguments
  def at_arity_1(a, _b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc(a, b, a) # @arity_3
  def at_aliased_arity_1(a, _b), do: XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_snoc(a) # @aliased_arity_1
  def at_undeclared(a, b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_undeclared(a, b) # @undeclared
  def at_undeclared_no_arguments(_a, _b), do: ExDbgi.Defdelegate.XArityAbsent.ex_dbgi_defdelegate_x_arity_absent_undeclared # @undeclared_no_arguments
end
