# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XAritySeparateBroken do
  alias ExDbgi.Defdelegate.XAritySeparate
  alias ExDbgi.Defdelegate.XAritySeparate, as: Aliased
  import ExDbgi.Defdelegate.XAritySeparate

  def at_arity_3(a, b), do: ExDbgi.Defdelegate.XAritySeparate.ex_dbgi_defdelegate_x_arity_separate_snoc(a, b, a) # @arity_3
end
