# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XArityZeroUndefined do
  alias ExDbgi.Defdelegate.XArityZero
  alias ExDbgi.Defdelegate.XArityZero, as: Aliased
  import ExDbgi.Defdelegate.XArityZero

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defdelegate_x_arity_zero_snoc(a) # @unqualified_arity_1
end
