# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XDefaultsHead.ImportTransitive.Middle do
  import ExDbgi.Defdelegate.XDefaultsHead
  def middle_marker, do: :ok
end

defmodule Callers.ExDbgi.Defdelegate.XDefaultsHead.ImportTransitive do
  import Callers.ExDbgi.Defdelegate.XDefaultsHead.ImportTransitive.Middle

  def at_import_transitive(a, b), do: ex_dbgi_defdelegate_x_defaults_head_snoc(a, b) # @import_transitive
end

