# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XNfc do
  alias ExDbgi.Defdelegate.XNfc
  alias ExDbgi.Defdelegate.XNfc, as: Aliased
  import ExDbgi.Defdelegate.XNfc

  def at_qualified(a, b), do: ExDbgi.Defdelegate.XNfc.ex_dbgi_defdelegate_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_dbgi_defdelegate_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_x_nfc_snoć(a, b) # @unqualified
end
