# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defdelegate.XNfcBroken do
  alias ExDbgi.Defdelegate.XNfc
  alias ExDbgi.Defdelegate.XNfc, as: Aliased
  import ExDbgi.Defdelegate.XNfc

  def at_arity_1(a, _b), do: ExDbgi.Defdelegate.XNfc.ex_dbgi_defdelegate_x_nfc_snoć(a) # @arity_1
end
