# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.W2.ImportFunctions do
  import ExDbgi.Defmacro.W2, only: :functions

  def at_import_functions(a, b), do: ex_dbgi_defmacro_w2_snoc(a, b) # @import_functions
end
