# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XArityAbsentUndefined do
  alias ExDbgi.Defmacro.XArityAbsent
  alias ExDbgi.Defmacro.XArityAbsent, as: Aliased
  require ExDbgi.Defmacro.XArityAbsent
  import ExDbgi.Defmacro.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defmacro_x_arity_absent_snoc(a) # @unqualified_arity_1
end
