# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XArityZeroUndefined do
  alias ExDbgi.Defmacro.XArityZero
  alias ExDbgi.Defmacro.XArityZero, as: Aliased
  require ExDbgi.Defmacro.XArityZero
  import ExDbgi.Defmacro.XArityZero

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defmacro_x_arity_zero_snoc(a) # @unqualified_arity_1
end
