# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XArityZero do
  alias ExDbgi.Defmacro.XArityZero
  alias ExDbgi.Defmacro.XArityZero, as: Aliased
  require ExDbgi.Defmacro.XArityZero
  import ExDbgi.Defmacro.XArityZero

  def at_qualified(a, b), do: ExDbgi.Defmacro.XArityZero.ex_dbgi_defmacro_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.ex_dbgi_defmacro_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defmacro_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defmacro_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defmacro_x_arity_zero_snoc(b) # @pipe
  def at_no_arguments(_a, _b), do: ExDbgi.Defmacro.XArityZero.ex_dbgi_defmacro_x_arity_zero_snoc # @no_arguments
end
