# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XAritySeparateBroken do
  alias ExDbgi.Defmacro.XAritySeparate
  alias ExDbgi.Defmacro.XAritySeparate, as: Aliased
  require ExDbgi.Defmacro.XAritySeparate
  import ExDbgi.Defmacro.XAritySeparate

  def at_arity_3(a, b), do: ExDbgi.Defmacro.XAritySeparate.ex_dbgi_defmacro_x_arity_separate_snoc(a, b, a) # @arity_3
end
