# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XDefaultsHeadUndefined do
  alias ExDbgi.Defmacro.XDefaultsHead
  alias ExDbgi.Defmacro.XDefaultsHead, as: Aliased
  require ExDbgi.Defmacro.XDefaultsHead
  import ExDbgi.Defmacro.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: ex_dbgi_defmacro_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
