# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XDefaultsHead.ImportMacros do
  import ExDbgi.Defmacro.XDefaultsHead, only: :macros

  def at_import_macros(a, b), do: ex_dbgi_defmacro_x_defaults_head_snoc(a, b) # @import_macros
end

defmodule Callers.ExDbgi.Defmacro.XDefaultsHead.ImportOnly do
  import ExDbgi.Defmacro.XDefaultsHead, only: [ex_dbgi_defmacro_x_defaults_head_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_dbgi_defmacro_x_defaults_head_snoc(a) # @import_only_1
end

defmodule Callers.ExDbgi.Defmacro.XDefaultsHead.ImportExcept do
  import ExDbgi.Defmacro.XDefaultsHead, except: [ex_dbgi_defmacro_x_defaults_head_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_dbgi_defmacro_x_defaults_head_snoc(a, b) # @import_except_2
end
