# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XLookalikeAbsentUndefined do
  alias ExDbgi.Defmacro.XLookalikeAbsent
  alias ExDbgi.Defmacro.XLookalikeAbsent, as: Aliased
  require ExDbgi.Defmacro.XLookalikeAbsent
  import ExDbgi.Defmacro.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defmacro_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
