# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defmacro.XNfcBroken do
  alias ExDbgi.Defmacro.XNfc
  alias ExDbgi.Defmacro.XNfc, as: Aliased
  require ExDbgi.Defmacro.XNfc
  import ExDbgi.Defmacro.XNfc

  def at_arity_1(a, _b), do: ExDbgi.Defmacro.XNfc.ex_dbgi_defmacro_x_nfc_snoć(a) # @arity_1
end
