# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defguardp.W2.ImportWhole do
  import Src.Defguardp.W2

  def at_import_whole(a, b), do: src_defguardp_w2_snoc(a, b) # @import_whole
end
