# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Def.XOtherModule.Other do
  def ex_dbgi_def_x_other_module_snoc(q, x), do: {q, x}
end
