# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.XArityAbsent.Target do
  def ex_dbgi_defdelegate_x_arity_absent_snoc(q, x), do: {q, x}
  def ex_dbgi_defdelegate_x_arity_absent_snoc(q), do: {q}
  def ex_dbgi_defdelegate_x_arity_absent_snoc(q, x, y), do: {q, x, y}

  def target_marker, do: :ok
end
