# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.XNfc do
  defdelegate ex_dbgi_defdelegate_x_nfc_snoć(q, x), to: ExDbgi.Defdelegate.XNfc.Target

  def local_site(a, b), do: ex_dbgi_defdelegate_x_nfc_snoć(a, b) # @local
end
