# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.XNotACall do
  defdelegate ex_dbgi_defdelegate_x_not_a_call_snoc(q, x), to: ExDbgi.Defdelegate.XNotACall.Target

  def local_site(a, b), do: ex_dbgi_defdelegate_x_not_a_call_snoc(a, b) # @local
end
