# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.W3 do
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_snoc(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_xsnoc(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_snoc_x(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_snoc?(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_snoc!(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_w3_snoć(q, x), to: ExDbgi.DefdelegateUnresolvable.W3.Missing

  def local_site(a, b), do: ex_dbgi_defdelegate_unresolvable_w3_snoc(a, b) # @local
end
