# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.XOtherModule.Other do
  defdelegate ex_dbgi_defdelegate_unresolvable_x_other_module_snoc(q, x), to: ExDbgi.DefdelegateUnresolvable.XOtherModule.Other.Missing
end
