# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.XNotACall.Target do
  def ex_dbgi_defdelegate_x_not_a_call_snoc(q, x), do: {q, x}

  def target_marker, do: :ok
end
