# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XDefaults do
  defp ex_dbgi_defp_x_defaults_snoc(q, x \\ nil), do: {q, x}

  def local_site(a, b), do: ex_dbgi_defp_x_defaults_snoc(a, b) # @local

  def uses(a, b), do: {ex_dbgi_defp_x_defaults_snoc(a), a, b}
end
