# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.W4.Target do
  def ex_dbgi_defdelegate_w4_snoc(q, x), do: {q, x}
  def ex_dbgi_defdelegate_w4_snoc(q), do: {q}
  def ex_dbgi_defdelegate_w4_snoc(q, x, y), do: {q, x, y}
  def ex_dbgi_defdelegate_w4_xsnoc(q, x), do: {q, x}
  def ex_dbgi_defdelegate_w4_snoc_x(q, x), do: {q, x}
  def ex_dbgi_defdelegate_w4_snoc?(q, x), do: {q, x}
  def ex_dbgi_defdelegate_w4_snoc!(q, x), do: {q, x}
  def ex_dbgi_defdelegate_w4_snoć(q, x), do: {q, x}

  def target_marker, do: :ok
end
