# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.XAritySeparate do
  defdelegate ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(), to: ExDbgi.DefdelegateUnresolvable.XAritySeparate.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a), to: ExDbgi.DefdelegateUnresolvable.XAritySeparate.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b), to: ExDbgi.DefdelegateUnresolvable.XAritySeparate.Missing

  def local_site(a, b), do: ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @local
end
