# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defp.XArityAbsent do
  defp ex_dbgi_defp_x_arity_absent_snoc(q, x), do: {q, x}

  def local_site(a, b), do: ex_dbgi_defp_x_arity_absent_snoc(a, b) # @local

  def uses(a, b), do: {a, b}
end
