# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.XDefaults do
  defdelegate ex_dbgi_defdelegate_unresolvable_x_defaults_snoc(q, x \\ nil), to: ExDbgi.DefdelegateUnresolvable.XDefaults.Missing

  def local_site(a, b), do: ex_dbgi_defdelegate_unresolvable_x_defaults_snoc(a, b) # @local
end
