# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defdelegate.XArityZero do
  defdelegate ex_dbgi_defdelegate_x_arity_zero_snoc(), to: ExDbgi.Defdelegate.XArityZero.Target
  defdelegate ex_dbgi_defdelegate_x_arity_zero_snoc(q, x), to: ExDbgi.Defdelegate.XArityZero.Target

  def local_site(a, b), do: ex_dbgi_defdelegate_x_arity_zero_snoc(a, b) # @local
end
