# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defguard.XOtherModule do
  defguard ex_dbgi_defguard_x_other_module_snoc(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: ex_dbgi_defguard_x_other_module_snoc(a, b) # @local
end
