# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Defguard.W4 do
  defguard ex_dbgi_defguard_w4_snoc(q, x) when is_list(q) or is_list(x)
  defguard ex_dbgi_defguard_w4_snoc(q) when is_list(q)
  defguard ex_dbgi_defguard_w4_snoc(q, x, y) when is_list(q) or is_list(x) or is_list(y)
  defguard ex_dbgi_defguard_w4_xsnoc(q, x) when is_list(q) or is_list(x)
  defguard ex_dbgi_defguard_w4_snoc_x(q, x) when is_list(q) or is_list(x)
  defguard ex_dbgi_defguard_w4_snoc?(q, x) when is_list(q) or is_list(x)
  defguard ex_dbgi_defguard_w4_snoc!(q, x) when is_list(q) or is_list(x)
  defguard ex_dbgi_defguard_w4_snoć(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: ex_dbgi_defguard_w4_snoc(a, b) # @local
end
