# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateAs.W2 do
  defdelegate ex_dbgi_defdelegate_as_w2_snoc(q, x), to: ExDbgi.DefdelegateAs.W2.Target, as: :delegated_ex_dbgi_defdelegate_as_w2_snoc
  defdelegate ex_dbgi_defdelegate_as_w2_snoc(q), to: ExDbgi.DefdelegateAs.W2.Target, as: :delegated_ex_dbgi_defdelegate_as_w2_snoc
  defdelegate ex_dbgi_defdelegate_as_w2_snoc(q, x, y), to: ExDbgi.DefdelegateAs.W2.Target, as: :delegated_ex_dbgi_defdelegate_as_w2_snoc

  def local_site(a, b), do: ex_dbgi_defdelegate_as_w2_snoc(a, b) # @local
end
