# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.W1 do
  defdelegate ex_dbgi_defdelegate_unresolvable_w1_snoc(q, x), to: ExDbgi.DefdelegateUnresolvable.W1.Missing

  def local_site(a, b), do: ex_dbgi_defdelegate_unresolvable_w1_snoc(a, b) # @local
end
