# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.Def.W4 do
  def ex_dbgi_def_w4_snoc(q, x) when is_list(q), do: {q, x}
  def ex_dbgi_def_w4_snoc(queue, item), do: {queue, item}
  def ex_dbgi_def_w4_snoc(q), do: {q}
  def ex_dbgi_def_w4_snoc(q, x, y), do: {q, x, y}
  def ex_dbgi_def_w4_xsnoc(q, x), do: {q, x}
  def ex_dbgi_def_w4_snoc_x(q, x), do: {q, x}
  def ex_dbgi_def_w4_snoc?(q, x), do: {q, x}
  def ex_dbgi_def_w4_snoc!(q, x), do: {q, x}
  def ex_dbgi_def_w4_snoć(q, x), do: {q, x}

  def local_site(a, b), do: ex_dbgi_def_w4_snoc(a, b) # @local
end
