# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDbgi.DefdelegateUnresolvable.XArityZero do
  defdelegate ex_dbgi_defdelegate_unresolvable_x_arity_zero_snoc(), to: ExDbgi.DefdelegateUnresolvable.XArityZero.Missing
  defdelegate ex_dbgi_defdelegate_unresolvable_x_arity_zero_snoc(q, x), to: ExDbgi.DefdelegateUnresolvable.XArityZero.Missing

  def local_site(a, b), do: ex_dbgi_defdelegate_unresolvable_x_arity_zero_snoc(a, b) # @local
end
