# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule :erl_abst_def_x_arity_separate do
  def erl_abst_def_x_arity_separate_snoc(), do: {}
  def erl_abst_def_x_arity_separate_snoc(a), do: {a}
  def erl_abst_def_x_arity_separate_snoc(a, b), do: {a, b}
end
