# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule :erl_abst_defp_w4 do
  defp erl_abst_defp_w4_snoc(q, x) when is_list(q), do: {q, x}
  defp erl_abst_defp_w4_snoc(queue, item), do: {queue, item}
  defp erl_abst_defp_w4_snoc(q), do: {q}
  defp erl_abst_defp_w4_snoc(q, x, y), do: {q, x, y}
  defp erl_abst_defp_w4_xsnoc(q, x), do: {q, x}
  defp erl_abst_defp_w4_snoc_x(q, x), do: {q, x}
  defp erl_abst_defp_w4_snoc?(q, x), do: {q, x}
  defp erl_abst_defp_w4_snoc!(q, x), do: {q, x}
  defp erl_abst_defp_w4_snoć(q, x), do: {q, x}
end
