%% Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
-module(erl_abst_defp_w2).
-export([local_site/2, uses/2]).

erl_abst_defp_w2_snoc(Q, X) when is_list(Q) -> {Q, X};
erl_abst_defp_w2_snoc(Queue, Item) -> {Queue, Item}.

erl_abst_defp_w2_snoc(Q) -> {Q}.

erl_abst_defp_w2_snoc(Q, X, Y) -> {Q, X, Y}.

local_site(A, B) -> erl_abst_defp_w2_snoc(A, B). % @local

uses(A, B) -> {erl_abst_defp_w2_snoc(A), erl_abst_defp_w2_snoc(A, B, A), A, B}.
