# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule :erl_abst_def_w2 do
  def erl_abst_def_w2_snoc(q, x) when is_list(q), do: {q, x}
  def erl_abst_def_w2_snoc(queue, item), do: {queue, item}
  def erl_abst_def_w2_snoc(q), do: {q}
  def erl_abst_def_w2_snoc(q, x, y), do: {q, x, y}
end
