%% Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
-module(erl_abst_def_w1).
-export([erl_abst_def_w1_snoc/2, local_site/2]).

erl_abst_def_w1_snoc(Q, X) -> {Q, X}.

local_site(A, B) -> erl_abst_def_w1_snoc(A, B). % @local
