# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule :erl_abst_def_x_not_a_call do
  def erl_abst_def_x_not_a_call_snoc(q, x), do: {q, x}
end
