%% Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
-module(erl_abst_def_w2).
-export([erl_abst_def_w2_snoc/2, erl_abst_def_w2_snoc/1, erl_abst_def_w2_snoc/3, local_site/2]).

erl_abst_def_w2_snoc(Q, X) when is_list(Q) -> {Q, X};
erl_abst_def_w2_snoc(Queue, Item) -> {Queue, Item}.

erl_abst_def_w2_snoc(Q) -> {Q}.

erl_abst_def_w2_snoc(Q, X, Y) -> {Q, X, Y}.

local_site(A, B) -> erl_abst_def_w2_snoc(A, B). % @local
