# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule :erl_abst_def_w3 do
  def erl_abst_def_w3_snoc(q, x), do: {q, x}
  def erl_abst_def_w3_xsnoc(q, x), do: {q, x}
  def erl_abst_def_w3_snoc_x(q, x), do: {q, x}
  def erl_abst_def_w3_snoc?(q, x), do: {q, x}
  def erl_abst_def_w3_snoc!(q, x), do: {q, x}
  def erl_abst_def_w3_snoć(q, x), do: {q, x}
end
