# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFrom.XAritySeparateBroken do
  alias Src.EexFunctionFrom.XAritySeparate
  alias Src.EexFunctionFrom.XAritySeparate, as: Aliased
  import Src.EexFunctionFrom.XAritySeparate

  def at_arity_3(a, b), do: Src.EexFunctionFrom.XAritySeparate.src_eex_function_from_x_arity_separate_snoc(a, b, a) # @arity_3
end
