# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFrom.XArityAbsentUndefined do
  alias Src.EexFunctionFrom.XArityAbsent
  alias Src.EexFunctionFrom.XArityAbsent, as: Aliased
  import Src.EexFunctionFrom.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: src_eex_function_from_x_arity_absent_snoc(a) # @unqualified_arity_1
end
