# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFrom.XArityZeroBroken do
  alias Src.EexFunctionFrom.XArityZero
  alias Src.EexFunctionFrom.XArityZero, as: Aliased
  import Src.EexFunctionFrom.XArityZero

  def at_arity_1(a, _b), do: Src.EexFunctionFrom.XArityZero.src_eex_function_from_x_arity_zero_snoc(a) # @arity_1
end
