# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFrom.XNotACall do
  alias Src.EexFunctionFrom.XNotACall
  alias Src.EexFunctionFrom.XNotACall, as: Aliased
  import Src.EexFunctionFrom.XNotACall

  def at_qualified(a, b), do: Src.EexFunctionFrom.XNotACall.src_eex_function_from_x_not_a_call_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XNotACall.src_eex_function_from_x_not_a_call_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_eex_function_from_x_not_a_call_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_eex_function_from_x_not_a_call_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_eex_function_from_x_not_a_call_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.EexFunctionFrom.XNotACall.src_eex_function_from_x_not_a_call_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.EexFunctionFrom.XNotACall, :src_eex_function_from_x_not_a_call_snoc, [a, b]) # @apply
  def at_variable(a, b), do: (fn src_eex_function_from_x_not_a_call_snoc -> src_eex_function_from_x_not_a_call_snoc end).({a, b}) # @variable
  def at_atom(a, b), do: {:src_eex_function_from_x_not_a_call_snoc, a, b} # @atom
  def at_keyword(a, b), do: [src_eex_function_from_x_not_a_call_snoc: a, b: b] # @keyword
end
