# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.EexFunctionFrom.XOtherModule do
  alias Src.EexFunctionFrom.XOtherModule
  alias Src.EexFunctionFrom.XOtherModule, as: Aliased
  import Src.EexFunctionFrom.XOtherModule

  def at_qualified(a, b), do: Src.EexFunctionFrom.XOtherModule.src_eex_function_from_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.src_eex_function_from_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_eex_function_from_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_eex_function_from_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_eex_function_from_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.EexFunctionFrom.XOtherModule.src_eex_function_from_x_other_module_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.EexFunctionFrom.XOtherModule, :src_eex_function_from_x_other_module_snoc, [a, b]) # @apply
  def at_other_qualified(a, b), do: Src.EexFunctionFrom.XOtherModule.Other.src_eex_function_from_x_other_module_snoc(a, b) # @other_qualified
end
