# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defdelegate.XAritySeparate do
  defdelegate ex_docs_defdelegate_x_arity_separate_snoc(), to: ExDocs.Defdelegate.XAritySeparate.Target
  defdelegate ex_docs_defdelegate_x_arity_separate_snoc(a), to: ExDocs.Defdelegate.XAritySeparate.Target
  defdelegate ex_docs_defdelegate_x_arity_separate_snoc(a, b), to: ExDocs.Defdelegate.XAritySeparate.Target

  def local_site(a, b), do: ex_docs_defdelegate_x_arity_separate_snoc(a, b) # @local
end
