# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defdelegate.W1.Target do
  def ex_docs_defdelegate_w1_snoc(q, x), do: {q, x}

  def target_marker, do: :ok
end
