# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defmacro.W2 do
  defmacro ex_docs_defmacro_w2_snoc(q, x) when is_list(q), do: quote(do: {unquote(q), unquote(x)})
  defmacro ex_docs_defmacro_w2_snoc(queue, item), do: quote(do: {unquote(queue), unquote(item)})
  defmacro ex_docs_defmacro_w2_snoc(q), do: quote(do: {unquote(q)})
  defmacro ex_docs_defmacro_w2_snoc(q, x, y), do: quote(do: {unquote(q), unquote(x), unquote(y)})

  def local_site(a, b), do: ex_docs_defmacro_w2_snoc(a, b) # @local
end
