# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defdelegate.W3 do
  defdelegate ex_docs_defdelegate_w3_snoc(q, x), to: ExDocs.Defdelegate.W3.Target
  defdelegate ex_docs_defdelegate_w3_xsnoc(q, x), to: ExDocs.Defdelegate.W3.Target
  defdelegate ex_docs_defdelegate_w3_snoc_x(q, x), to: ExDocs.Defdelegate.W3.Target
  defdelegate ex_docs_defdelegate_w3_snoc?(q, x), to: ExDocs.Defdelegate.W3.Target
  defdelegate ex_docs_defdelegate_w3_snoc!(q, x), to: ExDocs.Defdelegate.W3.Target
  defdelegate ex_docs_defdelegate_w3_snoć(q, x), to: ExDocs.Defdelegate.W3.Target

  def local_site(a, b), do: ex_docs_defdelegate_w3_snoc(a, b) # @local
end
