# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.DefdelegateAs.XOtherModule.Other.Target do
  def delegated_ex_docs_defdelegate_as_x_other_module_snoc(q, x), do: {q, x}

  def target_marker, do: :ok
end
