# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defguard.W3 do
  defguard ex_docs_defguard_w3_snoc(q, x) when is_list(q) or is_list(x)
  defguard ex_docs_defguard_w3_xsnoc(q, x) when is_list(q) or is_list(x)
  defguard ex_docs_defguard_w3_snoc_x(q, x) when is_list(q) or is_list(x)
  defguard ex_docs_defguard_w3_snoc?(q, x) when is_list(q) or is_list(x)
  defguard ex_docs_defguard_w3_snoc!(q, x) when is_list(q) or is_list(x)
  defguard ex_docs_defguard_w3_snoć(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: ex_docs_defguard_w3_snoc(a, b) # @local
end
