# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.DefdelegateAs.XDefaults do
  defdelegate ex_docs_defdelegate_as_x_defaults_snoc(q, x \\ nil), to: ExDocs.DefdelegateAs.XDefaults.Target, as: :delegated_ex_docs_defdelegate_as_x_defaults_snoc

  def local_site(a, b), do: ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @local
end
