# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defp.XLookalikeAbsent do
  defp ex_docs_defp_x_lookalike_absent_snoc(q, x), do: {q, x}
  defp ex_docs_defp_x_lookalike_absent_xsnoc(q, x), do: {q, x}
  defp ex_docs_defp_x_lookalike_absent_snoc_x(q, x), do: {q, x}
  defp ex_docs_defp_x_lookalike_absent_snoc?(q, x), do: {q, x}
  defp ex_docs_defp_x_lookalike_absent_snoc!(q, x), do: {q, x}
  defp ex_docs_defp_x_lookalike_absent_snoć(q, x), do: {q, x}

  def local_site(a, b), do: ex_docs_defp_x_lookalike_absent_snoc(a, b) # @local

  def uses(a, b), do: {ex_docs_defp_x_lookalike_absent_xsnoc(a, b), ex_docs_defp_x_lookalike_absent_snoc_x(a, b), ex_docs_defp_x_lookalike_absent_snoc?(a, b), ex_docs_defp_x_lookalike_absent_snoc!(a, b), ex_docs_defp_x_lookalike_absent_snoć(a, b), a, b}
end
