# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.DefdelegateAs.W1 do
  defdelegate ex_docs_defdelegate_as_w1_snoc(q, x), to: ExDocs.DefdelegateAs.W1.Target, as: :delegated_ex_docs_defdelegate_as_w1_snoc

  def local_site(a, b), do: ex_docs_defdelegate_as_w1_snoc(a, b) # @local
end
