# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defmacro.XDefaultsHead do
  defmacro ex_docs_defmacro_x_defaults_head_snoc(a \\ nil, b \\ nil)
  defmacro ex_docs_defmacro_x_defaults_head_snoc(a, b) when is_nil(a), do: quote(do: {unquote(a), unquote(b)})
  defmacro ex_docs_defmacro_x_defaults_head_snoc(a, b), do: quote(do: {unquote(a), unquote(b)})

  def local_site(a, b), do: ex_docs_defmacro_x_defaults_head_snoc(a, b) # @local
end
