# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Def.XAritySeparate do
  def ex_docs_def_x_arity_separate_snoc(), do: {}
  def ex_docs_def_x_arity_separate_snoc(a), do: {a}
  def ex_docs_def_x_arity_separate_snoc(a, b), do: {a, b}

  def local_site(a, b), do: ex_docs_def_x_arity_separate_snoc(a, b) # @local
end
