# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.GeneratorEmbed.XEmbed do
  require Mix.Generator

  Mix.Generator.embed_template(:ex_docs_generator_embed_x_embed_snoc, "<%= @q %>")
  Mix.Generator.embed_text(:ex_docs_generator_embed_x_embed_snoc, "text")

  def local_site(a, _b), do: ex_docs_generator_embed_x_embed_snoc_template(a) # @local

  def uses(a, b) do
    {
      ex_docs_generator_embed_x_embed_snoc_text(), # @uses_0
      a,
      b
    }
  end
end
