# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Def.XLookalikeAbsent do
  def ex_docs_def_x_lookalike_absent_snoc(q, x), do: {q, x}
  def ex_docs_def_x_lookalike_absent_xsnoc(q, x), do: {q, x}
  def ex_docs_def_x_lookalike_absent_snoc_x(q, x), do: {q, x}
  def ex_docs_def_x_lookalike_absent_snoc?(q, x), do: {q, x}
  def ex_docs_def_x_lookalike_absent_snoc!(q, x), do: {q, x}
  def ex_docs_def_x_lookalike_absent_snoć(q, x), do: {q, x}

  def local_site(a, b), do: ex_docs_def_x_lookalike_absent_snoc(a, b) # @local
end
