# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defp.XAritySeparate do
  defp ex_docs_defp_x_arity_separate_snoc(), do: {}
  defp ex_docs_defp_x_arity_separate_snoc(a), do: {a}
  defp ex_docs_defp_x_arity_separate_snoc(a, b), do: {a, b}

  def local_site(a, b), do: ex_docs_defp_x_arity_separate_snoc(a, b) # @local

  def uses(a, b) do
    {
      ex_docs_defp_x_arity_separate_snoc(), # @uses_0
      ex_docs_defp_x_arity_separate_snoc(a), # @uses_1
      a,
      b
    }
  end
end
