# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.DefdelegateUnresolvable.XDefaultsHead do
  defdelegate ex_docs_defdelegate_unresolvable_x_defaults_head_snoc(a \\ nil, b \\ nil), to: ExDocs.DefdelegateUnresolvable.XDefaultsHead.Missing

  def local_site(a, b), do: ex_docs_defdelegate_unresolvable_x_defaults_head_snoc(a, b) # @local
end
