# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.DefdelegateUnresolvable.XOtherModule do
  defdelegate ex_docs_defdelegate_unresolvable_x_other_module_snoc(q, x), to: ExDocs.DefdelegateUnresolvable.XOtherModule.Missing

  def local_site(a, b), do: ex_docs_defdelegate_unresolvable_x_other_module_snoc(a, b) # @local
end
