# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defdelegate.XLookalikeAbsent do
  defdelegate ex_docs_defdelegate_x_lookalike_absent_snoc(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target
  defdelegate ex_docs_defdelegate_x_lookalike_absent_xsnoc(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target
  defdelegate ex_docs_defdelegate_x_lookalike_absent_snoc_x(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target
  defdelegate ex_docs_defdelegate_x_lookalike_absent_snoc?(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target
  defdelegate ex_docs_defdelegate_x_lookalike_absent_snoc!(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target
  defdelegate ex_docs_defdelegate_x_lookalike_absent_snoć(q, x), to: ExDocs.Defdelegate.XLookalikeAbsent.Target

  def local_site(a, b), do: ex_docs_defdelegate_x_lookalike_absent_snoc(a, b) # @local
end
