# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defdelegate.XArityAbsent do
  defdelegate ex_docs_defdelegate_x_arity_absent_snoc(q, x), to: ExDocs.Defdelegate.XArityAbsent.Target

  def local_site(a, b), do: ex_docs_defdelegate_x_arity_absent_snoc(a, b) # @local
end
