# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.EexFunctionFrom.XArityZero do
  require EEx

  EEx.function_from_string(:def, :ex_docs_eex_function_from_x_arity_zero_snoc, "<%= inspect({}) %>", [])
  EEx.function_from_string(:def, :ex_docs_eex_function_from_x_arity_zero_snoc, "<%= inspect({q, x}) %>", [:q, :x])

  def local_site(a, b), do: ex_docs_eex_function_from_x_arity_zero_snoc(a, b) # @local
end
