# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExDocs.Defguard.XNotACall do
  defguard ex_docs_defguard_x_not_a_call_snoc(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: ex_docs_defguard_x_not_a_call_snoc(a, b) # @local
end
