# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XAritySeparateBroken do
  alias Src.Def.XAritySeparate
  alias Src.Def.XAritySeparate, as: Aliased
  import Src.Def.XAritySeparate

  def at_arity_3(a, b), do: Src.Def.XAritySeparate.src_def_x_arity_separate_snoc(a, b, a) # @arity_3
end
