# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XArityAbsentUndefined do
  alias Src.Def.XArityAbsent
  alias Src.Def.XArityAbsent, as: Aliased
  import Src.Def.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: src_def_x_arity_absent_snoc(a) # @unqualified_arity_1
end
