# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XConditional do
  alias Src.Def.XConditional
  alias Src.Def.XConditional, as: Aliased
  import Src.Def.XConditional

  def at_qualified(a, b), do: Src.Def.XConditional.src_def_x_conditional_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XConditional.src_def_x_conditional_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_def_x_conditional_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_def_x_conditional_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_def_x_conditional_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.Def.XConditional.src_def_x_conditional_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.Def.XConditional, :src_def_x_conditional_snoc, [a, b]) # @apply
end
