# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XDefaultsHead.ImportOnly2 do
  import Src.Def.XDefaultsHead, only: [src_def_x_defaults_head_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: src_def_x_defaults_head_snoc(a, b) # @import_only_2
end
