# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XDefaultsHeadUndefined do
  alias Src.Def.XDefaultsHead
  alias Src.Def.XDefaultsHead, as: Aliased
  import Src.Def.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: src_def_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
