# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XLookalikeAbsentUndefined do
  alias Src.Def.XLookalikeAbsent
  alias Src.Def.XLookalikeAbsent, as: Aliased
  import Src.Def.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: src_def_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
