# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Def.XNfc do
  alias Src.Def.XNfc
  alias Src.Def.XNfc, as: Aliased
  import Src.Def.XNfc

  def at_qualified(a, b), do: Src.Def.XNfc.src_def_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.src_def_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_def_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_def_x_nfc_snoć(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_def_x_nfc_snoć(b) # @pipe
  def at_capture(a, b), do: {&Src.Def.XNfc.src_def_x_nfc_snoć/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.Def.XNfc, :src_def_x_nfc_snoć, [a, b]) # @apply
  def at_apply_quoted(a, b), do: apply(Src.Def.XNfc, :"src_def_x_nfc_snoć", [a, b]) # @apply_quoted
  def at_atom(a, b), do: {:src_def_x_nfc_snoć, a, b} # @atom
end
