# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.W2 do
  alias Src.DefdelegateCompiled.W2
  alias Src.DefdelegateCompiled.W2, as: Aliased
  import Src.DefdelegateCompiled.W2

  def at_qualified(a, b), do: Src.DefdelegateCompiled.W2.src_defdelegate_compiled_w2_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W2.src_defdelegate_compiled_w2_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_compiled_w2_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_compiled_w2_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_compiled_w2_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.DefdelegateCompiled.W2.src_defdelegate_compiled_w2_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.DefdelegateCompiled.W2, :src_defdelegate_compiled_w2_snoc, [a, b]) # @apply
  def at_second_qualified(a, b), do: Src.DefdelegateCompiled.W2.src_defdelegate_compiled_w2_snoc(a, b) # @second_qualified
  def at_arity_1(a, _b), do: Src.DefdelegateCompiled.W2.src_defdelegate_compiled_w2_snoc(a) # @arity_1
  def at_arity_3(a, b), do: Src.DefdelegateCompiled.W2.src_defdelegate_compiled_w2_snoc(a, b, a) # @arity_3
end
