# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XArityZeroBroken do
  alias Src.DefdelegateCompiled.XArityZero
  alias Src.DefdelegateCompiled.XArityZero, as: Aliased
  import Src.DefdelegateCompiled.XArityZero

  def at_arity_1(a, _b), do: Src.DefdelegateCompiled.XArityZero.src_defdelegate_compiled_x_arity_zero_snoc(a) # @arity_1
end
