# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportTransitive.Middle do
  import Src.DefdelegateCompiled.XDefaultsHead
  def middle_marker, do: :ok
end

defmodule Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportTransitive do
  import Callers.Src.DefdelegateCompiled.XDefaultsHead.ImportTransitive.Middle

  def at_import_transitive(a, b), do: src_defdelegate_compiled_x_defaults_head_snoc(a, b) # @import_transitive
end

