# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XDefaults.ImportMacros do
  import Src.DefdelegateCompiled.XDefaults, only: :macros

  def at_import_macros(a, b), do: src_defdelegate_compiled_x_defaults_snoc(a, b) # @import_macros
end
