# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XLookalikeAbsentUndefined do
  alias Src.DefdelegateCompiled.XLookalikeAbsent
  alias Src.DefdelegateCompiled.XLookalikeAbsent, as: Aliased
  import Src.DefdelegateCompiled.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: src_defdelegate_compiled_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
