# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XNfc do
  alias Src.DefdelegateCompiled.XNfc
  alias Src.DefdelegateCompiled.XNfc, as: Aliased
  import Src.DefdelegateCompiled.XNfc

  def at_qualified(a, b), do: Src.DefdelegateCompiled.XNfc.src_defdelegate_compiled_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.src_defdelegate_compiled_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_compiled_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_compiled_x_nfc_snoć(a, b) # @unqualified
end
