# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateCompiled.XOtherModule do
  alias Src.DefdelegateCompiled.XOtherModule
  alias Src.DefdelegateCompiled.XOtherModule, as: Aliased
  import Src.DefdelegateCompiled.XOtherModule

  def at_qualified(a, b), do: Src.DefdelegateCompiled.XOtherModule.src_defdelegate_compiled_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.src_defdelegate_compiled_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_compiled_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_compiled_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_compiled_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.DefdelegateCompiled.XOtherModule.src_defdelegate_compiled_x_other_module_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.DefdelegateCompiled.XOtherModule, :src_defdelegate_compiled_x_other_module_snoc, [a, b]) # @apply
  def at_other_qualified(a, b), do: Src.DefdelegateCompiled.XOtherModule.Other.src_defdelegate_compiled_x_other_module_snoc(a, b) # @other_qualified
end
