# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defp.W2.ImportWhole do
  import ExDbgi.Defp.W2

  def at_import_whole(a, b), do: ex_dbgi_defp_w2_snoc(a, b) # @import_whole
end
