# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defp.XAritySeparate.ImportFunctions do
  import ExDbgi.Defp.XAritySeparate, only: :functions

  def at_import_functions(a, b), do: ex_dbgi_defp_x_arity_separate_snoc(a, b) # @import_functions
end
