# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.EexFunctionFrom.XArityZeroBroken do
  alias ExDocs.EexFunctionFrom.XArityZero
  alias ExDocs.EexFunctionFrom.XArityZero, as: Aliased
  import ExDocs.EexFunctionFrom.XArityZero

  def at_arity_1(a, _b), do: ExDocs.EexFunctionFrom.XArityZero.ex_docs_eex_function_from_x_arity_zero_snoc(a) # @arity_1
end
