# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateAs.XArityAbsentUndefined do
  alias ExDocs.DefdelegateAs.XArityAbsent
  alias ExDocs.DefdelegateAs.XArityAbsent, as: Aliased
  import ExDocs.DefdelegateAs.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_docs_defdelegate_as_x_arity_absent_snoc(a) # @unqualified_arity_1
end
