# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateAs.XDefaults.ImportOnly2 do
  import ExDocs.DefdelegateAs.XDefaults, only: [ex_docs_defdelegate_as_x_defaults_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @import_only_2
end
