# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.DefdelegateAs.XDefaults do
  alias ExDocs.DefdelegateAs.XDefaults
  alias ExDocs.DefdelegateAs.XDefaults, as: Aliased
  import ExDocs.DefdelegateAs.XDefaults

  def at_qualified(a, b), do: ExDocs.DefdelegateAs.XDefaults.ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XDefaults.ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defdelegate_as_x_defaults_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defdelegate_as_x_defaults_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.DefdelegateAs.XDefaults.ex_docs_defdelegate_as_x_defaults_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDocs.DefdelegateAs.XDefaults, :ex_docs_defdelegate_as_x_defaults_snoc, [a, b]) # @apply
  def at_default_arity(a, _b), do: ExDocs.DefdelegateAs.XDefaults.ex_docs_defdelegate_as_x_defaults_snoc(a) # @default_arity
end
