# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateAs.W2.ImportExcept1 do
  import ExDbgi.DefdelegateAs.W2, except: [ex_dbgi_defdelegate_as_w2_snoc: 1] # @import_except_1_key

  def at_import_except_1(a, _b), do: ex_dbgi_defdelegate_as_w2_snoc(a) # @import_except_1
end
