# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateAs.W2.ImportMacros do
  import ExDbgi.DefdelegateAs.W2, only: :macros

  def at_import_macros(a, b), do: ex_dbgi_defdelegate_as_w2_snoc(a, b) # @import_macros
end
