# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateAs.XOtherModule do
  alias ExDbgi.DefdelegateAs.XOtherModule
  alias ExDbgi.DefdelegateAs.XOtherModule, as: Aliased
  import ExDbgi.DefdelegateAs.XOtherModule

  def at_qualified(a, b), do: ExDbgi.DefdelegateAs.XOtherModule.ex_dbgi_defdelegate_as_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.ex_dbgi_defdelegate_as_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_as_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_as_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defdelegate_as_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.DefdelegateAs.XOtherModule.ex_dbgi_defdelegate_as_x_other_module_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDbgi.DefdelegateAs.XOtherModule, :ex_dbgi_defdelegate_as_x_other_module_snoc, [a, b]) # @apply
  def at_other_qualified(a, b), do: ExDbgi.DefdelegateAs.XOtherModule.Other.ex_dbgi_defdelegate_as_x_other_module_snoc(a, b) # @other_qualified
end
