# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XTry.Target do
  try do
    def src_defdelegate_compiled_x_try_snoc(q, x), do: {q, x}
  rescue
    _ -> nil
  end

  def target_marker, do: :ok
end
