# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XConditional.Target do
  if Code.ensure_loaded?(Kernel) do
    def src_defdelegate_compiled_x_conditional_snoc(q, x), do: {q, x}
  end

  def target_marker, do: :ok
end
