# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Src.DefdelegateCompiled.XNfc.Target do
  def src_defdelegate_compiled_x_nfc_snoć(q, x), do: {q, x}

  def target_marker, do: :ok
end
