# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XArityZeroBroken do
  alias ExGen.DefdelegateUnresolvable.XArityZero
  alias ExGen.DefdelegateUnresolvable.XArityZero, as: Aliased
  import ExGen.DefdelegateUnresolvable.XArityZero

  def at_arity_1(a, _b), do: ExGen.DefdelegateUnresolvable.XArityZero.ex_gen_defdelegate_unresolvable_x_arity_zero_snoc(a) # @arity_1
end
