# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XAritySeparate.ImportTransitive.Middle do
  import ExGen.DefdelegateUnresolvable.XAritySeparate
  def middle_marker, do: :ok
end

defmodule Callers.ExGen.DefdelegateUnresolvable.XAritySeparate.ImportTransitive do
  import Callers.ExGen.DefdelegateUnresolvable.XAritySeparate.ImportTransitive.Middle

  def at_import_transitive(a, b), do: ex_gen_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @import_transitive
end

