# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XAritySeparateBroken do
  alias ExGen.DefdelegateUnresolvable.XAritySeparate
  alias ExGen.DefdelegateUnresolvable.XAritySeparate, as: Aliased
  import ExGen.DefdelegateUnresolvable.XAritySeparate

  def at_arity_3(a, b), do: ExGen.DefdelegateUnresolvable.XAritySeparate.ex_gen_defdelegate_unresolvable_x_arity_separate_snoc(a, b, a) # @arity_3
end
