# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XAritySeparate.ImportMacros do
  import ExGen.DefdelegateUnresolvable.XAritySeparate, only: :macros

  def at_import_macros(a, b), do: ex_gen_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @import_macros
end
