# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XDefaults.ImportOnly2 do
  import ExGen.DefdelegateUnresolvable.XDefaults, only: [ex_gen_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: ex_gen_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_only_2
end
