# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateUnresolvable.XLookalikeAbsentUndefined do
  alias ExGen.DefdelegateUnresolvable.XLookalikeAbsent
  alias ExGen.DefdelegateUnresolvable.XLookalikeAbsent, as: Aliased
  import ExGen.DefdelegateUnresolvable.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_defdelegate_unresolvable_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
