# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defp.XAritySeparate.ImportWhole do
  import Src.Defp.XAritySeparate

  def at_import_whole(a, b), do: src_defp_x_arity_separate_snoc(a, b) # @import_whole
end
