# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defp.XArityAbsentBroken do

  def at_private_remote(a, b), do: Src.Defp.XArityAbsent.snoc(a, b) # @private_remote
  def at_private_remote_arity_1(a, _b), do: Src.Defp.XArityAbsent.snoc(a) # @private_remote_arity_1
  def at_private_remote_arity_3(a, b), do: Src.Defp.XArityAbsent.snoc(a, b, a) # @private_remote_arity_3
end
