# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defdelegate.XOtherModule do
  defdelegate ex_gen_defdelegate_x_other_module_snoc(q, x), to: ExGen.Defdelegate.XOtherModule.Target

  def local_site(a, b), do: ex_gen_defdelegate_x_other_module_snoc(a, b) # @local
end
