# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defguard.W2 do
  defguard ex_gen_defguard_w2_snoc(q, x) when is_list(q) or is_list(x)
  defguard ex_gen_defguard_w2_snoc(q) when is_list(q)
  defguard ex_gen_defguard_w2_snoc(q, x, y) when is_list(q) or is_list(x) or is_list(y)

  def local_site(a, b), do: ex_gen_defguard_w2_snoc(a, b) # @local
end
