# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defp.W3 do
  defp ex_gen_defp_w3_snoc(q, x), do: {q, x}
  defp ex_gen_defp_w3_xsnoc(q, x), do: {q, x}
  defp ex_gen_defp_w3_snoc_x(q, x), do: {q, x}
  defp ex_gen_defp_w3_snoc?(q, x), do: {q, x}
  defp ex_gen_defp_w3_snoc!(q, x), do: {q, x}
  defp ex_gen_defp_w3_snoć(q, x), do: {q, x}

  def local_site(a, b), do: ex_gen_defp_w3_snoc(a, b) # @local

  def uses(a, b) do
    {
      ex_gen_defp_w3_xsnoc(a, b), # @uses_0
      ex_gen_defp_w3_snoc_x(a, b), # @uses_1
      ex_gen_defp_w3_snoc?(a, b), # @uses_2
      ex_gen_defp_w3_snoc!(a, b), # @uses_3
      ex_gen_defp_w3_snoć(a, b), # @uses_4
      a,
      b
    }
  end
end
