# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Def.XArityAbsent do
  def ex_gen_def_x_arity_absent_snoc(q, x), do: {q, x}

  def local_site(a, b), do: ex_gen_def_x_arity_absent_snoc(a, b) # @local
end
