# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defmacro.XArityAbsent do
  defmacro ex_gen_defmacro_x_arity_absent_snoc(q, x), do: quote(do: {unquote(q), unquote(x)})

  def local_site(a, b), do: ex_gen_defmacro_x_arity_absent_snoc(a, b) # @local
end
