# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defmacro.XAritySeparate do
  defmacro ex_gen_defmacro_x_arity_separate_snoc(), do: quote(do: {})
  defmacro ex_gen_defmacro_x_arity_separate_snoc(a), do: quote(do: {unquote(a)})
  defmacro ex_gen_defmacro_x_arity_separate_snoc(a, b), do: quote(do: {unquote(a), unquote(b)})

  def local_site(a, b), do: ex_gen_defmacro_x_arity_separate_snoc(a, b) # @local
end
