# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defp.XDefaultsHead do
  defp ex_gen_defp_x_defaults_head_snoc(a \\ nil, b \\ nil)
  defp ex_gen_defp_x_defaults_head_snoc(a, b) when is_nil(a), do: {a, b}
  defp ex_gen_defp_x_defaults_head_snoc(a, b), do: {a, b}

  def local_site(a, b), do: ex_gen_defp_x_defaults_head_snoc(a, b) # @local

  def uses(a, b) do
    {
      ex_gen_defp_x_defaults_head_snoc(), # @uses_0
      ex_gen_defp_x_defaults_head_snoc(a), # @uses_1
      a,
      b
    }
  end
end
