# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Def.XArity do
  def ex_gen_def_x_arity_snoc(q, x), do: {q, x}
  def ex_gen_def_x_arity_snoc(q, x, y), do: {q, x, y}

  def local_site(a, b), do: ex_gen_def_x_arity_snoc(a, b) # @local
end
