# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defguard.W1 do
  defguard ex_gen_defguard_w1_snoc(q, x) when is_list(q) or is_list(x)

  def local_site(a, b), do: ex_gen_defguard_w1_snoc(a, b) # @local
end
