# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defdelegate.XAritySeparate do
  defdelegate ex_gen_defdelegate_x_arity_separate_snoc(), to: ExGen.Defdelegate.XAritySeparate.Target
  defdelegate ex_gen_defdelegate_x_arity_separate_snoc(a), to: ExGen.Defdelegate.XAritySeparate.Target
  defdelegate ex_gen_defdelegate_x_arity_separate_snoc(a, b), to: ExGen.Defdelegate.XAritySeparate.Target

  def local_site(a, b), do: ex_gen_defdelegate_x_arity_separate_snoc(a, b) # @local
end
