# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defdelegate.W4 do
  defdelegate ex_gen_defdelegate_w4_snoc(q, x), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoc(q), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoc(q, x, y), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_xsnoc(q, x), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoc_x(q, x), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoc?(q, x), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoc!(q, x), to: ExGen.Defdelegate.W4.Target
  defdelegate ex_gen_defdelegate_w4_snoć(q, x), to: ExGen.Defdelegate.W4.Target

  def local_site(a, b), do: ex_gen_defdelegate_w4_snoc(a, b) # @local
end
