# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.Defdelegate.XOtherModule.Other do
  defdelegate ex_gen_defdelegate_x_other_module_snoc(q, x), to: ExGen.Defdelegate.XOtherModule.Other.Target
end
