# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.DefdelegateAs.XArityAbsent do
  defdelegate ex_gen_defdelegate_as_x_arity_absent_snoc(q, x), to: ExGen.DefdelegateAs.XArityAbsent.Target, as: :delegated_ex_gen_defdelegate_as_x_arity_absent_snoc

  def local_site(a, b), do: ex_gen_defdelegate_as_x_arity_absent_snoc(a, b) # @local
end
