# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule ExGen.DefdelegateUnresolvable.XArity do
  defdelegate ex_gen_defdelegate_unresolvable_x_arity_snoc(q, x), to: ExGen.DefdelegateUnresolvable.XArity.Missing
  defdelegate ex_gen_defdelegate_unresolvable_x_arity_snoc(q, x, y), to: ExGen.DefdelegateUnresolvable.XArity.Missing

  def local_site(a, b), do: ex_gen_defdelegate_unresolvable_x_arity_snoc(a, b) # @local
end
