# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.W2.ImportOnly2 do
  import ExDocs.Defdelegate.W2, only: [ex_docs_defdelegate_w2_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: ex_docs_defdelegate_w2_snoc(a, b) # @import_only_2
end
