# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.XDefaultsHead.ImportOnly do
  import ExDocs.Defdelegate.XDefaultsHead, only: [ex_docs_defdelegate_x_defaults_head_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_docs_defdelegate_x_defaults_head_snoc(a) # @import_only_1
end

defmodule Callers.ExDocs.Defdelegate.XDefaultsHead.ImportExcept do
  import ExDocs.Defdelegate.XDefaultsHead, except: [ex_docs_defdelegate_x_defaults_head_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_docs_defdelegate_x_defaults_head_snoc(a, b) # @import_except_2
end
