# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.XDefaults.RequireOnly do
  require ExDocs.Defdelegate.XDefaults

  def at_require_only(a, b), do: ex_docs_defdelegate_x_defaults_snoc(a, b) # @require_only
end
