# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.XDefaultsHead.ImportExcept1 do
  import ExDocs.Defdelegate.XDefaultsHead, except: [ex_docs_defdelegate_x_defaults_head_snoc: 1] # @import_except_1_key

  def at_import_except_1(a, _b), do: ex_docs_defdelegate_x_defaults_head_snoc(a) # @import_except_1
end
