# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.XLookalikeAbsentUndefined do
  alias ExDocs.Defdelegate.XLookalikeAbsent
  alias ExDocs.Defdelegate.XLookalikeAbsent, as: Aliased
  import ExDocs.Defdelegate.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_docs_defdelegate_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
