# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defdelegate.XNfcBroken do
  alias ExDocs.Defdelegate.XNfc
  alias ExDocs.Defdelegate.XNfc, as: Aliased
  import ExDocs.Defdelegate.XNfc

  def at_arity_1(a, _b), do: ExDocs.Defdelegate.XNfc.ex_docs_defdelegate_x_nfc_snoć(a) # @arity_1
end
