# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XAritySeparate.RequireOnly do
  require ExDocs.Def.XAritySeparate

  def at_require_only(a, b), do: ex_docs_def_x_arity_separate_snoc(a, b) # @require_only
end
