# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XArityZeroBroken do
  alias ExDocs.Def.XArityZero
  alias ExDocs.Def.XArityZero, as: Aliased
  import ExDocs.Def.XArityZero

  def at_arity_1(a, _b), do: ExDocs.Def.XArityZero.ex_docs_def_x_arity_zero_snoc(a) # @arity_1
end
