# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XArityZero do
  alias ExDocs.Def.XArityZero
  alias ExDocs.Def.XArityZero, as: Aliased
  import ExDocs.Def.XArityZero

  def at_qualified(a, b), do: ExDocs.Def.XArityZero.ex_docs_def_x_arity_zero_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityZero.ex_docs_def_x_arity_zero_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_def_x_arity_zero_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_def_x_arity_zero_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_def_x_arity_zero_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.Def.XArityZero.ex_docs_def_x_arity_zero_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDocs.Def.XArityZero, :ex_docs_def_x_arity_zero_snoc, [a, b]) # @apply
  def at_no_arguments(_a, _b), do: ExDocs.Def.XArityZero.ex_docs_def_x_arity_zero_snoc # @no_arguments
end
