# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XLookalikeAbsentBroken do
  alias ExDocs.Def.XLookalikeAbsent
  alias ExDocs.Def.XLookalikeAbsent, as: Aliased
  import ExDocs.Def.XLookalikeAbsent

  def at_arity_1(a, _b), do: ExDocs.Def.XLookalikeAbsent.ex_docs_def_x_lookalike_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: ExDocs.Def.XLookalikeAbsent.ex_docs_def_x_lookalike_absent_snoc(a, b, a) # @arity_3
  def at_undeclared(a, b), do: ExDocs.Def.XLookalikeAbsent.ex_docs_def_x_lookalike_absent_undeclared(a, b) # @undeclared
end
