# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XLookalikeAbsentUndefined do
  alias ExDocs.Def.XLookalikeAbsent
  alias ExDocs.Def.XLookalikeAbsent, as: Aliased
  import ExDocs.Def.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_docs_def_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
