# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Def.XOtherModule do
  alias ExDocs.Def.XOtherModule
  alias ExDocs.Def.XOtherModule, as: Aliased
  import ExDocs.Def.XOtherModule

  def at_qualified(a, b), do: ExDocs.Def.XOtherModule.ex_docs_def_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.ex_docs_def_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_def_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_def_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_def_x_other_module_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDocs.Def.XOtherModule.ex_docs_def_x_other_module_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDocs.Def.XOtherModule, :ex_docs_def_x_other_module_snoc, [a, b]) # @apply
  def at_other_qualified(a, b), do: ExDocs.Def.XOtherModule.Other.ex_docs_def_x_other_module_snoc(a, b) # @other_qualified
end
