# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XAritySeparate do
  import :erl_abst_def_x_arity_separate

  def at_qualified(a, b), do: :erl_abst_def_x_arity_separate.erl_abst_def_x_arity_separate_snoc(a, b) # @qualified
  def at_unqualified(a, b), do: erl_abst_def_x_arity_separate_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> erl_abst_def_x_arity_separate_snoc(b) # @pipe
  def at_capture(a, b), do: {&:erl_abst_def_x_arity_separate.erl_abst_def_x_arity_separate_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(:erl_abst_def_x_arity_separate, :erl_abst_def_x_arity_separate_snoc, [a, b]) # @apply
  def at_no_arguments(_a, _b), do: :erl_abst_def_x_arity_separate.erl_abst_def_x_arity_separate_snoc # @no_arguments
  def at_arity_1(a, _b), do: :erl_abst_def_x_arity_separate.erl_abst_def_x_arity_separate_snoc(a) # @arity_1
end
