# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XAritySeparateBroken do
  import :erl_abst_def_x_arity_separate

  def at_arity_3(a, b), do: :erl_abst_def_x_arity_separate.erl_abst_def_x_arity_separate_snoc(a, b, a) # @arity_3
end
