# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XAritySeparate.ImportOnly2 do
  import :erl_abst_def_x_arity_separate, only: [erl_abst_def_x_arity_separate_snoc: 1] # @import_only_2_key

  def at_import_only_2(a, b), do: erl_abst_def_x_arity_separate_snoc(a, b) # @import_only_2
end
