# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XAritySeparate.RequireOnly do
  require :erl_abst_def_x_arity_separate

  def at_require_only(a, b), do: erl_abst_def_x_arity_separate_snoc(a, b) # @require_only
end
