# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XLookalikeAbsentBroken do
  import :erl_abst_def_x_lookalike_absent

  def at_arity_1(a, _b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc(a, b, a) # @arity_3
  def at_undeclared(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_undeclared(a, b) # @undeclared
end
