# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Def.XLookalikeAbsent do
  import :erl_abst_def_x_lookalike_absent

  def at_qualified(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc(a, b) # @qualified
  def at_unqualified(a, b), do: erl_abst_def_x_lookalike_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> erl_abst_def_x_lookalike_absent_snoc(b) # @pipe
  def at_capture(a, b), do: {&:erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(:erl_abst_def_x_lookalike_absent, :erl_abst_def_x_lookalike_absent_snoc, [a, b]) # @apply
  def at_lookalike_xsnoc(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_xsnoc(a, b) # @lookalike_xsnoc
  def at_lookalike_snoc_x(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc_x(a, b) # @lookalike_snoc_x
  def at_lookalike_snoc_question(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc?(a, b) # @lookalike_snoc_question
  def at_lookalike_snoc_bang(a, b), do: :erl_abst_def_x_lookalike_absent.erl_abst_def_x_lookalike_absent_snoc!(a, b) # @lookalike_snoc_bang
  def at_lookalike_snoc_combining(a, b), do: :erl_abst_def_x_lookalike_absent."erl_abst_def_x_lookalike_absent_snoć"(a, b) # @lookalike_snoc_combining
end
