# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defdelegate.XAritySeparateUndefined do
  alias ExGen.Defdelegate.XAritySeparate
  alias ExGen.Defdelegate.XAritySeparate, as: Aliased
  import ExGen.Defdelegate.XAritySeparate

  def at_unqualified_arity_3(a, b), do: ex_gen_defdelegate_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
