# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defdelegate.XDefaultsHead.RequireOnly do
  require ExGen.Defdelegate.XDefaultsHead

  def at_require_only(a, b), do: ex_gen_defdelegate_x_defaults_head_snoc(a, b) # @require_only
end
