# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defdelegate.XDefaultsHeadUndefined do
  alias ExGen.Defdelegate.XDefaultsHead
  alias ExGen.Defdelegate.XDefaultsHead, as: Aliased
  import ExGen.Defdelegate.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: ex_gen_defdelegate_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
