# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defdelegate.XDefaults.ImportMacros do
  import ExGen.Defdelegate.XDefaults, only: :macros

  def at_import_macros(a, b), do: ex_gen_defdelegate_x_defaults_snoc(a, b) # @import_macros
end
