# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Defp.W2.ImportFunctions do
  import :erl_abst_defp_w2, only: :functions

  def at_import_functions(a, b), do: erl_abst_defp_w2_snoc(a, b) # @import_functions
end
