# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ErlAbst.Defp.XAritySeparate.ImportWhole do
  import :erl_abst_defp_x_arity_separate

  def at_import_whole(a, b), do: erl_abst_defp_x_arity_separate_snoc(a, b) # @import_whole
end
