# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XAritySeparateUndefined do
  alias Src.Defdelegate.XAritySeparate
  alias Src.Defdelegate.XAritySeparate, as: Aliased
  import Src.Defdelegate.XAritySeparate

  def at_unqualified_arity_3(a, b), do: src_defdelegate_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
