# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XArity do
  alias Src.Defdelegate.XArity
  alias Src.Defdelegate.XArity, as: Aliased
  import Src.Defdelegate.XArity

  def at_qualified(a, b), do: Src.Defdelegate.XArity.src_defdelegate_x_arity_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArity.src_defdelegate_x_arity_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.src_defdelegate_x_arity_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: src_defdelegate_x_arity_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> src_defdelegate_x_arity_snoc(b) # @pipe
  def at_capture(a, b), do: {&Src.Defdelegate.XArity.src_defdelegate_x_arity_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(Src.Defdelegate.XArity, :src_defdelegate_x_arity_snoc, [a, b]) # @apply
  def at_arity_3(a, b), do: Src.Defdelegate.XArity.src_defdelegate_x_arity_snoc(a, b, a) # @arity_3
  def at_unqualified_arity_3(a, b), do: src_defdelegate_x_arity_snoc(a, b, a) # @unqualified_arity_3
end
