# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XDefaultsHeadUndefined do
  alias Src.Defdelegate.XDefaultsHead
  alias Src.Defdelegate.XDefaultsHead, as: Aliased
  import Src.Defdelegate.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: src_defdelegate_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
