# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defdelegate.XNfcBroken do
  alias Src.Defdelegate.XNfc
  alias Src.Defdelegate.XNfc, as: Aliased
  import Src.Defdelegate.XNfc

  def at_arity_1(a, _b), do: Src.Defdelegate.XNfc.src_defdelegate_x_nfc_snoć(a) # @arity_1
end
