# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defp.XDefaults.ImportFunctions do
  import ExGen.Defp.XDefaults, only: :functions

  def at_import_functions(a, b), do: ex_gen_defp_x_defaults_snoc(a, b) # @import_functions
end
