# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defp.XDefaultsHead.ImportWhole do
  import ExGen.Defp.XDefaultsHead

  def at_import_whole(a, b), do: ex_gen_defp_x_defaults_head_snoc(a, b) # @import_whole
end
