# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.EexFunctionFrom.XAritySeparateUndefined do
  alias ExGen.EexFunctionFrom.XAritySeparate
  alias ExGen.EexFunctionFrom.XAritySeparate, as: Aliased
  import ExGen.EexFunctionFrom.XAritySeparate

  def at_unqualified_arity_3(a, b), do: ex_gen_eex_function_from_x_arity_separate_snoc(a, b, a) # @unqualified_arity_3
end
