# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.EexFunctionFrom.XArityAbsentBroken do
  alias ExGen.EexFunctionFrom.XArityAbsent
  alias ExGen.EexFunctionFrom.XArityAbsent, as: Aliased
  import ExGen.EexFunctionFrom.XArityAbsent

  def at_no_arguments(_a, _b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_snoc # @no_arguments
  def at_arity_1(a, _b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_snoc(a) # @arity_1
  def at_arity_3(a, b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_snoc(a, b, a) # @arity_3
  def at_aliased_arity_1(a, _b), do: XArityAbsent.ex_gen_eex_function_from_x_arity_absent_snoc(a) # @aliased_arity_1
  def at_undeclared(a, b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_undeclared(a, b) # @undeclared
  def at_lookalike_prefix(a, b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_sno(a, b) # @lookalike_prefix
  def at_undeclared_no_arguments(_a, _b), do: ExGen.EexFunctionFrom.XArityAbsent.ex_gen_eex_function_from_x_arity_absent_undeclared # @undeclared_no_arguments
  def at_kernel_name(a, _b), do: ExGen.EexFunctionFrom.XArityAbsent.is_nil(a) # @kernel_name
end
