# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.EexFunctionFrom.XArityZeroBroken do
  alias ExGen.EexFunctionFrom.XArityZero
  alias ExGen.EexFunctionFrom.XArityZero, as: Aliased
  import ExGen.EexFunctionFrom.XArityZero

  def at_arity_1(a, _b), do: ExGen.EexFunctionFrom.XArityZero.ex_gen_eex_function_from_x_arity_zero_snoc(a) # @arity_1
end
