# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.DefdelegateAs.XArityAbsentUndefined do
  alias ExGen.DefdelegateAs.XArityAbsent
  alias ExGen.DefdelegateAs.XArityAbsent, as: Aliased
  import ExGen.DefdelegateAs.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_defdelegate_as_x_arity_absent_snoc(a) # @unqualified_arity_1
end
