# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.W1 do
  alias ExDbgi.Defguard.W1
  alias ExDbgi.Defguard.W1, as: Aliased
  require ExDbgi.Defguard.W1
  import ExDbgi.Defguard.W1

  def at_qualified(a, b), do: ExDbgi.Defguard.W1.ex_dbgi_defguard_w1_snoc(a, b) # @qualified
  def at_aliased(a, b), do: W1.ex_dbgi_defguard_w1_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_w1_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_w1_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_w1_snoc(b) # @pipe
end
