# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XArity do
  alias ExDbgi.Defguard.XArity
  alias ExDbgi.Defguard.XArity, as: Aliased
  require ExDbgi.Defguard.XArity
  import ExDbgi.Defguard.XArity

  def at_qualified(a, b), do: ExDbgi.Defguard.XArity.ex_dbgi_defguard_x_arity_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArity.ex_dbgi_defguard_x_arity_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_x_arity_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_x_arity_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_x_arity_snoc(b) # @pipe
  def at_arity_3(a, b), do: ExDbgi.Defguard.XArity.ex_dbgi_defguard_x_arity_snoc(a, b, a) # @arity_3
  def at_unqualified_arity_3(a, b), do: ex_dbgi_defguard_x_arity_snoc(a, b, a) # @unqualified_arity_3
end
