# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XArityAbsent do
  alias ExDbgi.Defguard.XArityAbsent
  alias ExDbgi.Defguard.XArityAbsent, as: Aliased
  require ExDbgi.Defguard.XArityAbsent
  import ExDbgi.Defguard.XArityAbsent

  def at_qualified(a, b), do: ExDbgi.Defguard.XArityAbsent.ex_dbgi_defguard_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.ex_dbgi_defguard_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_x_arity_absent_snoc(b) # @pipe
end
