# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XNfc do
  alias ExDbgi.Defguard.XNfc
  alias ExDbgi.Defguard.XNfc, as: Aliased
  require ExDbgi.Defguard.XNfc
  import ExDbgi.Defguard.XNfc

  def at_qualified(a, b), do: ExDbgi.Defguard.XNfc.ex_dbgi_defguard_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_dbgi_defguard_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_x_nfc_snoć(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_x_nfc_snoć(b) # @pipe
  def at_atom(a, b), do: {:ex_dbgi_defguard_x_nfc_snoć, a, b} # @atom
end
