# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XNfcBroken do
  alias ExDbgi.Defguard.XNfc
  alias ExDbgi.Defguard.XNfc, as: Aliased
  require ExDbgi.Defguard.XNfc
  import ExDbgi.Defguard.XNfc

  def at_arity_1(a, _b), do: ExDbgi.Defguard.XNfc.ex_dbgi_defguard_x_nfc_snoć(a) # @arity_1
end
