# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.Defguard.XOtherModule do
  alias ExDbgi.Defguard.XOtherModule
  alias ExDbgi.Defguard.XOtherModule, as: Aliased
  require ExDbgi.Defguard.XOtherModule
  require ExDbgi.Defguard.XOtherModule.Other
  import ExDbgi.Defguard.XOtherModule

  def at_qualified(a, b), do: ExDbgi.Defguard.XOtherModule.ex_dbgi_defguard_x_other_module_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XOtherModule.ex_dbgi_defguard_x_other_module_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defguard_x_other_module_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defguard_x_other_module_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defguard_x_other_module_snoc(b) # @pipe
  def at_other_qualified(a, b), do: ExDbgi.Defguard.XOtherModule.Other.ex_dbgi_defguard_x_other_module_snoc(a, b) # @other_qualified
end
