# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XArityAbsentUndefined do
  alias ExDbgi.DefdelegateUnresolvable.XArityAbsent
  alias ExDbgi.DefdelegateUnresolvable.XArityAbsent, as: Aliased
  import ExDbgi.DefdelegateUnresolvable.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_dbgi_defdelegate_unresolvable_x_arity_absent_snoc(a) # @unqualified_arity_1
end
