# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XAritySeparate do
  alias ExDbgi.DefdelegateUnresolvable.XAritySeparate
  alias ExDbgi.DefdelegateUnresolvable.XAritySeparate, as: Aliased
  import ExDbgi.DefdelegateUnresolvable.XAritySeparate

  def at_qualified(a, b), do: ExDbgi.DefdelegateUnresolvable.XAritySeparate.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XAritySeparate.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExDbgi.DefdelegateUnresolvable.XAritySeparate.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExDbgi.DefdelegateUnresolvable.XAritySeparate, :ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc, [a, b]) # @apply
  def at_no_arguments(_a, _b), do: ExDbgi.DefdelegateUnresolvable.XAritySeparate.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc # @no_arguments
  def at_arity_1(a, _b), do: ExDbgi.DefdelegateUnresolvable.XAritySeparate.ex_dbgi_defdelegate_unresolvable_x_arity_separate_snoc(a) # @arity_1
end
