# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XArityZeroBroken do
  alias ExDbgi.DefdelegateUnresolvable.XArityZero
  alias ExDbgi.DefdelegateUnresolvable.XArityZero, as: Aliased
  import ExDbgi.DefdelegateUnresolvable.XArityZero

  def at_arity_1(a, _b), do: ExDbgi.DefdelegateUnresolvable.XArityZero.ex_dbgi_defdelegate_unresolvable_x_arity_zero_snoc(a) # @arity_1
end
