# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XDefaultsHeadUndefined do
  alias ExDbgi.DefdelegateUnresolvable.XDefaultsHead
  alias ExDbgi.DefdelegateUnresolvable.XDefaultsHead, as: Aliased
  import ExDbgi.DefdelegateUnresolvable.XDefaultsHead

  def at_unqualified_arity_3(a, b), do: ex_dbgi_defdelegate_unresolvable_x_defaults_head_snoc(a, b, a) # @unqualified_arity_3
end
