# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDbgi.DefdelegateUnresolvable.XDefaults.ImportFunctions do
  import ExDbgi.DefdelegateUnresolvable.XDefaults, only: :functions

  def at_import_functions(a, b), do: ex_dbgi_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_functions
end

defmodule Callers.ExDbgi.DefdelegateUnresolvable.XDefaults.ImportOnly do
  import ExDbgi.DefdelegateUnresolvable.XDefaults, only: [ex_dbgi_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_dbgi_defdelegate_unresolvable_x_defaults_snoc(a) # @import_only_1
end

defmodule Callers.ExDbgi.DefdelegateUnresolvable.XDefaults.ImportExcept do
  import ExDbgi.DefdelegateUnresolvable.XDefaults, except: [ex_dbgi_defdelegate_unresolvable_x_defaults_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_dbgi_defdelegate_unresolvable_x_defaults_snoc(a, b) # @import_except_2
end
