# Generates the code intelligence matrix's fixtures: for every backing, declaration form and world, the declaring
# sources, a caller of them, the compiled `.beam`s where the backing is compiled, and `oracle.json`, which says for
# each marked site which definition the compiler bound it to. Every compiled backing is built from the same world as
# its source, so every backing is asked the same question.
#
# Run from this directory: `mise exec -- elixir generate.exs`. Elixir is needed only here, never by the tests.

defmodule Matrix.Events do
  use Agent

  def start_link, do: Agent.start_link(fn -> [] end, name: __MODULE__)
  def add(event), do: Agent.update(__MODULE__, &[event | &1])
  def take, do: Agent.get_and_update(__MODULE__, &{Enum.reverse(&1), []})
end

defmodule Matrix.Tracer do
  @kinds [:remote_function, :imported_function, :remote_macro, :imported_macro]

  def trace({kind, meta, module, name, arity}, env) when kind in @kinds do
    Matrix.Events.add(%{file: env.file, line: meta[:line], module: module, name: name, arity: arity, kind: kind})
  end

  def trace({kind, meta, name, arity}, env) when kind in [:local_function, :local_macro] do
    Matrix.Events.add(%{file: env.file, line: meta[:line], module: env.module, name: name, arity: arity, kind: kind})
  end

  def trace(_event, _env), do: :ok
end

defmodule Matrix do
  @header "Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in " <>
            "testData/org/elixir_lang/code_insight/code_intelligence_matrix."

  # Everything this script owns: wiped before a run and hashed into `manifest.json` after it, so the two can never
  # disagree about what a fixture is.
  @generated_directories ["lib", "spec", "_build", "provenance"]

  # `c` followed by U+0301 COMBINING ACUTE ACCENT: Elixir normalises it to `ć` (U+0107) in identifiers, Erlang does not.
  @decomposed "snoć"
  @precomposed "snoć"

  # `strip` lists the chunks removed from the compiled module, which decides the decompiler's clause source.
  def backings do
    [
      %{id: "src", language: :elixir, prefix: "Src", compiled: false},
      %{id: "ex_dbgi", language: :elixir, prefix: "ExDbgi", compiled: true, strip: [], clause_source: "ElixirDebugInfo"},
      %{id: "ex_docs", language: :elixir, prefix: "ExDocs", compiled: true, strip: [~c"Dbgi"], clause_source: "DocsSignatures"},
      %{id: "ex_gen", language: :elixir, prefix: "ExGen", compiled: true, strip: [~c"Dbgi", ~c"Docs"], clause_source: "Generated"},
      %{id: "erl_abst", language: :erlang, prefix: "erl_abst", compiled: true, debug_info: true, strip: [~c"Docs"], clause_source: "ErlangAbstractCode"},
      %{id: "erl_gen", language: :erlang, prefix: "erl_gen", compiled: true, debug_info: false, strip: [~c"Docs"], clause_source: "Generated"}
    ]
  end

  # The backing a `defdelegate_compiled` target is compiled in, whatever the delegator's backing.
  @delegate_target_backing %{id: "delegate_targets", language: :elixir, prefix: "Target", compiled: true, strip: [], clause_source: "ElixirDebugInfo"}

  # `delegate` is where a delegate's target lives: beside it in the same backing, compiled, or nowhere.
  def forms do
    [
      %{id: "def", definer: "def"},
      %{id: "defp", definer: "defp", private: true},
      %{id: "defmacro", definer: "defmacro", macro: true},
      %{id: "defmacrop", definer: "defmacrop", macro: true, private: true},
      %{id: "defguard", definer: "defguard", macro: true, guard: true},
      %{id: "defguardp", definer: "defguardp", macro: true, guard: true, private: true},
      %{id: "defdelegate", definer: "defdelegate", delegate: :same},
      %{id: "defdelegate_compiled", definer: "defdelegate", delegate: :compiled},
      %{id: "defdelegate_unresolvable", definer: "defdelegate", delegate: :missing}
    ]
  end

  # A world is its modules' definitions and the calls made to them. A definition is `{name, clauses}`; a clause is
  # `{parameters, guard}`, where a parameter is a name or `{name, default}` and a guard is `{function, parameter}`.
  # A call is `{site id, module (0 for the main one), name, arity, shape}`, and `shape` decides how it is written.
  def worlds do
    snoc_2 = {"snoc", [{["q", "x"], nil}]}
    many = [{"snoc", [{["q", "x"], {"is_list", "q"}}, {["queue", "item"], nil}]}, {"snoc", [{["q"], nil}]}, {"snoc", [{["q", "x", "y"], nil}]}]
    lookalikes = for name <- ["xsnoc", "snoc_x", "snoc?", "snoc!", @decomposed], do: {name, [{["q", "x"], nil}]}
    one_calls = calls_to(0, "snoc", 2)
    many_calls = one_calls ++ [{"second_qualified", 0, "snoc", 2, :qualified}, {"arity_1", 0, "snoc", 1, :qualified}, {"arity_3", 0, "snoc", 3, :qualified}]

    # `snoc/0`, `snoc/1` and `snoc/2` from one definition with defaults, and from three separate ones. The callers
    # are identical, so any feature answering the same for both is only right by accident.
    defaults_head =
      {"snoc",
       [
         {[{"a", "nil"}, {"b", "nil"}], nil, :head},
         {["a", "b"], {"is_nil", "a"}},
         {["a", "b"], nil}
       ]}

    separate = [{"snoc", [{[], nil}]}, {"snoc", [{["a"], nil}]}, {"snoc", [{["a", "b"], nil}]}]

    spread_calls =
      one_calls ++
        [
          {"no_arguments", 0, "snoc", 0, :no_arguments},
          {"arity_1", 0, "snoc", 1, :qualified},
          {"arity_3", 0, "snoc", 3, :qualified},
          {"unqualified_arity_3", 0, "snoc", 3, :unqualified}
        ]

    lookalike_calls =
      for {id, name} <- [{"xsnoc", "xsnoc"}, {"snoc_x", "snoc_x"}, {"snoc_question", "snoc?"}, {"snoc_bang", "snoc!"}, {"snoc_combining", @decomposed}],
          do: {"lookalike_" <> id, 0, name, 2, :qualified}

    %{
      "w1" => %{modules: [[snoc_2]], calls: one_calls},
      "w2" => %{modules: [many], calls: many_calls},
      "w3" => %{modules: [[snoc_2 | lookalikes]], calls: one_calls ++ lookalike_calls},
      "w4" => %{modules: [many ++ lookalikes], calls: many_calls ++ lookalike_calls},
      "x_arity" => %{modules: [[snoc_2, {"snoc", [{["q", "x", "y"], nil}]}]], calls: one_calls ++ [{"arity_3", 0, "snoc", 3, :qualified}, {"unqualified_arity_3", 0, "snoc", 3, :unqualified}]},
      "x_other_module" => %{modules: [[snoc_2], [snoc_2]], calls: one_calls ++ [{"other_qualified", 1, "snoc", 2, :qualified}]},
      "x_not_a_call" => %{modules: [[snoc_2]], calls: one_calls ++ [{"variable", 0, "snoc", 0, :variable}, {"atom", 0, "snoc", 0, :atom}, {"keyword", 0, "snoc", 0, :keyword}]},
      "x_defaults" => %{modules: [[{"snoc", [{["q", {"x", "nil"}], nil}]}]], calls: one_calls ++ [{"default_arity", 0, "snoc", 1, :qualified}]},
      # Only `snoc/2` exists, so a call at any other arity has exactly one candidate and none of them match it.
      "x_arity_absent" => %{
        modules: [[snoc_2]],
        calls:
          one_calls ++
            [
              {"no_arguments", 0, "snoc", 0, :no_arguments},
              {"arity_1", 0, "snoc", 1, :qualified},
              {"arity_3", 0, "snoc", 3, :qualified},
              {"aliased_arity_1", 0, "snoc", 1, :aliased},
              {"unqualified_arity_1", 0, "snoc", 1, :unqualified},
              # A name no module declares at any arity, so that "the arity is wrong" has a control to be told apart
              # from "there is no such function". Without it a three-valued diagnostic assertion has an unreachable
              # value, and a plugin that answers "does not resolve to anything" to both looks correct about one of
              # them. It sits in this world because the contrast is then inside one file: the same caller holds
              # `snoc` at arities the module does not define and a name it never heard of.
              {"undeclared", 0, "undeclared", 2, :qualified},
              {"undeclared_no_arguments", 0, "undeclared", 0, :no_arguments}
            ]
      },
      # `snoc/0` genuinely exists, so `M.snoc` is correct rather than a mistake, and `M.snoc(a)` has two candidates
      # and matches neither. Without this world nothing can tell a resolver that respects arity from one that does not.
      "x_arity_zero" => %{
        modules: [[{"snoc", [{[], nil}]}, snoc_2]],
        calls:
          one_calls ++
            [
              {"no_arguments", 0, "snoc", 0, :no_arguments},
              {"arity_1", 0, "snoc", 1, :qualified},
              {"unqualified_arity_1", 0, "snoc", 1, :unqualified}
            ]
      },
      "x_defaults_head" => %{modules: [[defaults_head]], calls: spread_calls},
      "x_arity_separate" => %{modules: [separate], calls: spread_calls},
      "x_nfc" => %{
        modules: [[{@decomposed, [{["q", "x"], nil}]}]],
        calls: [
          {"qualified", 0, @precomposed, 2, :qualified},
          {"aliased", 0, @precomposed, 2, :aliased},
          {"aliased_as", 0, @precomposed, 2, :aliased_as},
          {"unqualified", 0, @precomposed, 2, :unqualified}
        ]
      }
    }
  end

  defp calls_to(module, name, arity) do
    for shape <- [:qualified, :aliased, :aliased_as, :unqualified, :pipe, :capture, :apply],
        do: {to_string(shape), module, name, arity, shape}
  end

  # Which (backing, form, world) cannot exist, and why; the generator skips them and records the reason.
  # Stripping the Docs chunk leaves nothing to say the beam is Erlang, so `clauseSource` falls back to
  # `beamLanguage = "elixir"` and picks the same decompiler `ex_gen` gets. Measured over 1,090 comparable cells,
  # the two never once disagreed - not coincidence but the same code. One scenario is kept so the fallback itself
  # can be pinned by a guard; asking the features again would cost seconds and red cells to learn nothing.
  def not_applicable(%{id: "erl_gen"}, form, world) when form.id != "def" or world != "w1",
    do: "erl_gen runs the same decompiler as ex_gen; one scenario is kept only to pin that fallback"

  def not_applicable(%{language: :erlang}, form, _world) when form.id not in ["def", "defp"], do: "Erlang has only functions"
  def not_applicable(%{language: :erlang}, _form, world) when world in ["x_defaults", "x_defaults_head"],
    do: "Erlang has no default arguments"

  def not_applicable(%{language: :erlang}, _form, "x_nfc"), do: "Erlang does not normalise the declared name, so a precomposed call cannot reach it"

  def not_applicable(%{compiled: true}, %{macro: true, private: true}, _world),
    do: "a private macro is expanded away at compile time, so the .beam has no definition of it"

  def not_applicable(%{compiled: true}, %{delegate: :compiled}, _world), do: "a compiled delegator's target is compiled either way"
  def not_applicable(_backing, %{guard: true}, world) when world in ["x_defaults", "x_defaults_head"],
    do: "a guard cannot have default arguments"

  def not_applicable(_backing, %{guard: true}, world) when world in ["x_arity_zero", "x_arity_separate"],
    do: "a guard takes at least one argument, so it cannot define the zero-arity clause this world is about"
  def not_applicable(_backing, %{private: true}, world) when world in ["x_other_module", "x_not_a_call"],
    do: "a private definition cannot be called from outside, so the world adds no site"

  def not_applicable(_backing, _form, _world), do: nil

  def run do
    {:ok, _} = Matrix.Events.start_link()
    Code.put_compiler_option(:tracers, [Matrix.Tracer])
    Code.put_compiler_option(:parser_options, columns: true)

    # The tree is laid out as a Mix project so it can be opened in a sandbox IDE and used by `testUI`: `lib` is what
    # Mix compiles, `_build` is where it expects a dependency's beams, and `spec` holds what is neither - the Erlang
    # sources and the Elixir renderings of them the tests quote.
    for dir <- @generated_directories, do: File.rm_rf!(dir)

    provenance()

    {scenarios, skipped} =
      for backing <- backings(), form <- forms(), {world, spec} <- Enum.sort(worlds()), reduce: {[], []} do
        {scenarios, skipped} ->
          case not_applicable(backing, form, world) do
            nil -> {[scenario(backing, form, world, spec) | scenarios], skipped}
            reason -> {scenarios, [%{"backing" => backing.id, "form" => form.id, "world" => world, "reason" => reason} | skipped]}
          end
      end

    # Which call binds to which definition is the compiler's answer, recorded here rather than asked again at test
    # time, so the pair that answered is part of the oracle: a committed answer from another Elixir is not evidence.
    oracle = %{
      "header" => @header,
      "elixir" => System.version(),
      "otp" => List.to_string(:erlang.system_info(:otp_release)),
      "scenarios" => Enum.reverse(scenarios),
      "notApplicable" => Enum.reverse(skipped)
    }

    File.write!("oracle.json", [:json.format(json(oracle)), ?\n])
    File.write!("manifest.json", [:json.format(manifest(Enum.reverse(scenarios))), ?\n])
  end

  defp json(nil), do: :null
  defp json(map) when is_map(map), do: Map.new(map, fn {key, value} -> {key, json(value)} end)
  defp json(list) when is_list(list), do: Enum.map(list, &json/1)
  defp json(other), do: other

  defp scenario(backing, form, world, spec) do
    spec = scope(spec, backing, form, world)
    names = module_names(backing, form, world, length(spec.modules))
    worlds_modules = Enum.map(spec.modules, &shape(&1, form))
    primary = worlds_modules |> hd() |> hd()

    modules =
      worlds_modules
      |> Enum.zip(names)
      |> Enum.with_index()
      |> Enum.flat_map(fn {{definitions, module}, index} ->
        compile_module(backing, form, world, module, definitions, if(index == 0, do: primary))
      end)

    calls =
      cond do
        form[:private] ->
          []

        true ->
          Enum.reject(spec.calls, fn {_, _, _, _, shape} ->
            (form[:macro] && shape in [:capture, :apply]) ||
              (backing.language == :erlang && shape in [:aliased, :aliased_as])
          end)
      end
    # A call at an arity nothing defines cannot share a file with the rest: made locally it is a compile error, so
    # it would take the whole module down with it. It gets its own caller, compiled expecting to fail, and what the
    # compiler says about it is the oracle for what the IDE should say.
    {calls, broken} = Enum.split_with(calls, &defined?(&1, worlds_modules))

    caller_path = Path.join(["lib", "callers", backing.id, form.id, Macro.underscore(world) <> ".ex"])
    caller = render_caller(backing, form, world, names, calls)
    File.mkdir_p!(Path.dirname(caller_path))
    File.write!(caller_path, caller)
    caller_events = compile_elixir(caller_path, caller)

    {broken_paths, broken_sites} = broken_caller(backing, form, world, names, broken)

    %{
      "backing" => backing.id,
      "form" => form.id,
      "world" => world,
      "caller" => caller_path,
      "brokenCallers" => broken_paths,
      "modules" => Enum.map(modules, &Map.delete(&1, :local)),
      "sites" =>
        caller_sites(caller_path, caller, caller_events, calls, backing, names) ++
          Enum.flat_map(modules, & &1.local) ++ broken_sites
    }
  end

  # The shapes that are not calls of the definition at all, so no arity can be wrong for them.
  @not_calls [:variable, :atom, :keyword]

  defp defined?({_id, _module, _name, _arity, shape}, _modules) when shape in @not_calls, do: true

  defp defined?({_id, module, name, arity, _shape}, modules) do
    modules
    |> Enum.at(module, [])
    |> Enum.any?(fn {definition_name, [first | _]} ->
      {parameters, _guard, _head?} = clause_parts(first)
      defaults = Enum.count(parameters, &is_tuple/1)
      # Elixir normalises identifiers, so a decomposed declaration and a precomposed call are the same function.
      nfc(definition_name) == nfc(name) and arity in (length(parameters) - defaults)..length(parameters)
    end)
  end

  # Calling an undefined function locally is a compile error and takes the whole module with it, so the remote calls
  # in the same file would never reach the warning that names them. The two kinds get a file each.
  @imported_shapes [:unqualified, :pipe]

  defp broken_caller(backing, form, world, names, calls) do
    {imported, remote} = Enum.split_with(calls, fn {_, _, _, _, shape} -> shape in @imported_shapes end)

    [{remote_path, remote_sites}, {imported_path, imported_sites}] =
      [{remote, "_broken"}, {imported, "_undefined"}]
      |> Enum.map(fn {subset, suffix} -> broken_caller_file(backing, form, world, names, subset, suffix) end)

    {Enum.reject([remote_path, imported_path], &is_nil/1), remote_sites ++ imported_sites}
  end

  defp broken_caller_file(_backing, _form, _world, _names, [], _suffix), do: {nil, []}

  defp broken_caller_file(backing, form, world, names, calls, suffix) do
    path = Path.join(["lib", "callers", backing.id, form.id, Macro.underscore(world) <> suffix <> ".ex"])
    source = render_caller(backing, form, world <> suffix, names, calls)
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, source)

    diagnostics = compile_expecting_failure(path, source)
    {path, broken_sites(path, source, calls, diagnostics)}
  end

  # Nothing here is expected to compile, and a local call at an unknown arity is a hard error rather than a warning,
  # so the module may not be produced at all. Only what the compiler said is kept.
  defp compile_expecting_failure(path, source) do
    Matrix.Events.take()

    {_result, diagnostics} =
      Code.with_diagnostics(fn ->
        try do
          Code.compile_string(source, path)
        rescue
          _ -> :error
        end
      end)

    Matrix.Events.take()

    if diagnostics == [], do: raise("#{path} was expected to be rejected by the compiler, and was not")

    diagnostics
  end

  defp broken_sites(path, source, calls, diagnostics) do
    lines = source |> String.split("\n") |> Enum.with_index(1)

    Enum.map(calls, fn {id, _module, name, arity, _shape} ->
      {text, line} = Enum.find(lines, fn {text, _} -> String.ends_with?(text, "# @#{id}") end)
      said = Enum.find(diagnostics, fn diagnostic -> position_line(diagnostic.position) == line end)

      # A site in a file the compiler rejected, with nothing said about its own line, would be committed as a call
      # the compiler was happy with - and the matrix would then assert the IDE must say nothing about it, the exact
      # inverse of what this file exists to test. It happens when the compiler reports at another line, or aborts on
      # an earlier hard error before reaching this call, so the fix is a caller with fewer calls per file.
      if is_nil(said) do
        raise "#{path}:#{line} (@#{id}) is in a file the compiler rejected, but no diagnostic names that line; " <>
                "split the call into its own file so the compiler reaches it"
      end

      %{
        "id" => id,
        "file" => path,
        "line" => line,
        "column" => name_column(text, name),
        "name" => nfc(name),
        "arity" => arity,
        "binding" => nil,
        "diagnostic" => %{"severity" => to_string(said.severity), "message" => said.message}
      }
    end)
  end

  defp position_line({line, _column}), do: line
  defp position_line(line) when is_integer(line), do: line
  defp position_line(_), do: nil

  # Every scenario shares one project, so a function name has to name its scenario. Searching for a bare `snoc`
  # would return every scenario's files and discard all but one, and the search-driven features - Find Usages and
  # Rename, already the most expensive - would pay for it. Module names already carry the scenario (`Src.Def.W1`),
  # so only function names need this. `local_site`, `uses` and `target_marker` are never search targets, so they
  # keep their bare names.
  defp scope(spec, backing, form, world) do
    prefix = "#{backing.id}_#{form.id}_#{world}_"

    %{
      spec
      | modules:
          Enum.map(spec.modules, fn definitions ->
            Enum.map(definitions, fn {name, clauses} -> {prefix <> name, clauses} end)
          end),
        calls: Enum.map(spec.calls, fn {id, module, name, arity, shape} -> {id, module, prefix <> name, arity, shape} end)
    }
  end

  # A clause is `{parameters, guard}`, or `{parameters, guard, :head}` for the bodiless head Elixir requires when
  # several clauses of one definition share default arguments. Nothing else may carry defaults in that case.
  defp clause_parts({parameters, guard}), do: {parameters, guard, false}
  defp clause_parts({parameters, guard, :head}), do: {parameters, guard, true}

  defp head?(clause), do: clause_parts(clause) |> elem(2)

  # A guard or a delegate has one clause per name and arity, no guard of its own, and so never a separate head.
  defp shape(definitions, form) do
    if form[:guard] || form[:delegate] do
      Enum.map(definitions, fn {name, [clause | _]} ->
        {parameters, _guard, _head?} = clause_parts(clause)
        {name, [{parameters, nil}]}
      end)
    else
      definitions
    end
  end

  defp module_names(%{language: :elixir, prefix: prefix}, form, world, count) do
    main = "#{prefix}.#{Macro.camelize(form.id)}.#{Macro.camelize(world)}"
    [main | Enum.map(1..(count - 1)//1, fn _ -> main <> ".Other" end)]
  end

  defp module_names(%{language: :erlang, prefix: prefix}, form, world, count) do
    main = "#{prefix}_#{form.id}_#{world}"
    [main | Enum.map(1..(count - 1)//1, fn _ -> main <> "_other" end)]
  end

  defp reference(%{language: :elixir}, module), do: module
  defp reference(%{language: :erlang}, module), do: ":" <> module

  # The declaring module, and for a delegate whose target exists, the target module compiled before it.
  defp compile_module(backing, form, world, module, definitions, primary) do
    {target, targets} =
      case form[:delegate] do
        nil -> {nil, []}
        :missing -> {module <> ".Missing", []}
        :same -> {module <> ".Target", [compile_one(backing, %{id: "def", definer: "def"}, world, module <> ".Target", strip_defaults(definitions), nil, nil)]}
        :compiled -> {module <> ".Target", [compile_one(@delegate_target_backing, %{id: "def", definer: "def"}, world, module <> ".Target", strip_defaults(definitions), nil, nil)]}
      end

    [compile_one(backing, form, world, module, definitions, primary, target) | targets]
  end

  # A delegate target takes the same arities without the defaults, so a bodiless head has nothing left to declare.
  defp strip_defaults(definitions) do
    Enum.map(definitions, fn {name, clauses} ->
      bare =
        clauses
        |> Enum.reject(&head?/1)
        |> Enum.map(fn clause ->
          {parameters, guard, _head?} = clause_parts(clause)
          {Enum.map(parameters, fn {parameter, _} -> parameter; parameter -> parameter end), guard}
        end)

      {name, bare}
    end)
  end

  defp compile_one(backing, form, _world, module, definitions, primary, target) do
    extension = if(backing.language == :elixir, do: ".ex", else: ".erl")
    # Named after the whole module: every world's delegate target is a `Target`.
    file = if(backing.language == :elixir, do: module |> Macro.underscore() |> String.replace("/", "."), else: module)
    # Erlang sources sit outside `lib`, which is Mix's to compile and holds Elixir only.
    root = if(backing.language == :elixir, do: "lib", else: "spec")
    path = Path.join([root, backing.id, file <> extension])
    source = render_source(backing, form, module, definitions, primary, target)
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, source)

    {beam, events} = compile_source(backing, module, path, source)

    spec =
      if backing.language == :erlang do
        spec_path = path <> ".ex.spec"
        File.write!(spec_path, render_elixir(form, ":" <> module, definitions, nil, nil))
        spec_path
      else
        path
      end

    local = if primary, do: local_sites(path, source, events, backing, module, primary), else: []

    %{
      "module" => reference(backing, module),
      "source" => path,
      "spec" => spec,
      "heads" => artefact_heads(heads(spec), beam),
      "complete" => complete?(beam),
      "beam" => beam,
      "clauseSource" => Map.get(backing, :clause_source),
      "delegateTo" => target,
      "definitions" => Enum.map(definitions, &definition/1),
      "declarations" => if(backing.language == :elixir, do: declarations(source), else: []),
      local: local
    }
  end

  # The arities come from the first clause, which is the bodiless head where there is one, because that is where the
  # defaults are declared. A head is not itself a clause, so it is not counted as one.
  defp definition({name, [first | _] = clauses}) do
    {parameters, _guard, _head?} = clause_parts(first)
    defaults = Enum.count(parameters, &is_tuple/1)
    bodied = Enum.reject(clauses, &head?/1)

    %{
      "name" => nfc(name),
      "minArity" => length(parameters) - defaults,
      "maxArity" => length(parameters),
      "clauses" => length(bodied)
    }
  end

  # The oldest pair CI supports, from `.github/ci-versions.json`'s `beam.additional`.
  @oldest_elixir "1.11.4-otp-24"
  @oldest_otp "24.3.4.6"

  @doc """
  One module compiled by the oldest Elixir CI supports as well as by the pinned one.

  Measured before building it: what the decompiler reads - definitions, their kinds, parameter names, clause counts
  and the docs metadata carrying `defaults` and `delegate_to` - is byte-identical across 1.11.4 and 1.20.4 for every
  construct this matrix uses. The versions differ only in `Dbgi` map keys the plugin never reads (`line` became
  `anno`, `is_behaviour` became `defines_behaviour`). So provenance is a guard, not a backing: a whole axis would
  have cost thousands of cells that cannot disagree. What the guard still catches is a reader tuned for modern beams
  that stops reading old dependencies - a plausible outcome of the migration this matrix exists to protect.
  """
  def provenance do
    File.mkdir_p!("provenance")
    source = Path.join("provenance", "provenance.ex")
    File.write!(source, provenance_source())

    for {elixir, otp} <- [{@oldest_elixir, @oldest_otp}, {System.version(), nil}] do
      directory = Path.join("provenance", elixir |> String.split("-") |> hd())
      File.mkdir_p!(directory)
      compile_provenance(source, directory, elixir, otp)
    end
  end

  # The pinned Elixir is this script's own; anything else needs mise to put it on PATH.
  defp compile_provenance(source, directory, _elixir, nil) do
    for {module, binary} <- Code.compile_file(source) do
      File.write!(Path.join(directory, "#{module}.beam"), binary)
    end
  end

  defp compile_provenance(source, directory, elixir, otp) do
    {output, _status} =
      System.cmd("mise", ["exec", "elixir@#{elixir}", "erlang@#{otp}", "--", "elixirc", "-o", directory, source],
        stderr_to_stdout: true
      )

    # `mise exec` reports success even when the command it ran failed, so the beam itself is the evidence.
    if Path.wildcard(Path.join(directory, "*.beam")) == [],
      do: raise("compiling #{source} with Elixir #{elixir} produced no beam:\n#{output}")
  end

  defp provenance_source do
    """
    # #{@header}
    defmodule Provenance.Target do
      def snoc(q, x), do: {q, x}
    end

    defmodule Provenance do
      @doc "Appends x to q."
      def defaulted(a \\\\ nil, b \\\\ nil)
      def defaulted(a, b) when is_nil(a), do: {a, b}
      def defaulted(a, b), do: {a, b}

      def guarded(q, x) when is_list(q), do: {q, x}

      defmacro maked(a, b), do: quote(do: {unquote(a), unquote(b)})

      defdelegate delegated(q, x), to: Provenance.Target, as: :snoc

      # Precomposed, not decomposed: 1.11.4 rejects an unquoted identifier that is not already in NFC form, where
      # 1.20.4 accepts it and normalises. The matrix's own NFC world covers that difference on the pinned Elixir.
      def #{@precomposed}(q, x), do: {q, x}

      defp hidden(q), do: q
      def uses_hidden(q), do: hidden(q)
    end
    """
  end

  @definers [:def, :defp, :defmacro, :defmacrop, :defguard, :defguardp, :defdelegate]

  # The clause heads a feature should describe, read from real Elixir's parse of the declaring source. Taken here
  # rather than by quoting at test time so the tests ask the language nothing: the expectations are committed, the
  # pair that produced them is stamped, and the suite is then the same on every CI leg because nothing in it can
  # vary with the Elixir the leg happens to configure.
  defp heads(path) do
    {_ast, heads} =
      path
      |> File.read!()
      |> Code.string_to_quoted!()
      |> Macro.prewalk([], fn
        {definer, _, [head | _]} = node, acc when definer in @definers -> {node, [head(definer, head) | acc]}
        node, acc -> {node, acc}
      end)

    heads |> Enum.reverse() |> Enum.reject(&is_nil/1)
  end

  # What a reader of the compiled artefact can honestly say about a definition, measured from the artefact rather
  # than declared. Debug info carries every clause as the author wrote it. A `Docs` chunk carries one signature per
  # definition - the author's parameter names, the defaults, and metadata saying whether it was a guard or a
  # delegate - but not the guard expression and not the other clauses; and a private function has no entry there at
  # all, so it falls through to the tables below. With neither chunk only the export and local tables survive: a
  # name, an arity, and a `MACRO-` prefix for a macro. Nothing in them records what a parameter was called, so the
  # expected parameter is `_`, which is how Elixir itself writes an argument that has no name. Rendering anything
  # else - `p0` included - would be the IDE inventing a name the author never chose, which is the one answer a
  # developer cannot act on.
  # Whether what the reader has is everything the author wrote: the source itself, or a beam that still carries its
  # debug info. False means something is gone for good - the guard, the other clauses, sometimes the parameter
  # names - and the reader owes the developer a word about it rather than quietly showing less.
  defp complete?(nil), do: true
  defp complete?(beam), do: beam |> File.read!() |> debug_info?()

  defp artefact_heads(heads, nil), do: heads

  defp artefact_heads(heads, beam) do
    binary = File.read!(beam)

    if debug_info?(binary) do
      heads
    else
      documented = documented_names(binary)
      {signatured, unnamed} = Enum.split_with(heads, &MapSet.member?(documented, &1["name"]))

      signatured
      |> Enum.uniq_by(&{&1["name"], length(&1["parameters"])})
      |> Enum.map(&%{&1 | "guard" => nil})
      |> Enum.concat(exported_heads(binary, unnamed))
    end
  end

  # Asked by making the backend produce the forms, not by looking for the chunk. A beam compiled without debug
  # info can still carry a `Dbgi` chunk that holds none - every Erlang beam here does - so the chunk's presence
  # says nothing, and the shape of what is inside it is the backend's business rather than this generator's.
  defp debug_info?(binary) do
    case :beam_lib.chunks(binary, [:debug_info]) do
      {:ok, {module, [debug_info: {:debug_info_v1, backend, data}]}} ->
        match?({:ok, _forms}, backend.debug_info(:erlang_v1, module, data, []))

      _ ->
        false
    end
  end

  defp documented_names(binary) do
    case :beam_lib.chunks(binary, [~c"Docs"], [:allow_missing_chunks]) do
      {:ok, {_module, [{~c"Docs", docs}]}} when is_binary(docs) ->
        {_tag, _anno, _language, _format, _module_doc, _metadata, entries} = :erlang.binary_to_term(docs)

        MapSet.new(entries, fn entry -> entry |> elem(0) |> elem(1) |> to_string() |> nfc() end)

      _ ->
        MapSet.new()
    end
  end

  # The export and local tables, as clause heads. A macro is exported under a `MACRO-` prefix and one arity higher,
  # for the caller's environment; a private function is local rather than exported. Nothing else about the
  # definition survives here, so nothing else is claimed.
  defp exported_heads(_binary, []), do: []

  defp exported_heads(binary, heads) do
    names = MapSet.new(heads, & &1["name"])
    {:ok, {_module, [exports: exports]}} = :beam_lib.chunks(binary, [:exports])
    {:ok, {_module, [locals: locals]}} = :beam_lib.chunks(binary, [:locals])

    (Enum.map(exports, &{&1, false}) ++ Enum.map(locals, &{&1, true}))
    |> Enum.map(fn {{name, arity}, private} -> exported_head(to_string(name), arity, private) end)
    |> Enum.filter(&MapSet.member?(names, &1["name"]))
    |> Enum.sort_by(&{&1["name"], length(&1["parameters"])})
  end

  defp exported_head("MACRO-" <> name, arity, private),
    do: unnamed_head(name, arity - 1, if(private, do: "defmacrop", else: "defmacro"))

  defp exported_head(name, arity, private),
    do: unnamed_head(name, arity, if(private, do: "defp", else: "def"))

  defp unnamed_head(name, arity, definer) do
    %{
      "definer" => definer,
      "name" => nfc(name),
      "parameters" => List.duplicate("_", arity),
      "defaults" => 0,
      "guard" => nil
    }
  end

  defp head(definer, {:when, _, [call, guard]}), do: head(definer, call, guard_string(guard))
  defp head(definer, call), do: head(definer, call, nil)

  defp head(definer, {name, _, arguments}, guard) when is_atom(name) and is_list(arguments) do
    parameters = Enum.map(arguments, &parameter/1)

    %{
      "definer" => to_string(definer),
      "name" => nfc(to_string(name)),
      "parameters" => parameters,
      "defaults" => Enum.count(parameters, &String.contains?(&1, " \\\\ ")),
      "guard" => guard
    }
  end

  defp head(_definer, _call, _guard), do: nil

  defp parameter({:\\, _, [variable, default]}), do: "#{parameter(variable)} \\\\ #{Macro.to_string(default)}"
  defp parameter({name, _, context}) when is_atom(name) and is_atom(context), do: to_string(name)
  defp parameter(other), do: Macro.to_string(other)

  # A guard as the scenarios write it: a local call on variables, such as `is_list(q)`.
  defp guard_string({name, _, arguments}) when is_atom(name) and is_list(arguments),
    do: "#{name}(#{Enum.map_join(arguments, ", ", &guard_string/1)})"

  defp guard_string({name, _, context}) when is_atom(name) and is_atom(context), do: to_string(name)
  defp guard_string(other), do: Macro.to_string(other)

  defp nfc(name), do: :unicode.characters_to_nfc_binary(name)

  defp render_source(%{language: :elixir}, form, module, definitions, primary, target),
    do: render_elixir(form, module, definitions, primary, target)

  defp render_source(%{language: :erlang}, form, module, definitions, primary, _target) do
    uses = if form[:private], do: private_uses(definitions, primary, :erlang), else: nil

    exports =
      definitions
      |> Enum.reject(fn _ -> form[:private] end)
      |> Enum.map(fn {name, [{parameters, _} | _]} -> "#{erlang_atom(name)}/#{length(parameters)}" end)
      |> Enum.uniq()
      |> Kernel.++(if primary, do: ["local_site/2"], else: [])
      |> Kernel.++(if uses, do: ["uses/2"], else: [])
      |> Enum.join(", ")

    functions =
      definitions
      |> Enum.group_by(fn {name, [{parameters, _} | _]} -> {name, length(parameters)} end)
      |> Enum.sort_by(fn {key, _} -> Enum.find_index(definitions, fn {name, [{parameters, _} | _]} -> {name, length(parameters)} == key end) end)
      |> Enum.map_join("\n\n", fn {_, group} ->
        group
        |> Enum.flat_map(fn {name, clauses} -> Enum.map(clauses, &{name, &1}) end)
        |> Enum.map_join(";\n", fn {name, {parameters, guard}} ->
          variables = Enum.map(parameters, &String.capitalize/1)
          guard = if guard, do: " when #{elem(guard, 0)}(#{String.capitalize(elem(guard, 1))})", else: ""
          "#{erlang_atom(name)}(#{Enum.join(variables, ", ")})#{guard} -> {#{Enum.join(variables, ", ")}}"
        end)
        |> Kernel.<>(".")
      end)

    local =
      if primary do
        {name, _} = primary
        "\n\nlocal_site(A, B) -> #{erlang_atom(name)}(A, B). % @local"
      else
        ""
      end

    uses = if uses, do: "\n\nuses(A, B) -> {#{uses}}.", else: ""

    """
    %% #{@header}
    -module(#{module}).
    -export([#{exports}]).

    #{functions}#{local}#{uses}
    """
  end

  defp erlang_atom(name), do: if(name =~ ~r/^[a-z][a-zA-Z0-9_]*$/, do: name, else: "'#{name}'")

  defp render_elixir(form, module, definitions, primary, target) do
    clauses =
      for {name, clauses} <- definitions, clause <- clauses do
        {parameters, guard, head?} = clause_parts(clause)
        rendered = Enum.map_join(parameters, ", ", fn {parameter, default} -> "#{parameter} \\\\ #{default}"; parameter -> parameter end)
        variables = Enum.map(parameters, fn {parameter, _} -> parameter; parameter -> parameter end)
        guard = if guard, do: " when #{elem(guard, 0)}(#{elem(guard, 1)})", else: ""

        cond do
          # A bodiless head declares the defaults for the clauses that follow and defines nothing itself.
          head? -> "  #{form.definer} #{name}(#{rendered})"
          form[:delegate] -> "  defdelegate #{name}(#{rendered}), to: #{target}"
          form[:guard] -> "  #{form.definer} #{name}(#{rendered}) when #{Enum.map_join(variables, " or ", &"is_list(#{&1})")}"
          form[:macro] -> "  #{form.definer} #{name}(#{rendered})#{guard}, do: quote(do: {#{Enum.map_join(variables, ", ", &"unquote(#{&1})")}})"
          true -> "  #{form.definer} #{name}(#{rendered})#{guard}, do: {#{Enum.join(variables, ", ")}}"
        end
      end

    local =
      if primary do
        {name, _} = primary
        "\n\n  def local_site(a, b), do: #{nfc(name)}(a, b) # @local"
      else
        ""
      end

    uses = if primary && form[:private], do: "\n\n  def uses(a, b), do: {#{private_uses(definitions, primary, :elixir)}}", else: ""

    # A delegate's target has no `local_site/2`; this gives it an ASCII-named definition too, so how its `.beam` was
    # built can be checked apart from how the decompiler reads the world's own names.
    marker = if String.ends_with?(module, ".Target"), do: "\n\n  def target_marker, do: :ok", else: ""

    """
    # #{@header}
    defmodule #{module} do
    #{Enum.join(clauses, "\n")}#{local}#{uses}#{marker}
    end
    """
  end

  # Every private definition and arity other than what `local_site` calls, so the compiler warns about none.
  defp private_uses(definitions, primary, language) do
    {primary_name, _} = primary

    definitions
    |> Enum.flat_map(fn {name, [first | _]} ->
      {parameters, _, _} = clause_parts(first)
      defaults = Enum.count(parameters, &is_tuple/1)
      # `local_site` always passes two arguments, whatever the primary's own arity, so that is the one call already
      # made. Excluding the primary's full arity instead only coincided while every primary took two parameters.
      for arity <- (length(parameters) - defaults)..length(parameters), {name, arity} != {primary_name, 2}, do: {name, arity}
    end)
    |> Enum.uniq()
    |> Enum.map_join(", ", fn {name, arity} ->
      arguments = ["a", "b", "a"] |> Enum.take(arity)

      case language do
        :elixir -> "#{nfc(name)}(#{Enum.join(arguments, ", ")})"
        :erlang -> "#{erlang_atom(name)}(#{arguments |> Enum.map(&String.upcase/1) |> Enum.join(", ")})"
      end
    end)
    |> case do
      "" -> ""
      uses -> uses <> ", "
    end
    |> Kernel.<>(if(language == :elixir, do: "a, b", else: "A, B"))
  end

  defp render_caller(backing, form, world, names, calls) do
    references = Enum.map(names, &reference(backing, &1))

    body =
      Enum.map_join(calls, "\n", fn {id, module, name, arity, shape} ->
        body = call(shape, backing, Enum.at(references, module), name, arity)
        parameters = Enum.map_join(["a", "b"], ", ", fn parameter -> if(body =~ ~r/\b#{parameter}\b/, do: parameter, else: "_" <> parameter) end)
        "  def at_#{id}(#{parameters}), do: #{body} # @#{id}"
      end)

    aliases =
      if backing.language == :elixir && !form[:private] do
        "  alias #{hd(references)}\n  alias #{hd(references)}, as: Aliased\n"
      else
        ""
      end

    uses =
      cond do
        form[:private] -> ""
        form[:macro] -> aliases <> Enum.map_join(references, "", &"  require #{&1}\n") <> "  import #{hd(references)}\n"
        true -> aliases <> "  import #{hd(references)}\n"
      end

    """
    # #{@header}
    defmodule Callers.#{Macro.camelize(backing.prefix)}.#{Macro.camelize(form.id)}.#{Macro.camelize(world)} do
    #{uses}
    #{body}
    end
    """
  end

  # No argument list at all. A different shape in the parser, and the only one the unresolved inspection looks at.
  defp call(:no_arguments, backing, module, name, _arity), do: "#{module}.#{call_name(backing, name)}"
  defp call(:qualified, backing, module, name, arity), do: "#{module}.#{call_name(backing, name)}(#{arguments(arity)})"
  defp call(:aliased, backing, module, name, arity), do: "#{last_segment(module)}.#{call_name(backing, name)}(#{arguments(arity)})"
  defp call(:aliased_as, backing, _module, name, arity), do: "Aliased.#{call_name(backing, name)}(#{arguments(arity)})"
  defp call(:unqualified, _backing, _module, name, arity), do: "#{name}(#{arguments(arity)})"
  defp call(:pipe, _backing, _module, name, arity), do: "a |> #{name}(#{arguments(arity - 1) |> String.replace_prefix("a", "b")})"
  defp call(:capture, backing, module, name, arity), do: "{&#{module}.#{call_name(backing, name)}/#{arity}, a, b}"
  defp call(:apply, _backing, module, name, arity), do: "apply(#{module}, :#{name}, [#{arguments(arity)}])"
  defp call(:variable, _backing, _module, name, _arity), do: "(fn #{name} -> #{name} end).({a, b})"
  defp call(:atom, _backing, _module, name, _arity), do: "{:#{name}, a, b}"
  defp call(:keyword, _backing, _module, name, _arity), do: "[#{name}: a, b: b]"

  # Erlang keeps a decomposed name as written, so Elixir must quote it to call it; unquoted, it would normalise it.
  defp call_name(%{language: :erlang}, name), do: if(name == nfc(name), do: name, else: ~s("#{name}"))
  defp call_name(_backing, name), do: name

  defp arguments(arity), do: ["a", "b", "a"] |> Enum.take(arity) |> Enum.join(", ")

  defp last_segment(module), do: module |> String.split(".") |> List.last()

  defp compile_source(%{language: :elixir} = backing, module, path, source) do
    {[{_module, binary}], events} = compile_elixir_modules(path, source)
    {beam_path(backing, module, binary), events}
  end

  defp compile_source(%{language: :erlang} = backing, module, path, _source) do
    options = [:binary, :return_errors, :return_warnings, :deterministic] ++ if(backing.debug_info, do: [:debug_info], else: [])

    {:ok, erlang_module, binary, warnings} = :compile.file(String.to_charlist(path), options)
    if warnings != [], do: raise("#{path} compiled with warnings: #{inspect(warnings)}")
    {:module, ^erlang_module} = :code.load_binary(erlang_module, String.to_charlist(path), binary)

    {beam_path(backing, module, binary), :erlang}
  end

  defp beam_path(%{compiled: false}, _module, _binary), do: nil

  defp beam_path(backing, module, binary) do
    {:ok, name, chunks} = :beam_lib.all_chunks(binary)
    {:ok, stripped} = :beam_lib.build_module(Enum.reject(chunks, fn {id, _} -> id in backing.strip end))
    file = if(backing.language == :elixir, do: "Elixir." <> module, else: module) <> ".beam"
    ^name = if(backing.language == :elixir, do: String.to_atom("Elixir." <> module), else: String.to_atom(module))
    # Where Mix puts a dependency's beams, so the sandbox project sees them exactly as it would a real dependency.
    path = Path.join(["_build", "dev", "lib", backing.id, "ebin", file])
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, stripped)
    path
  end

  defp compile_elixir(path, source) do
    {_modules, events} = compile_elixir_modules(path, source)
    events
  end

  defp compile_elixir_modules(path, source) do
    Matrix.Events.take()
    {modules, diagnostics} = Code.with_diagnostics(fn -> Code.compile_string(source, path) end)
    # An unresolvable delegate's target is missing on purpose.
    diagnostics = Enum.reject(diagnostics, &(&1.message =~ ~r/^\S+\.Missing\.\S+ is undefined \(module \S+\.Missing is not available/))
    if diagnostics != [], do: raise("#{path} compiled with diagnostics: #{inspect(diagnostics)}")
    {modules, Matrix.Events.take()}
  end

  defp caller_sites(path, source, events, calls, backing, names) do
    lines = source |> String.split("\n") |> Enum.with_index(1)

    Enum.map(calls, fn {id, module, name, arity, shape} ->
      {text, line} = Enum.find(lines, fn {text, _} -> String.ends_with?(text, "# @#{id}") end)
      binding = binding(events, path, line, name, shape, backing, Enum.at(names, module), arity)

      %{
        "id" => id,
        "file" => path,
        "line" => line,
        "column" => name_column(text, name),
        "name" => nfc(name),
        "arity" => arity,
        "binding" => binding
      }
    end)
  end

  # The compiler binds nothing at the atom in `apply(M, :name, [...])`, but the plugin treats that atom as a
  # reference to M.name/length([...]), and so does this oracle. A variable, a bare atom and a keyword key bind to no
  # definition.
  defp binding(_events, _path, _line, name, :apply, backing, module, arity),
    do: %{"module" => reference(backing, module), "name" => nfc(name), "arity" => arity, "kind" => "apply"}

  defp binding(_events, _path, _line, _name, shape, _backing, _module, _arity) when shape in [:variable, :atom, :keyword], do: nil

  defp binding(events, path, line, name, _shape, _backing, _module, _arity) do
    atom = String.to_atom(name)

    case Enum.filter(events, &(&1.file |> Path.relative_to_cwd() == path and &1.line == line and &1.name in [atom, String.to_atom(nfc(name))])) do
      [event] -> %{"module" => inspect(event.module), "name" => to_string(event.name), "arity" => event.arity, "kind" => to_string(event.kind)}
      events -> raise("#{path}:#{line} has #{length(events)} traced calls to #{name}: #{inspect(events)}")
    end
  end

  # Erlang is compiled without the Elixir tracer, but its only marked call is `local_site`'s local call.
  defp local_sites(path, source, events, backing, module, {name, _}) do
    lines = source |> String.split("\n") |> Enum.with_index(1)
    {text, line} = Enum.find(lines, fn {text, _} -> String.ends_with?(text, "@local") end)

    binding =
      if events == :erlang do
        %{"module" => reference(backing, module), "name" => name, "arity" => 2, "kind" => "local_function"}
      else
        binding(events, path, line, nfc(name), :local, backing, module, 2)
      end

    [
      %{
        "id" => "local",
        "file" => path,
        "line" => line,
        "column" => name_column(text, nfc(name)),
        "name" => nfc(name),
        "arity" => 2,
        "binding" => binding
      }
    ]
  end

  # A site's column is where the target's name starts after `do:` (or `->` in Erlang), counted in UTF-16 code units
  # as the IDE's document offsets are.
  defp name_column(text, name) do
    [{body_start, _}] = Regex.run(~r/do: |-> /, text, return: :index)
    escaped = Regex.escape(name)
    pattern = ~r/(?<![\w.:?!"])#{escaped}(?![\w?!\x{0300}-\x{036F}])|(?<=[.:"])#{escaped}(?![\w?!\x{0300}-\x{036F}])/u
    [{start, _}] = Regex.run(pattern, text, return: :index, offset: body_start)
    utf16_length(binary_part(text, 0, start)) + 1
  end

  defp utf16_length(text), do: text |> :unicode.characters_to_binary(:utf8, :utf16) |> byte_size() |> div(2)

  defp declarations(source) do
    source
    |> String.split("\n")
    |> Enum.with_index(1)
    |> Enum.flat_map(fn {text, line} ->
      # `\s*$` matches a bodiless head, which declares the defaults and defines nothing.
      case Regex.run(~r/^\s*(def|defp|defmacro|defmacrop|defguard|defguardp|defdelegate) ([^\s(]+)\((.*?)\)(?: when |, do:|, to:|\s*$)/u, text, return: :index) do
        [_, {definer_start, definer_length}, {name_start, name_length}, {parameters_start, parameters_length}] ->
          name = binary_part(text, name_start, name_length)
          parameters = binary_part(text, parameters_start, parameters_length) |> String.split(", ", trim: true)

          if name in ["local_site", "uses"] do
            []
          else
            [%{"name" => nfc(name), "arity" => length(parameters), "definer" => binary_part(text, definer_start, definer_length), "line" => line, "column" => utf16_length(binary_part(text, 0, name_start)) + 1}]
          end

        nil ->
          []
      end
    end)
    |> Enum.group_by(&{&1["name"], &1["arity"]})
    |> Enum.flat_map(fn {_, clauses} -> clauses |> Enum.with_index() |> Enum.map(fn {clause, index} -> Map.put(clause, "clause", index) end) end)
    |> Enum.sort_by(&{&1["line"], &1["column"]})
  end

  # Every file this script writes, found by walking the directories it wipes at the start rather than by listing
  # what the oracle happens to name. Enumerating the oracle's own keys left the broken callers and the provenance
  # beams unhashed - 155 files holding 259 marked sites - so a hand-edit to one of them moved hundreds of carets
  # with the guard still green. A fixture the oracle does not mention is exactly the one nothing else would catch.
  #
  # `oracle.json` is hashed too: it is the expectations themselves, so an edit to it is the one that changes what
  # the matrix asserts. It is written before this runs, so hashing it here is safe.
  defp manifest(_scenarios) do
    files =
      @generated_directories
      |> Enum.flat_map(&Path.wildcard(Path.join(&1, "**/*")))
      |> Enum.reject(&File.dir?/1)
      |> Kernel.++(["oracle.json"])
      |> Enum.sort()
      |> Map.new(&{&1, :crypto.hash(:sha256, File.read!(&1)) |> Base.encode16(case: :lower)})

    %{"header" => @header, "sha256" => files}
  end
end

Matrix.run()
