# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.W2.ImportTransitive.Middle do
  import ExDocs.Defguard.W2
  def middle_marker, do: :ok
end

defmodule Callers.ExDocs.Defguard.W2.ImportTransitive do
  import Callers.ExDocs.Defguard.W2.ImportTransitive.Middle

  def at_import_transitive(a, b), do: ex_docs_defguard_w2_snoc(a, b) # @import_transitive
end

