# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.W2.ImportOnly do
  import ExDocs.Defguard.W2, only: [ex_docs_defguard_w2_snoc: 1] # @import_only_key

  def at_import_only_1(a, _b), do: ex_docs_defguard_w2_snoc(a) # @import_only_1
end

defmodule Callers.ExDocs.Defguard.W2.ImportExcept do
  import ExDocs.Defguard.W2, except: [ex_docs_defguard_w2_snoc: 1] # @import_except_key

  def at_import_except_2(a, b), do: ex_docs_defguard_w2_snoc(a, b) # @import_except_2
end
