# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.XArityAbsentUndefined do
  alias ExDocs.Defguard.XArityAbsent
  alias ExDocs.Defguard.XArityAbsent, as: Aliased
  require ExDocs.Defguard.XArityAbsent
  import ExDocs.Defguard.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_docs_defguard_x_arity_absent_snoc(a) # @unqualified_arity_1
end
