# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.XArityAbsent do
  alias ExDocs.Defguard.XArityAbsent
  alias ExDocs.Defguard.XArityAbsent, as: Aliased
  require ExDocs.Defguard.XArityAbsent
  import ExDocs.Defguard.XArityAbsent

  def at_qualified(a, b), do: ExDocs.Defguard.XArityAbsent.ex_docs_defguard_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.ex_docs_defguard_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defguard_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defguard_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defguard_x_arity_absent_snoc(b) # @pipe
end
