# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.XNfcBroken do
  alias ExDocs.Defguard.XNfc
  alias ExDocs.Defguard.XNfc, as: Aliased
  require ExDocs.Defguard.XNfc
  import ExDocs.Defguard.XNfc

  def at_arity_1(a, _b), do: ExDocs.Defguard.XNfc.ex_docs_defguard_x_nfc_snoć(a) # @arity_1
end
