# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExDocs.Defguard.XNotACall do
  alias ExDocs.Defguard.XNotACall
  alias ExDocs.Defguard.XNotACall, as: Aliased
  require ExDocs.Defguard.XNotACall
  import ExDocs.Defguard.XNotACall

  def at_qualified(a, b), do: ExDocs.Defguard.XNotACall.ex_docs_defguard_x_not_a_call_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XNotACall.ex_docs_defguard_x_not_a_call_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_docs_defguard_x_not_a_call_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_docs_defguard_x_not_a_call_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_docs_defguard_x_not_a_call_snoc(b) # @pipe
  def at_variable(a, b), do: (fn ex_docs_defguard_x_not_a_call_snoc -> ex_docs_defguard_x_not_a_call_snoc end).({a, b}) # @variable
  def at_atom(a, b), do: {:ex_docs_defguard_x_not_a_call_snoc, a, b} # @atom
  def at_keyword(a, b), do: [ex_docs_defguard_x_not_a_call_snoc: a, b: b] # @keyword
end
