# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defguard.XArityAbsentUndefined do
  alias ExGen.Defguard.XArityAbsent
  alias ExGen.Defguard.XArityAbsent, as: Aliased
  require ExGen.Defguard.XArityAbsent
  import ExGen.Defguard.XArityAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_defguard_x_arity_absent_snoc(a) # @unqualified_arity_1
end
