# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defguard.XLookalikeAbsentUndefined do
  alias ExGen.Defguard.XLookalikeAbsent
  alias ExGen.Defguard.XLookalikeAbsent, as: Aliased
  require ExGen.Defguard.XLookalikeAbsent
  import ExGen.Defguard.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_defguard_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
