# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Defguard.XNfc do
  alias ExGen.Defguard.XNfc
  alias ExGen.Defguard.XNfc, as: Aliased
  require ExGen.Defguard.XNfc
  import ExGen.Defguard.XNfc

  def at_qualified(a, b), do: ExGen.Defguard.XNfc.ex_gen_defguard_x_nfc_snoć(a, b) # @qualified
  def at_aliased(a, b), do: XNfc.ex_gen_defguard_x_nfc_snoć(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_defguard_x_nfc_snoć(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_defguard_x_nfc_snoć(a, b) # @unqualified
end
