# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateAs.XDefaults.RequireOnly do
  require Src.DefdelegateAs.XDefaults

  def at_require_only(a, b), do: src_defdelegate_as_x_defaults_snoc(a, b) # @require_only
end
