# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.DefdelegateAs.XDefaults.ImportExcept1 do
  import Src.DefdelegateAs.XDefaults, except: [src_defdelegate_as_x_defaults_snoc: 1] # @import_except_1_key

  def at_import_except_1(a, _b), do: src_defdelegate_as_x_defaults_snoc(a) # @import_except_1
end
