# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XArityZeroBroken do
  alias ExGen.Def.XArityZero
  alias ExGen.Def.XArityZero, as: Aliased
  import ExGen.Def.XArityZero

  def at_arity_1(a, _b), do: ExGen.Def.XArityZero.ex_gen_def_x_arity_zero_snoc(a) # @arity_1
end
