# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XArityAbsent do
  alias ExGen.Def.XArityAbsent
  alias ExGen.Def.XArityAbsent, as: Aliased
  import ExGen.Def.XArityAbsent

  def at_qualified(a, b), do: ExGen.Def.XArityAbsent.ex_gen_def_x_arity_absent_snoc(a, b) # @qualified
  def at_aliased(a, b), do: XArityAbsent.ex_gen_def_x_arity_absent_snoc(a, b) # @aliased
  def at_aliased_as(a, b), do: Aliased.ex_gen_def_x_arity_absent_snoc(a, b) # @aliased_as
  def at_unqualified(a, b), do: ex_gen_def_x_arity_absent_snoc(a, b) # @unqualified
  def at_pipe(a, b), do: a |> ex_gen_def_x_arity_absent_snoc(b) # @pipe
  def at_capture(a, b), do: {&ExGen.Def.XArityAbsent.ex_gen_def_x_arity_absent_snoc/2, a, b} # @capture
  def at_apply(a, b), do: apply(ExGen.Def.XArityAbsent, :ex_gen_def_x_arity_absent_snoc, [a, b]) # @apply
end
