# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XDefaultsHeadBroken do
  alias ExGen.Def.XDefaultsHead
  alias ExGen.Def.XDefaultsHead, as: Aliased
  import ExGen.Def.XDefaultsHead

  def at_arity_3(a, b), do: ExGen.Def.XDefaultsHead.ex_gen_def_x_defaults_head_snoc(a, b, a) # @arity_3
end
