# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XLookalikeAbsentUndefined do
  alias ExGen.Def.XLookalikeAbsent
  alias ExGen.Def.XLookalikeAbsent, as: Aliased
  import ExGen.Def.XLookalikeAbsent

  def at_unqualified_arity_1(a, _b), do: ex_gen_def_x_lookalike_absent_snoc(a) # @unqualified_arity_1
end
