# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.ExGen.Def.XNfcBroken do
  alias ExGen.Def.XNfc
  alias ExGen.Def.XNfc, as: Aliased
  import ExGen.Def.XNfc

  def at_arity_1(a, _b), do: ExGen.Def.XNfc.ex_gen_def_x_nfc_snoć(a) # @arity_1
end
