# Generated by generate.exs; do not edit. Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/code_insight/code_intelligence_matrix.
defmodule Callers.Src.Defmacrop.XDefaults.ImportWhole do
  import Src.Defmacrop.XDefaults

  def at_import_whole(a, b), do: src_defmacrop_x_defaults_snoc(a, b) # @import_whole
end
